### ISSUE TITLE
1. github无法正常翻译  2. 是否可以修改为选中即翻 点一下和右侧显示都会麻烦且挡视线  3.能否增加全页面无跳转的翻译

### ISSUE THREAD

**Issue by truelv** [EdgeTranslate/EdgeTranslate#10]

**Comment by Mark-Fritz** [comment]
1. 请问使用的是 firefox 浏览器还是 chrome 系列的浏览器, 是否可以给出更加具体的描述
2. 选中单词或句子立即翻译的功能需要在设置选项里开启,默认是不开启的
设置方法如果不太清楚,详见 https://github.com/nickyc975/EdgeTranslate/wiki/Manual 中的选中立即翻译这一项
3. 这个其实一直想增加来着, 但是无奈实现难度较高,一直没有时间去弄,以后尽量实现

**Comment by truelv** [comment]
1. 浏览器是firefox的

**Comment by nickyc975** [comment]
最新的1.5.0已经实现了这些功能，请下载体验。
