### ISSUE TITLE
添加语言选项

### ISSUE THREAD

**Issue by gjw152** [EdgeTranslate/EdgeTranslate#100]
对于在使用英文作业系统中的侧栏翻译会出现英文翻译成英文的情况,无法自定义欲翻译的语言。

**Comment by nickyc975** [comment]
目标语言设定功能是有的，参考 #97

**Comment by gjw152** [comment]
点击翻译按钮选择语言是有的
但这里主要指的是侧栏翻译。

**Comment by gjw152** [comment]
刚发现edge浏览器下得重新选择语言侧栏翻译才会生效。遇到同样问题的可试试看
