### ISSUE TITLE
新增驼峰命名字符串拆分翻译功能

### ISSUE THREAD

**Issue by youyiqin** [EdgeTranslate/EdgeTranslate#101]
**功能描述**
常见的大小驼峰命名字符串无法翻译
_你想要什么样的功能 /改进？_
对驼峰命名的词语进行拆分和翻译
**使用场景**
文档翻译
_你是在什么场景下需要用到这个功能 /改进？_
常用

**解决方案**
获取翻译目标的时候,加一层判断,如果符合[骆驼命名法_百度百科](https://baike.baidu.com/item/%E9%AA%86%E9%A9%BC%E5%91%BD%E5%90%8D%E6%B3%95) 的格式,则尝试拆分单词再翻译.

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_
手动用鼠标选择翻译的部分字符串进行翻译

**Comment by nickyc975** [comment]
这个有一个问题，就是似乎没什么算法能够将符合驼峰命名规则的字符串和带有大写字母的专有名词区分开。

比如sRGB这个字符串显然是符合驼峰命名规则的，但是这是一整个单词而不是几个单词组成的字符串，如果按照驼峰命名规则进行切分的话就出问题了。

**Comment by youyiqin** [comment]
@Mark-Fenng 那么能否在设置里增加一个可选的设置,以单独支持拆分 a_b_c 这种以下划线分割的字符串?或者以"-"分割.
