### ISSUE TITLE
错误：服务器无法完成您的请求。你稍后重试

### ISSUE THREAD

**Issue by ljc520313** [EdgeTranslate/EdgeTranslate#103]
chrome-84.0.4147.105  EdgeTranslate-1.9.1，单击谷歌网页翻译，报如下错误
![image](https://user-images.githubusercontent.com/7116096/88763077-1035ed00-d1a5-11ea-9e25-1f9068d126bd.png)

**Comment by Mark-Fenng** [comment]
部分网站有非常严格的安全策略，网页翻译的代码不被执行，这个我们也没有办法

**Comment by ljc520313** [comment]
谢谢

**Comment by nickyc975** [comment]
如果谷歌网页翻译用不了的话可以试试用网易网页翻译
