### ISSUE TITLE
希望增加仅在 PDF 中双击/划词立即翻译

### ISSUE THREAD

**Issue by imhuay** [EdgeTranslate/EdgeTranslate#104]
**功能描述**

仅在 PDF 内双击/划词立即翻译

**使用场景**

目前的立即翻译功能不区分使用场景，在任何场合都会展开侧边栏，希望可以支持仅在阅读 PDF 时启用立即翻译功能

**Comment by nickyc975** [comment]
你可以选择只开启双击立即翻译，这样正常选择文本的时候就不会产生干扰了。
