### ISSUE TITLE
chromium浏览器不能使用

### ISSUE THREAD

**Issue by 5201413** [EdgeTranslate/EdgeTranslate#107]
如题,百度,google都不能翻译

**Comment by Mark-Fenng** [comment]
没有看懂，你说的是什么不能翻译，是百度网页上不能使用吗

**Comment by 5201413** [comment]
> 没有看懂，你说的是什么不能翻译，是百度网页上不能使用吗

就是安装完翻译不了页面 比如用goole的翻译是这样的
![截屏2020-08-11 上午10 29 53](https://user-images.githubusercontent.com/25979676/89888942-64a88600-dc03-11ea-8134-f6defbb47ca0.png)

**Comment by Mark-Fenng** [comment]
有道的网页翻译确实不能用了，是个问题，我们再看一下
谷歌的网页翻译在大部分页面还是可以用的，只是个别页面例如github的安全策略，禁止了翻译的请求
