### ISSUE TITLE
更新后无法使用内置pdf查看器

### ISSUE THREAD

**Issue by sssssy** [EdgeTranslate/EdgeTranslate#108]
**描述问题**

更新后，读入PDF文件时，无论从网页html链接、从本地打开，都无法正常显示pdf
可以显示完整的界面框架，但是没有内容
标签页标题显示PDF.js viewer
尝试多个pdf文件，以及新下载的pdf文件都是同样情况
（已经打开访问本地文件的权限）

**出现问题的网址**

无

**复现步骤**

以任意方式打开pdf文件

**问题截图**

**使用环境**

Chrome Version 84.0.4147.125 (Official Build) (64-bit)

Edge Translation 1.9.2

**其他信息**

大约两天前，自动更新之后出现如上问题

**Comment by Mark-Fenng** [comment]
不好意思，这次发布前测试工作没有做到位，尽快修复

**Comment by amir96** [comment]
I have this problem, too.
