### ISSUE TITLE
翻译启用禁用控制

### ISSUE THREAD

**Issue by iamsurfing** [EdgeTranslate/EdgeTranslate#11]
**功能描述**

管理中添加两种模式，默认启用翻译和默认禁用翻译。
然后右键菜单加一个对本页面(启用\禁用)翻译。

**使用场景**

我很少看英文，但是看英文的时候我希望快捷翻译。但是在不需要翻译的时候就会感觉碍事。
老是到设置中更改觉得很麻烦。

**你的解决方案**

如上

**替代方案**

改设置，或者禁用插件

**其他信息**

无

**Comment by nickyc975** [comment]
感谢反馈，我们后续会加上这个功能的。
