### ISSUE TITLE
翻译超时

### ISSUE THREAD

**Issue by 13015517713** [EdgeTranslate/EdgeTranslate#110]
**有时候划词翻译之后，右边一直在加载，网络是没问题的，原来没有这样的状况，原来直接划词就可以翻译了。**
**是翻译接口调用的方式修改了吗？**

**Comment by Mark-Fenng** [comment]
这部分一直没有变过，通常情况是网络不稳定，谷歌服务器的问题或者本地的网络代理设置有问题。
如果不是这些原因的话，希望你提供一下版本号，浏览器类型等信息，帮助我们排查问题。

**Comment by 13015517713** [comment]
Firefox BroWSER 79.0 (64 位)
EdgeTranslate     1.9.2

**Comment by 13015517713** [comment]
老版本好像是没这样问题的，这是我最近更新了

**Comment by 13015517713** [comment]
有时候直接能翻译，有时候翻译的很慢或者翻译结果出不来

**Comment by Mark-Fenng** [comment]
你的大致地理位置是哪里，目前使用的是谷歌翻译的cn接口

**Comment by 13015517713** [comment]
中国内陆，谷歌的翻译通过网页正常使用。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EdgeTranslate/EdgeTranslate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 上午10:42
收件人:&nbsp;"EdgeTranslate/EdgeTranslate"<EdgeTranslate@noreply.github.com&gt;;
抄送:&nbsp;"萌级小菜鸟"<2430278602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EdgeTranslate/EdgeTranslate] 翻译超时 (#110)





 
你的大致地理位置是哪里，目前使用的是谷歌翻译的cn接口

**Comment by Mark-Fenng** [comment]
我这是实在是复现不出来，都是秒出结果，你要不切换个网络环境（比如用流量，换个网）再试试

**Comment by 13015517713** [comment]
请问您的版本和我是一致的吗，不过这个确实可能是我网络的问题哈。 我看火狐扩展评价中也有加载很慢，所以问了下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EdgeTranslate/EdgeTranslate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 上午10:49
收件人:&nbsp;"EdgeTranslate/EdgeTranslate"<EdgeTranslate@noreply.github.com&gt;;
抄送:&nbsp;"萌级小菜鸟"<2430278602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EdgeTranslate/EdgeTranslate] 翻译超时 (#110)





 
我这是实在是复现不出来，都是秒出结果，你要不切换个网络环境（比如用流量，换个网）再试试

**Comment by Mark-Fenng** [comment]
@13015517713  浏览器版本和扩展版本一模一样，不管如何，欢迎来讨论。
如果下次出现无法翻译的问题，麻烦留意一下错误码或者看看控制台有什么报错信息
