### ISSUE TITLE
干扰网页样式（类选择器.container）

### ISSUE THREAD

**Issue by zhongjimeiying** [EdgeTranslate/EdgeTranslate#115]
**网页样式受到了影响**

最近扩展自动更新后，打开公司内部网站，发现页面排版出现错误，但是在其他人电脑上没有出现这个问题。经过排查，发现.container类选择器样式导致了变化，进入样式查看器跟踪来源，显示为扩展文件样式。尝试禁用扩展后，问题消失。

**问题截图**

禁用扩展
![1](https://user-images.githubusercontent.com/41845617/93411288-63870a80-f8cd-11ea-8e7a-4204193098d2.JPG)

启用扩展
![2](https://user-images.githubusercontent.com/41845617/93411326-7e597f00-f8cd-11ea-81b7-8abc62c6a050.JPG)

**使用环境**

_浏览器类型 [firefox]_

_浏览器版本 [80.0b3 (64 位)]_

_插件版本 [2.0.0]_

**其他信息**

网页中使用到的.container 类选择器是引入了bootstrap的样式。建议扩展的样式通过增加前缀等方式避免冲突

**Comment by nickyc975** [comment]
收到，我们尽快修复。

**Comment by zifeng991** [comment]
同火狐80.0.1 (64 位)，2.0.0 
CSDN界面乱了

**Comment by Xydawn** [comment]
同火狐浏览器80.0.1 (64 位)  
发现有很多网站都有样式干扰,如CSDN OSCHINA等.

**Comment by nickyc975** [comment]
> 同火狐浏览器80.0.1 (64 位)
> 发现有很多网站都有样式干扰,如CSDN OSCHINA等.

问题已经修复，请更新到2.0.1
