### ISSUE TITLE
csdn stackoverflow等网站 排版错误

### ISSUE THREAD

**Issue by kainanxu** [EdgeTranslate/EdgeTranslate#116]
**描述问题**
firefox
csdn stackoverflow等网站 排版错误

**出现问题的网址**

https://stackoverflow.com/questions/29511521/is-key-required-as-part-of-sending-messages-to-kafka 等等等等

**复现步骤**

2.0.0版本
启用插件, 访问以上网站即可, 关闭禁用插件后网页立刻恢复正常(不用刷新)

**问题截图**

![图片](https://user-images.githubusercontent.com/25890915/93448711-7a961e80-f906-11ea-99fd-39712bd5df44.png)

**使用环境**

![图片](https://user-images.githubusercontent.com/25890915/93448796-913c7580-f906-11ea-8e5d-3a8137fa0d6f.png)
win10
![图片](https://user-images.githubusercontent.com/25890915/93448876-ab765380-f906-11ea-9aee-5dc046940809.png)

**Comment by Mark-Fenng** [comment]
问题已经修复，请尽快更新v2.0.1
