### ISSUE TITLE
好像新的版本2.0.0在火狐上会造成一些页面样式错位的问题

### ISSUE THREAD

**Issue by tianyu924** [EdgeTranslate/EdgeTranslate#117]
**描述问题**

好像新的版本2.0.0在火狐上会造成一些页面样式错位的问题

**出现问题的网址**

https://blog.csdn.net/fantexi1984/article/details/52670390

**复现步骤**

反复开启关闭插件，然后刷新网页即可

**问题截图**

未开启的网页截图：
![火狐截图_2020-09-17T13-57-10 303Z](https://user-images.githubusercontent.com/6048086/93481238-ed1bf400-f930-11ea-96dd-0e4a89ecf057.png)
开启后的网页截图：
![火狐截图_2020-09-17T13-57-37 807Z](https://user-images.githubusercontent.com/6048086/93481264-f4db9880-f930-11ea-9b09-20b9f678dd0a.png)

**使用环境**
window10 64位

_浏览器类型 [firefox]_

_浏览器版本 [80.0.1]_

_插件版本 [2.0.0]_

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
感谢反馈，这个问题确实很严重，已经修复，麻烦您及时更新一下
