### ISSUE TITLE
这个拼音？

### ISSUE THREAD

**Issue by crazyair** [EdgeTranslate/EdgeTranslate#118]
![image](https://user-images.githubusercontent.com/7971419/93545326-b2e33e80-f992-11ea-802f-111d0403d1ec.png)

**Comment by nickyc975** [comment]
你用的哪个翻译源？

**Comment by crazyair** [comment]
> 你用的哪个翻译源？是混合源吗？

混合的，来回试了下，必应是 yin fa

**Comment by crazyair** [comment]
用这个单词测试 

triggered

**Comment by nickyc975** [comment]
已修复
