### ISSUE TITLE
三击选择段落功能优化

### ISSUE THREAD

**Issue by noncomfortzone** [EdgeTranslate/EdgeTranslate#119]
**Firefox 下三击选择段落无法弹出翻译图标**

早期的版本的时候，在 Firefox 之中，三击选择段落，会浮出侧边翻译的图标，点击直接翻译，很方便。最近的版本双击的时候，图标会闪动一下就消失。唯一的办法就是拖动鼠标选择才能正常工作。

相似的问题只在 Firefox 中出现，Edge 和 Chrome 都行为正常。希望能够修复类似的问题。

我用的 Firefox 版本是 80.0.1 (64 位)。

非常感谢，这个插件是用过的翻译插件中最好的一个。

**Comment by Mark-Fenng** [comment]
感谢反馈，可以提供下出现问题的网址吗，据我的实验，并不是所有网站都出现这个问题

**Comment by noncomfortzone** [comment]
几乎所有网站，随便打开一个 github 就能复现。-------- 原始邮件 --------发件人： 踩坑小王子 <notifications@github.com>日期： 2020年9月18日周五 10:48收件人： EdgeTranslate/EdgeTranslate <EdgeTranslate@noreply.github.com>抄送： noncomfortzone <cjp.pku@gmail.com>, Author <author@noreply.github.com>主    题： Re: [EdgeTranslate/EdgeTranslate] Firefox 下双击选择段落无法弹出翻译图标 (#119)

感谢反馈，可以提供下出现问题的网址吗，据我的实验，并不是所有网站都出现这个问题

**Comment by nickyc975** [comment]
收到，三击选择段落这个确实是我们没考虑到的，之后会想办法优化。
