### ISSUE TITLE
firefox下github页面无法翻译

### ISSUE THREAD

**Issue by kvinwang** [EdgeTranslate/EdgeTranslate#12]
**描述问题**

firefox下尝试翻译github上的文本侧边面板空白

**出现问题的网址**

https://github.com

**复现步骤**

随便选择一个词翻译

**问题截图**

![image](https://user-images.githubusercontent.com/6442159/53928169-216bee80-40c4-11e9-9418-8038da232e07.png)

**使用环境**

Firefox nightly 67.0a1 (2019-03-06) (64-bit)
macOS 10.12.6 (16G29)
插件版本：1.4.1

**Comment by nickyc975** [comment]
感谢反馈，这是已知问题，develop分支上已经修复了，下个版本生效。

**Comment by luoqishuai** [comment]
请问你你们解决了吗？
现在版本是 1.5.0 我依旧无法在firefox上面翻译github的内容

**Comment by nickyc975** [comment]
已经解决了，请更新最新的 1.6.1 版。

**Comment by luoqishuai** [comment]
好像我应该提供更详细的信息。你说你需要什么，我列给你。
刚刚移除组件后，重新安装（版本1.6.1)，并且关闭所有firefox浏览器（版本66.0.3 ）重新启动。
然后在https://github.com/  右键->侧边翻译->google翻译。
无反应。。。

**Comment by nickyc975** [comment]
谷歌翻译的网页翻译功能在github上无法使用，这个无解，请使用有道的网页翻译。

**Comment by luoqishuai** [comment]
好吧。最近我用百度翻译，发现英译中  、关于 机器学习 方向的论文，翻译的效果比其它的强。。起码我看来是

**Comment by nickyc975** [comment]
嗯，我们后续看看能不能把百度翻译的接口加上。
