### ISSUE TITLE
请问windows edge浏览器打开本地pdf文件时会默认调用自己的viewer，从而不能使用侧边翻译

### ISSUE THREAD

**Issue by kaisquares** [EdgeTranslate/EdgeTranslate#121]
请问windows edge浏览器打开本地pdf文件时会默认调用自己的viewer，而不是侧边翻译内建的js pdf viewer，从而不能使用侧边翻译，有没有办法改变？或者未来会不会针对edge浏览器自己的viewer做一些适配？

**Comment by nickyc975** [comment]
请在插件设置中打开“允许访问文件链接”

**Comment by kaisquares** [comment]
> 请在插件设置中打开“允许访问文件链接”

感谢，居然是这个原因~~谢谢
