### ISSUE TITLE
与Swagger UI页面兼容

### ISSUE THREAD

**Issue by WangScaler** [EdgeTranslate/EdgeTranslate#122]
**打不开本地部署的网页**

_当我在火狐上安装了这个插件，再打开我开发过程中部署的SwaggerUI，结果打不开，当我卸载了这个插件，就又能打开了，不知道是火狐的问题，还是你们插件的原因。_

**SwaggerUI本地部署地址**

**使用环境**

_浏览器类型 [e.g. chrome, firefox]_

_浏览器版本 [e.g. 80.0.1]_

_插件版本 [e.g. 2.0.1]_

**Comment by nickyc975** [comment]
收到，我们尽快修复。

**Comment by nickyc975** [comment]
与 #39 应该是同一问题。

**Comment by Mark-Fenng** [comment]
> 与 #39 应该是同一问题。

相同的表现，但是问题原因却没有关系
