### ISSUE TITLE
在pdf进行划词时存在的鼠标失准、分词bug的问题和一些建议

### ISSUE THREAD

**Issue by sssssy** [EdgeTranslate/EdgeTranslate#123]
0. 请原谅我这种把建议和bug反馈放到一个issue的行为，如果造成混乱实在抱歉

1. 在pdf划词时，经常出现划到的词并非鼠标实际点选位置的情况（大概有0.5~2个字符的误差），不知道是否与缩放有关（浏览器缩放、屏幕缩放、pdf阅读器内部缩放）

2. 与问题1类似，在划词（无论双击还是拖拽）时，接近段落开头结尾、行开头结尾时，很容易划到整段或者整页，较影响使用体验

3. 使用双击选择词的时候，会有把许多词识别成一个词（即分词失效）的bug，经常出现；使用鼠标拖拽划词的时候，提供给翻译的文本有时也会出现分词失效的bug。当然，也可能跟pdf自身格式有关，但是在其他阅读器上选取文本的分词bug概率要比这里的pdf viewer的bug概率小很多。（包括翻译插件的反馈结果、包括复制粘贴得到的结果）

4. 【针对问题3的建议】建议在翻译页面加入编辑翻译原文的功能，在翻译区域上加入【重新翻译】按钮，在一些情况下可以手动分词

5. 【额外的建议】相对于网页上的使用很流畅的翻译功能而言，pdf viewer的翻译体验还有很多可以提升的地方。但是这个阅读器打开、渲染pdf的速度很快，给一个赞！！另外，如果能加入简单的高亮（荧光笔）、划线、批注功能，使用体验会更加完美，希望考虑一下，辛苦！！！

**Comment by nickyc975** [comment]
1. 我们使用的是一个开源的pdf阅读器，叫做pdf.js，pdf阅读器的功能比较复杂，我们没有足够的时间去自己做或者魔改，所以暂时不能为其添加新功能了；

2. 分词不准这个问题应该跟缩放有关，可以试着调一下，除此之外我们也没有更好的办法；

3. 选词后允许编辑和重新翻译是个不错的建议，我们会考虑加入的；
