### ISSUE TITLE
Firefox浏览器下字体与背景颜色一致导致翻译内容不显示

### ISSUE THREAD

**Issue by CHEN-Jing194** [EdgeTranslate/EdgeTranslate#125]
![屏幕截图 2020-09-29 092214](https://user-images.githubusercontent.com/49305655/94501820-4a6b4b80-0235-11eb-89fb-238997a1410d.png)

windows深色模式
Firefox开发者版82.0b4

**Comment by Mark-Fenng** [comment]
收到，感谢反馈

**Comment by Mark-Fenng** [comment]
> ![屏幕截图 2020-09-29 092214](https://user-images.githubusercontent.com/49305655/94501820-4a6b4b80-0235-11eb-89fb-238997a1410d.png)
> 
> windows深色模式
> Firefox开发者版82.0b4

请问是整个网页都变成了黑色背景吗，如何做到的

**Comment by nblog** [comment]
Microsoft Edge Dev 版 出现同样的问题
网站: https://guidedhacking.com

![Snipaste_2020-11-12_11-10-24](https://user-images.githubusercontent.com/10218627/98890795-bd740d00-24d7-11eb-856d-a659a2f44229.png)

**Comment by Mark-Fenng** [comment]
@nblog 你使用了什么调整颜色的扩展

**Comment by nblog** [comment]
> @nblog 你使用了什么调整颜色的扩展

没有其他调整颜色相关的扩展  这个是网站本身就是这种颜色

**Comment by Mark-Fenng** [comment]
@nblog 好的，感谢反馈，知道是什么问题了
