### ISSUE TITLE
使用侧面翻译时一直显示没有网络连接，但我是有网络的

### ISSUE THREAD

**Issue by tristanccp** [EdgeTranslate/EdgeTranslate#126]
**描述问题**

_请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**出现问题的网址**

_如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**复现步骤**

_请在此给出问题的复现步骤_

**问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

_在这里给出你的使用环境，例如：_

_浏览器类型 [e.g. chrome, firefox]_

_浏览器版本 [e.g. 22]_

_插件版本 [e.g. 1.2.0]_

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
可以描述一下使用的翻译源类型吗，比如是谷歌翻译，还是必应 百度

**Comment by tristanccp** [comment]
我每个都试了一下,没有, 但是刚刚又好了, 所以就不好再找原因了😓

踩坑小王子 <notifications@github.com> 于2020年9月29日周二 上午11:09写道：

**Comment by nickyc975** [comment]
这个可能是你那边暂时的网络波动吧。
