### ISSUE TITLE
部分翻译源未处理HTML字符转义

### ISSUE THREAD

**Issue by cn-kristopher** [EdgeTranslate/EdgeTranslate#127]
**描述问题**

**出现问题的网址:
https://docs.spring.io/spring-framework/docs/5.1.18.RELEASE/spring-framework-reference/core.html#spring-core

**问题截图**

![Uploading image.png…]()

**使用环境**

_在这里给出你的使用环境，例如：_

_浏览器类型 新版microsoft edge

_插件版本 2.02

**Comment by Mark-Fenng** [comment]
感谢反馈 ，不过你的截图好像没有上传成功

**Comment by cn-kristopher** [comment]
张宝亭-------- 原始邮件 --------发件人： 踩坑小王子 <notifications@github.com>日期： 2020年9月29日周二 晚上7:03收件人： EdgeTranslate/EdgeTranslate <EdgeTranslate@noreply.github.com>抄送： cn-kristopher <17667374819@qq.com>, Author <author@noreply.github.com>主    题： Re: [EdgeTranslate/EdgeTranslate] 当选定文本中含有特殊格式时,弹出窗口显示不正常. (#127)

感谢反馈 ，不过你的截图好像没有上传成功

**Comment by nickyc975** [comment]
问题收到，正在修复。

**Comment by nickyc975** [comment]
已修复，下个版本生效。
