### ISSUE TITLE
与octortree插件冲突

### ISSUE THREAD

**Issue by CongLinDev** [EdgeTranslate/EdgeTranslate#128]
**描述问题**

与octortree插件冲突，详细见图。

**出现问题的网址**

www.github.com

**问题截图**

![image.png](https://i.loli.net/2020/09/30/LsbcMQve47Sugw3.png)

**使用环境**

_在这里给出你的使用环境，例如：_

_浏览器类型 [edge]_

_浏览器版本 [85.0.564.63]_

_插件版本 [2.0.2]_

**Comment by nickyc975** [comment]
收到，我们会尽快确认并修复。
