### ISSUE TITLE
插件导致guru3d.com样式出错

### ISSUE THREAD

**Issue by RealXuChe** [EdgeTranslate/EdgeTranslate#129]
我在使用:
Firefox 82.0b5
EdgeTranslate 2.0.2
Windows_NT 10.0 19041

**复现步骤**

打开[这篇文章](https://www.guru3d.com/articles_pages/clocktuner_for_ryzen_ctr_guide_download,1.html), 使用"谷歌网页翻译".

**描述问题**

网页样式被破坏, 出现背景消失, 内容宽度限制消失等问题.

**问题截图**

![图片](https://user-images.githubusercontent.com/47659370/94806789-2704f400-0421-11eb-9246-8d5d3ced299f.png)

**Comment by RealXuChe** [comment]
似乎这是google自己的问题，因为google translate的网页翻译也会破坏样式。
https://translate.google.com/translate?sl=en&tl=zh-CN&u=https%3A%2F%2Fwww.guru3d.com%2Farticles_pages%2Fclocktuner_for_ryzen_ctr_guide_download%2C1.html
不过还是希望能修一下

**Comment by nickyc975** [comment]
这个要修复可能比较困难，我们会尝试一下的。

**Comment by Mark-Fenng** [comment]
谷歌网页翻译的问题我们应该是没有办法修复，因为代码不是开源的，而且是外部请求得来的
我们试试吧

**Comment by Mark-Fenng** [comment]
似乎现在没有这个问题了
