### ISSUE TITLE
提示google封锁IP问题

### ISSUE THREAD

**Issue by huang-jf** [EdgeTranslate/EdgeTranslate#13]
**描述问题**

翻译时，提示：
**由于您的请求过于频繁，Google已将您的IP暂时封锁，请等待半小时后重试！**

**出现问题的网址**

所有

**复现步骤**

翻译时出现

**使用环境**

chrome73
插件版本1.6.0

**其他信息**

**Comment by Mark-Fenng** [comment]
感谢反馈，不过这个问题还是因为请求过于频繁，或许不是自己翻译太频繁，而是同一个ip下的局域网内有人反复翻译，谷歌暂时把你的ip屏蔽了，一般半小时之内就会自动解封，之后就可以正常用了
以后只要不是一秒钟内翻译多次是没有关系的
