### ISSUE TITLE
希望内置的pdf查看器能够添加高亮功能

### ISSUE THREAD

**Issue by programmerZe** [EdgeTranslate/EdgeTranslate#132]
**功能描述**

_你想要什么样的功能 /改进？_
希望内置的pdf查看器能够有高亮功能。
**使用场景**

_你是在什么场景下需要用到这个功能 /改进？_
看pdf想要做笔记时有需要
**你的解决方案**

_你有没有想到什么解决方案？_

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_
edge自带的高亮功能：
![Snipaste_2020-10-26_17-06-10](https://user-images.githubusercontent.com/32977308/97153539-a03c0080-17ad-11eb-8975-91dc6350944d.png)
**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
这个暂时加不上，抱歉。
