### ISSUE TITLE
翻译源选择

### ISSUE THREAD

**Issue by ovaso** [EdgeTranslate/EdgeTranslate#133]
首次使用,所以把当前的问题反馈一下

对于翻译源,选择的全是腾讯,但是默认使用的还是谷歌翻译
其次,有道源不可用
示例网站https://www.dnf-universe.com

Microsoft Edge Chromium 86.0.622.63

_浏览器版本 
86.0.622.63

_插件版本
2.0.2

**Comment by Mark-Fenng** [comment]
`对于翻译源,选择的全是腾讯,但是默认使用的还是谷歌翻译`
  这个问题在翻译源列表上显示的是谷歌翻译，还是你认为他实际翻译结果是来自谷歌翻译

`有道源不可用`
这个问题是因为有道网页翻译不支持韩语，抱歉，这个我们无能为力

**Comment by ovaso** [comment]
意思是说,只是在标题栏上写的谷歌翻译,但是选择了是腾讯就是腾讯对吧?

韩语问题那我暂时就使用谷歌源吧

发件人: 踩坑小王子<mailto:notifications@github.com>
发送时间: 2020年11月9日 10:13
收件人: EdgeTranslate/EdgeTranslate<mailto:EdgeTranslate@noreply.github.com>
抄送: Ovaso<mailto:proamyr@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译源选择 (#133)


对于翻译源,选择的全是腾讯,但是默认使用的还是谷歌翻译
这个问题在翻译源列表上显示的是谷歌翻译，还是你认为他实际翻译结果是来自谷歌翻译

有道源不可用
这个问题是因为有道网页翻译不支持韩语，抱歉，这个我们无能为力

―

**Comment by Mark-Fenng** [comment]
不是的，标题栏上写的什么翻译源实际就是什么翻译源，如果不是这样的话，就是bug了，还是麻烦提供一下更多的信息，最好能有复现步骤

**Comment by ovaso** [comment]
这个是设置后并重启浏览器之后的设置截图(每次设置完需要重启浏览器才会生效),已经全部设置为腾讯翻译了
[cid:image001.png@01D6B68A.F14A9FB0]

这个是设置完之后使用的截图,直接是谷歌翻译
[cid:image006.png@01D6B68A.F14A9FB0]
发件人: 踩坑小王子<mailto:notifications@github.com>
发送时间: 2020年11月9日 10:51
收件人: EdgeTranslate/EdgeTranslate<mailto:EdgeTranslate@noreply.github.com>
抄送: Ovaso<mailto:proamyr@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译源选择 (#133)


不是的，标题栏上写的什么翻译源实际就是什么翻译源，如果不是这样的话，就是bug了，还是麻烦提供一下更多的信息，最好能有复现步骤

―

**Comment by nickyc975** [comment]
你是不是想说在设置页面全部设置成了腾讯翻译，但是在翻译框里显示的还是谷歌翻译？

**Comment by Mark-Fenng** [comment]
> 你是不是想说在设置页面全部设置成了腾讯翻译，但是在翻译框里显示的还是谷歌翻译？

我感觉你触及到问题的本质了😂

**Comment by ovaso** [comment]
是的😂,所以我问是不是只是外显的谷歌翻译,但是实际已经是腾讯翻译了

发件人: 踩坑小王子<mailto:notifications@github.com>
发送时间: 2020年11月9日 11:36
收件人: EdgeTranslate/EdgeTranslate<mailto:EdgeTranslate@noreply.github.com>
抄送: Ovaso<mailto:proamyr@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译源选择 (#133)


你是不是想说在设置页面全部设置成了腾讯翻译，但是在翻译框里显示的还是谷歌翻译？

我感觉你触及到问题的本质了😂

**Comment by Mark-Fenng** [comment]
是这样的，设置页面的语言设置选项 设置的混合翻译模式的翻译源
如果你想直接使用腾讯翻译，可以直接在翻译结果侧边栏里面选择
如果那里的翻译源选择框里没有腾讯翻译，可能是目前的一个bug（马上就会更新新版来修复）, 可以重新设置一下翻译的目标语言来解决

**Comment by nickyc975** [comment]
只有你在翻译侧边栏里选择了混合翻译的时候，设置页面里的翻译源设置才是有效的。

**Comment by ovaso** [comment]
Okok晓得了,这下搞清楚了

发件人: 踩坑小王子<mailto:notifications@github.com>
发送时间: 2020年11月9日 11:48
收件人: EdgeTranslate/EdgeTranslate<mailto:EdgeTranslate@noreply.github.com>
抄送: Ovaso<mailto:proamyr@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译源选择 (#133)


是这样的，设置页面的语言设置选项 设置的混合翻译模式的翻译源
如果你想直接使用腾讯翻译，可以直接在翻译结果侧边栏里面选择
如果那里的翻译源选择框里没有腾讯翻译，可能是目前的一个bug（马上就会更新新版来修复）, 可以重新设置一下翻译的目标语言来解决

―

**Comment by ovaso** [comment]
已解决,谢谢解答

发件人: Nicky Chen<mailto:notifications@github.com>
发送时间: 2020年11月9日 11:53
收件人: EdgeTranslate/EdgeTranslate<mailto:EdgeTranslate@noreply.github.com>
抄送: Ovaso<mailto:proamyr@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译源选择 (#133)


只有你在翻译侧边栏里选择了混合翻译的时候，设置页面里的翻译源设置才是有效的。

―
