### ISSUE TITLE
添加选项来指定要显示的内容

### ISSUE THREAD

**Issue by nbnbnb** [EdgeTranslate/EdgeTranslate#134]
**describe feature功能描述**

1，能否添加显示英文音标功能，目前显示的拼音

2，是否可以添加选项来指定要显示的内容

**Comment by Mark-Fenng** [comment]
现在是有音标功能的，翻译结果下方的是拼音，下面是显示的音标（谷歌的音标和常见的不太一样，百度翻译的音标是标准的）
![image](https://user-images.githubusercontent.com/27533910/98762559-e5e60380-2412-11eb-8b45-ca67f08b46bf.png)

关于`是否可以添加选项来指定要显示的内容`
这个之后会尽快加上的，已在计划中
