### ISSUE TITLE
双语对照

### ISSUE THREAD

**Issue by Gmengfan** [EdgeTranslate/EdgeTranslate#136]
**describe feature功能描述**

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

**your solution 你的解决方案**

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

**Comment by Gmengfan** [comment]
可不可以翻译之后有个双语对照？

**Comment by Mark-Fenng** [comment]
你说的双语对照是什么，现在不就已经有原文和翻译结果的对照了吗
![image](https://user-images.githubusercontent.com/27533910/98967057-f8615980-2546-11eb-8f33-4494fbd10421.png)

**Comment by Gmengfan** [comment]
Now I see it. I don't know why it didn't show up when I just installed it.

**Comment by Gmengfan** [comment]
现在我看到了，我也不懂为什么刚安装的时候为什么没有显示
