### ISSUE TITLE
单词发音问题

### ISSUE THREAD

**Issue by kylewen7** [EdgeTranslate/EdgeTranslate#137]
Hi，

原本的单词发音默认为第一次正常速度，第二次慢速。但是不知道从哪个版本升级以后就变成了第一次慢速，第二次才正常。所有网页均如此，也未找到相关设置。请问是否能调整回第一次发音为正常速度。
用的Google 翻译服务器。

另：请增加打赏窗口噢~

谢谢，

**Comment by Mark-Fenng** [comment]
感谢反馈，确实是这样，我也觉得第一次发音应该是正常语速，可能下个版本会改回来

**Comment by kylewen7** [comment]
哈哈哈谢谢哦~爱您~~已支持~~~你们在做件小儿伟大的事情所以请继续加油哦~~~~~

**Comment by Mark-Fenng** [comment]
谢谢支持！！！😁

**Comment by nickyc975** [comment]
感谢支持！
