### ISSUE TITLE
个人使用的感受和对于功能的建议

### ISSUE THREAD

**Issue by hwan289** [EdgeTranslate/EdgeTranslate#139]
感谢创造这个软件，这个软件是现在我能找到的最好网页一键翻译的选择！现在我最喜欢这个软件因为我可以用快捷键非常快的切换到未翻译过的网页，这是其他我所知的网页翻译插件都没有的功能，都没有返回原文的选项不管用快捷键或是右键。我不知道有没有软件可以实现这个除了这个软件。我个人希望能够在开启英文网站的时候，自动翻译（不需要点翻译网页）就像谷歌网页翻译插件那样子。我现在在用chrome浏览器，macos系统，其他系统功能上区别不太熟，然后有些我希望的功能可能我这个版本没有，希望有更多的选项能让我启用或禁用，让更多人有更加个人化的用这个软件。然后因为我现在没任何编程能力，不知道如何自己弄出我希望的功能，只能希望你们能在设置菜单中开启更多能选的选项了！

**describe feature功能描述**
1 希望有个选项能让我隐藏一碰到词就显示原文的功能当我浏览已翻译过后的网站；因为个人有时候想有鼠标指着词去更快的阅读。或者有个热键的选项能让我主动开启查看原文在读已经翻译的网站的时候。
2 希望在右键菜单中可以添加回到未翻译网页的选项。我个人更倾向于这个多于对照翻译，可能因为我觉得对照翻译有时候没翻译好整句话，然后看的难受对我来说。

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_
1 在设置中能够开启或关闭“一打开网页就自动翻译”像谷歌网页翻译插件那样子。
2 设置菜单中能够选择开启或禁用一些功能，尤其是马上的显示原文当一碰到个词对我来说，（其实我个人几乎不使用其他功能除了网页翻译，因为macos右键有自带词典，对我非常便捷，然后触控板也有相关快捷键。）
3 希望右键菜单能自定义更多的选项，例如右键然后 选择翻译网页（不会跳到另一个网页的那种）。对我来说可以弥补macos自带词典没法右键翻译句子。（我个人倾向用快捷键然后右键，像现在我一般用谷歌翻译，然后每次想看下原文挺累的，要移动挺远去手动的让谷歌插件显示原文。）然后翻译后的内容可以有能固定在屏幕上的选项。（这个功能很多能划词的软件都能实现，比如mac的有道也行，然后谷歌插件也很多，不过能右键这样做的我也不确定哪个插件有，有道是没有，右键只能跳到有道软件页面，不是有道翻译界面，挺麻烦的。如果这个软件也带这个功能，就省得开着有道词典然后只能划词翻译通过点击一般右下角出现的图标了，因为觉得这样子还是要动挺远的，有时候还容易不小心这个小图标因为我鼠标不小心离开范围就消失了。。）

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

**your solution 你的解决方案**

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_
希望能在设置界面添加更多的选择有关于右键菜单和网页翻译。我个人一般快捷键和右键菜单用得最多，用着触控板有时候觉得移动太远不方便。这个软件快捷键设置对我非常足够。我尽力检查了使用指南但是没发现以上的我希望的功能。
我最希望有的功能是能别自动跳出原文当我想用鼠标定位文字去加速阅读然后碰到那些单词的时候。快捷键加上碰到单词 或者能够在设置页面上禁止跳出原文当一碰到词。
然后很希望可以节省每当打开一个新页面要输入快捷键翻译整个网站的操作，希望设置页面能让我选择一打开网页就自动翻译。
然后两个个人觉得这个软件可以有的功能，右键菜单能有“回到原文”和“翻译选取文字”的选项。虽然我能用快捷键，不过有更多的方法去用一个功能对我来说更加方便些。有时候可能懒得碰键盘了，然后也能在右键菜单上实现相同功能。我现在右键菜单只有翻译整个网站这个选项，希望在未来能够有更多的关于右键菜单的选项在设置页面。
我对编程没任何概念，感谢有这个软件能让我用对我来说非常方便的方式-快捷键去回到未翻译过的网站。这是我最喜欢的功能，然后其他软件都没这么方便当我想看一眼原文然后再回到已翻译网页！希望谅解如果有些我希望的功能我没注意。希望能推荐其他插件能实现我所希望的功能，现在即使搜了网页翻译插件很久，也只找到这个软件，也不知道谷歌是否自带快捷键去回到原文或者有其他更方便的办法去回到未翻译网页，感觉这是我最希望有的功能对于整个网页翻译供。

**Comment by Mark-Fenng** [comment]
1. 右键的选项每个扩展只能占用一项，额外的菜单选项会被折叠，这点我们将会维持现状。
2. 一碰到词就显示原文的功能是谷歌网页翻译提供的，我们只是将其集成进了扩展里面，没有办法修改它的功能。不过chrome自带的网页翻译没有一碰到词显示原文的功能，正好满足你的要求，你可以把两者结合起来使用。
3. 右键选择翻译网页的功能已经支持，见截图：
![image](https://user-images.githubusercontent.com/27533910/100535000-ffc77900-324f-11eb-9a89-4f94f7f5dbb7.png)
右键菜单翻译选取文字的功能也已经支持，见截图：
![image](https://user-images.githubusercontent.com/27533910/100535162-4ec1de00-3251-11eb-91d1-1c86e087c091.png)
4. `翻译后的内容可以有能固定在屏幕上的选项`，这个功能也有，见截图：
![image](https://user-images.githubusercontent.com/27533910/100535266-47e79b00-3252-11eb-9f54-bdf0a0e9a6b9.png)
5. 打开网页自动翻译的功能可以考虑加上

我们用户众多，恕不能提供非常个性化的功能要求，如果想要提供个人定制的版本可以另外通过邮件联系
