### ISSUE TITLE
I use with my Edge browser, but very recently it started translating my German pages into Chinese. I have read the instructions and tried to fix it, but nothing seems to work. I loved this Edge Translate app and hope there's a fix for this!  Thanks, Gerald Maffeo

### ISSUE THREAD

**Issue by GeraldMaffeo** [EdgeTranslate/EdgeTranslate#140]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
If you are using page translating, you need to set the default page translator to Google Page Translate so that you can choose the target language.

**Comment by nickyc975** [comment]
Sorry about that, it turns out that it's my mistake. I'll fix it right now.

**Comment by GeraldMaffeo** [comment]
Great, thanks for your very fast response to my issue! I did re-check all the settings (e.g. default to Google Translate) and nothing worked.

**Comment by nickyc975** [comment]
The problem has been fixed, but the fix couldn't reach to you until our next release.  You can follow the following instructions to work around the problem:

1. Translate a page as usual;

2. After translating, you'll see `已翻译为以下语言：中文（简体）显示原文` in the Google Page Translate tool bar;

3. Click `中文（简体）` and you'll see the language list, in Chinese however;

4. Choose `德语` which means German and you will get German translation.

I am sorry for the mistake, hope this could help.

**Comment by GeraldMaffeo** [comment]
Thanks, Nicky. The workaround does indeed work for translating into German, but I want to translate into English. Can you send me that for now? Also, roughly when do you think the next release will be?

By the way, I was also a developer (since retired), so I appreciate the amount of effort you need to put into implementing and prepping a new release. My last remaining app is called 10Calc and is in the Microsoft Store, if you want to check it out.

**Comment by nickyc975** [comment]
The Chinese word for English is `英语`.

**Comment by nickyc975** [comment]
Next release might be published in several weeks, depands on how busy we are. We will make it as soon as possible.

**Comment by GeraldMaffeo** [comment]
OK, thanks again.

**Comment by nickyc975** [comment]
You are welcome!
