### ISSUE TITLE
划词取译时，点击弹出翻译框的右上角齿轮设置时，会自动弹出两个标签页

### ISSUE THREAD

**Issue by linhcpg** [EdgeTranslate/EdgeTranslate#141]
这两个标签页，一个是设置页，一个是提示页，默认激活的是提示页,
提示页显示如下内容：
/*********************************************************
为什么会出现这个页面？

   1 你也许忘记在安装或者更新扩展后刷新已经打开的页面了。
   2 你正在一个无法注入我们扩展脚本的页面上使用侧边翻译。
        例如这些网址：
        chrome://extensions/
        https://chrome.google.com/webstore/
        一个空白页面
   3 在火狐浏览器上，我们的扩展不能在文件页面上使用

链接

    侧边翻译设置
    说明文档
    报告一个bug
**************************************************/

是每次操作都会自动弹出这俩标签页，而且默认激活的还是提示页不是设置页。

PS:我用的是火狐浏览器,装的是扩展最新版本

**Comment by linhcpg** [comment]
发现设置里勾选翻译后取消文本选择就不会弹那个提示标签页，算是解决了。。

**Comment by nickyc975** [comment]
你是在什么页面上翻译的？有些页面上无法翻译所以会自动打开提示页展示翻译结果。

**Comment by Mark-Fenng** [comment]
@linhcpg 你是不是开启了选中自动文字自动翻译的选项

**Comment by linhcpg** [comment]
@Mark-Fenng 是的，开启了这个

**Comment by Mark-Fenng** [comment]
不开启这个选项会出现这个问题吗

**Comment by linhcpg** [comment]
> 
> 
> 不开启这个选项会出现这个问题吗

@Mark-Fenng 是的，不开启就正常，如果同时勾选“划词后立即翻译”和“翻译后取消文本选择”这两项，也是正常的

**Comment by Mark-Fenng** [comment]
好的，已经定位到问题原因了，感谢反馈，下个版本会修复

**Comment by firerflystar** [comment]
今天更新又出现这个问题了 , Chrome

**Comment by Mark-Fenng** [comment]
@firerflystar 请问这次应该怎么复现呢

**Comment by firerflystar** [comment]
> @firerflystar 请问这次应该怎么复现呢

你好 刚提交了
