### ISSUE TITLE
不兼容简悦的阅读模式

### ISSUE THREAD

**Issue by Mooncan** [EdgeTranslate/EdgeTranslate#143]
**describe the bug描述问题**
在打开简悦的阅读模式后，EdgeTranslate的翻译框会被简悦的元素覆盖，弹出模式和贴靠模式相同问题。
**fix修复**
具体问题因为简悦的元素层级设置了一个特别大的数字，如图:
![image.png](https://i.loli.net/2020/12/10/NQYSvVi5jUo2WBm.png)
所以可以把EdgeTranslate的z-index设为更大……
（不知道有没有更好的办法）

**Comment by Mark-Fenng** [comment]
啊 哎 这

**Comment by Mooncan** [comment]
抱歉贴错图片了，不过好像区别不大哈哈
![image.png](https://i.loli.net/2020/12/10/NQYSvVi5jUo2WBm.png)

**Comment by Mark-Fenng** [comment]
我刚刚才更新了新版，要是早点提issue还可以顺带改上😂
