### ISSUE TITLE
Mac上使用右鍵選單的「查詢」功能時，選取會位移

### ISSUE THREAD

**Issue by greenalienpay** [EdgeTranslate/EdgeTranslate#148]
<img width="599" alt="截圖 2021-01-06 上午9 43 02" src="https://user-images.githubusercontent.com/9688127/103719269-97647800-5003-11eb-827e-062484b155b5.png">
在畫面選取文字後，按下右鍵，選擇Mac本身內建的「查詢」功能時，選取內容會往前移動幾個字元，導致無法查詢。
關閉插件後，此問題就會消失。

macOS Big Sur 11.1
Microsoft Edge 87.0.664.66

**Comment by Mark-Fenng** [comment]
感谢反馈，确实有这个问题，我尝试修复一下
