### ISSUE TITLE
布局及字体大小问题

### ISSUE THREAD

**Issue by Vove7** [EdgeTranslate/EdgeTranslate#15]
**描述问题**

不知道字体为什么这么大，缩进有些大，布局有些显示不完，滚动条略粗，希望改进
插件很棒，支持
![image](https://user-images.githubusercontent.com/25018573/55822301-e7ae5d80-5b31-11e9-9451-3a5dda794833.png)

**出现问题的网址**

\*

**问题截图**

![](https://user-images.githubusercontent.com/25018573/55822451-34923400-5b32-11e9-98e5-f77db659e230.png)

**使用环境**

Chrome 
Microsoft Edge(Chroimum版)

Windows 10

插件版本1.6.0

**其他信息**

网页布局缩放100%
分辨率1920x1080
系统显示缩放150%

**Comment by nickyc975** [comment]
感谢反馈！布局这个问题我们会抽时间优化的。
