### ISSUE TITLE
我记得之前可以自定义出现的查词的词典的内容和顺序? 比如我不想看中文 只想看单词的英文解释这种功能? 

### ISSUE THREAD

**Issue by gottaegbert** [EdgeTranslate/EdgeTranslate#150]
**describe feature功能描述**

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

**your solution 你的解决方案**
比如我不想看中文 只想看单词的英文解释这种功能? 

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

**Comment by Mark-Fenng** [comment]
在2.0之后更改了项目结构，这个功能还没有来得及实现，我们会尽快加上
