### ISSUE TITLE
希望能增加中英互译

### ISSUE THREAD

**Issue by JaxVanYang** [EdgeTranslate/EdgeTranslate#154]
**describe feature功能描述**

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

可以自动识别文本语言，如果是文本是中文，翻译成英文

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

这对程序员可能是刚需，也可以用于学习外语  

比如在写这个 issue 的时候，如果侧边翻译有这种功能，我就可以很方便地把我写的建议翻成英文，写成 issue 模板的这种格式（一半英文，一半中文）

**your solution 你的解决方案**

_Do you have any solution 你有没有想到什么解决方案？_

在翻译之前先识别文本语言，如果与默认目标语言（中文）相同就翻译成其他语言（如英文）

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

**Comment by Mark-Fenng** [comment]
如果我对需求理解正确的话，这个功能已经有了，看截图处的按钮。需要注意的是，如果源语言是自动检测，则按钮不能开启。
![image](https://user-images.githubusercontent.com/27533910/106106567-b082c380-6180-11eb-82dd-b6c4e2a6b775.png)

**Comment by JaxVanYang** [comment]
#

> 如果我对需求理解正确的话，这个功能已经有了，看截图处的按钮。需要注意的是，如果源语言是自动检测，则按钮不能开启。
> ![image](https://user-images.githubusercontent.com/27533910/106106567-b082c380-6180-11eb-82dd-b6c4e2a6b775.png)

谢谢，是我疏忽了，那我顺便建议一下吧，希望能够考虑给自动检测加入互译功能

**Comment by Mark-Fenng** [comment]
@JaxVanYang 自己检测没有办法做互译功能，源语言和目标语言有一个是不确定的，没有办法实现。
我们的用户不只有英语和简体中文的互译需求
