### ISSUE TITLE
[功能建议] 能不能加一个域名黑白名单的功能

### ISSUE THREAD

**Issue by Alafun** [EdgeTranslate/EdgeTranslate#157]
**describe feature功能描述**

域名黑白名单

**scene used使用场景**

有时我打开一些网页划词单纯是为了显示，highlight展示一下或者有的时候是 赶论文复制粘贴这个时候要是可以把域名加入黑名单就好了，减少bother，避免打扰

**your solution 你的解决方案**

域名黑白名单

**more information 其他信息**

如果可以，设置一个 询问` 是否将此域名加入黑名单 ` 在选 `是` 之后在弹出一个框，`将这个域名加入黑名单多长时间` 有类似 `day`, `week`,`three weeks` 的选项，这样可以更准确的在项目期或者实习期之后自动恢复，但是这样貌似涉及到了一个cache的问题，还是砍了吧

**Comment by Mark-Fenng** [comment]
域名黑名单功能已经有了哦，在右上角的侧边翻译图标处右键，就能看到把域名和url加入黑名单的选项了
