### ISSUE TITLE
能否考虑为内置的Pdf阅读功能提供“黑暗模式”或类似护眼功能？

### ISSUE THREAD

**Issue by baozidai** [EdgeTranslate/EdgeTranslate#158]
**describe feature功能描述**

_提供暗黑模式或其他可选配色的PDF阅读器_

**scene used使用场景**

_阅读本地pdf文件时候进行划词翻译_

**your solution 你的解决方案**

_https://github.com/VictorYu379/Invertor_
_这个项目提供的功能或许可以使用_

**more information 其他信息**

_我建议这可以作为一个优先级较低的需求存在开发任务中_

**Comment by Mark-Fenng** [comment]
非常好的建议和解决方案，我们会尽快加上功能

**Comment by nickyc975** [comment]
功能已实现，下个版本更新，欢迎使用后给我们提供反馈！
