### ISSUE TITLE
the same shortcut to open the app and/or translate the selected text and/or close the result frame

### ISSUE THREAD

**Issue by WiliTest** [EdgeTranslate/EdgeTranslate#159]
The options in `edge://extensions/shortcuts` are great, but they don't allow the same shortcuts.

Thanks for sharing your work!

**Comment by nickyc975** [comment]
One shortcut for multiple functions is ambiguous. The browser could not know which function you want to trigger when you input the shortcut. Therefore, it's impossible to set the same shortcut for multiple functions.

**Comment by WiliTest** [comment]
Thanks for your answer. 
Sorry I wasn't clear, I meant using a shortcut to Activate the extension and the same one to close the result frame (= "if the frame is closed, open it"). 

Optional: It would be great to also use it to translate the selected text: (= "if the frame is closed, and a text is selected, open it to translate teh selection")

**Comment by nickyc975** [comment]
That's still ambiguous. Someone might be happy to keep the result frame open. If we close the frame when he or she was intended to activate the popup, he or she would be angry.

You might think that we can make it optional. But from our perspective, it's not worth adding some complex logic to the extension just for remembering one or two less shortcuts.
