### ISSUE TITLE
窗口大小bug，窗口大小经常会无法控制，无法拉大并且会随鼠标移动缩小，最终越来越小

### ISSUE THREAD

**Issue by DopamineLcy** [EdgeTranslate/EdgeTranslate#163]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
请详细描述一下触发这个bug的条件，例如在什么页面上，进行什么操作会触发这个bug。

**Comment by DopamineLcy** [comment]
在阅读pdf的页面上，使用edge浏览器，进行调整窗口大小时会触发bug。详细的请看视频演示。
[IEEE Xplore Full-Text PDF_ - 个人 - Microsoft​ Edge 2021-04-02 14-34-24.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/6248067/IEEE.Xplore.Full-Text.PDF_.-.-.Microsoft.Edge.2021-04-02.14-34-24.zip)

**Comment by Mark-Fenng** [comment]
感谢反馈，问题已经确认，会尽快修复
