### ISSUE TITLE
发现谷歌自带的pdf模式会和这个插件的pdf冲突，我返回原来的谷歌的阅读pdf后，回不到这个插件的pdf模式。还有开启划线翻译会导致我复制不了谷歌浏览器的文字，会很烦

### ISSUE THREAD

**Issue by ld1289551942** [EdgeTranslate/EdgeTranslate#164]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
1. 刷新一下页面应该就能重新打开自带的pdf阅读器了。请确保在插件的管理页面打开了访问文件url的权限，并且在插件设置页面打开了使用内置pdf阅读器的开关。
2. _开启划线翻译会导致我复制不了谷歌浏览器的文字_ 能否提供一下出现问题的网址和复现的步骤，最好能上传个视频。
