### ISSUE TITLE
其它翻译接口支持

### ISSUE THREAD

**Issue by beyound87** [EdgeTranslate/EdgeTranslate#166]
发现侧边栏翻译怎么换都只支持google，这样在google网络不畅的时候特别影响体验，求大佬完善可以支持其他翻译接口

**Comment by Mark-Fenng** [comment]
正常还有好多个接口，比如baidu，bing...
能否提供一下出问题的截图或者复现的步骤

**Comment by beyound87** [comment]
![image](https://user-images.githubusercontent.com/3038772/115018339-4ad5e600-9eea-11eb-8bb6-e384e7c64c3b.png)
如上图，是翻译截图
但是我设置的主翻译源如下图，设置的百度：
![image](https://user-images.githubusercontent.com/3038772/115018392-5f19e300-9eea-11eb-877a-e7123965c329.png)

**Comment by Mark-Fenng** [comment]
让我来解释一下翻译源设置，图一的翻译框左上角显示的是谷歌翻译，点击一下可以选择多种翻译源，其中有一种叫混合翻译，图二的设置项就是用来设置混合翻译源的。如果你不想用混合翻译，就直接在图一的结果栏选择翻译源。

**Comment by beyound87** [comment]
喔喔，不好意思，找到了，很难发现原来图一那儿可以点击下拉，谢谢

**Comment by Mark-Fenng** [comment]
为了颜色的统一，下拉框确实不明显
