### ISSUE TITLE
Read Problem with Google Translate

### ISSUE THREAD

**Issue by nguyenhieubis** [EdgeTranslate/EdgeTranslate#169]
Hello guys,

Currently I'm having "Read original text" & "Read translated text" problem like a below image with option "Google Translate". It show "Pronouncing failed, please check your network or choose another translator." My network is OK, if I choose "Bing Translate" everything is OK. But I like Google Translate.
Hope your help.
![EdgeTranslate_Error](https://user-images.githubusercontent.com/62685761/118748303-cf1ede80-b885-11eb-8bc1-5250b8b181e6.png)

**Comment by Mark-Fenng** [comment]
Sorry for your bad experience. Looks like something has changed of google translate api and we will update it soon.

**Comment by nguyenhieubis** [comment]
Thank you for your support.
