### ISSUE TITLE
最近一直提示网络连接问题，麻烦您看下是什么问题

### ISSUE THREAD

**Issue by qqlovekerry** [EdgeTranslate/EdgeTranslate#17]
**描述问题**
最近一直显示网络连接错误，显示不出来翻译的内容。

**问题截图**
![Screenshot from 2019-04-25 17-24-43](https://user-images.githubusercontent.com/16799190/56728184-d34e9f80-6784-11e9-9ec1-147c951c661f.png)

**使用环境**

_Ubuntu 18.04_

_firefox_

_66.0.3_

_1.6.1_

**Comment by nickyc975** [comment]
你试试能不能直接访问这个网址：[translate.google.cn](https://translate.google.cn)

**Comment by qqlovekerry** [comment]
@nickyc975 访问不了呢，您不用代理可以直接访问吗？

**Comment by nickyc975** [comment]
我这里不用代理也可以正常访问啊，这个网址应该没有被封锁才对。

**Comment by nickyc975** [comment]
你可能需要检查一下你的网络连接。

**Comment by qqlovekerry** [comment]
很奇怪，我昨晚回家就可以连接，但是单位不行，那可能是我单位的网络访问<translate.google.cn>有问题。
如果可以增加一个解析的翻译网址比如有道之类的，可能一个不能用的时候可以更换一个。
或者增加一个代理的功能，不过可能有点麻烦。
谢谢您的解答！

**Comment by nickyc975** [comment]
我们有时间了会考虑增加一些国内的翻译源的，谢谢使用！
