### ISSUE TITLE
朗讀失敗，請檢查網絡連接或更換翻譯源。

### ISSUE THREAD

**Issue by MakotoChang** [EdgeTranslate/EdgeTranslate#170]
我在chrome上面使用側邊翻譯有一段時間了，今天在使用的時候發現發音的功能不能使用，顯示出來的訊息為"朗讀失敗，請檢查網絡連接或更換翻譯源。"，請問該如何排除這問題？

**Comment by nickyc975** [comment]
是否是使用谷歌翻译的时候遇到的问题？
如果是的话，那这是一个已知的问题，即将发布的新版本会修复，你可以先用其他翻译源替代一下。

**Comment by MakotoChang** [comment]
Hi, Nicky你好，
我不管選哪一個翻譯源或著混合翻譯源都有這樣的問題。

以上回報
Thanks,
Makoto

Nicky Chen ***@***.***>於 2021年5月21日 週五，上午10:50寫道：

**Comment by nickyc975** [comment]
那这个应该是你的网络的问题，我们没办法复现。你看一下在谷歌翻译的官网是否可以发音呢？

**Comment by MakotoChang** [comment]
Hi, Nicky,
我的google翻譯是可以發音的，網路也沒有問題，但錯誤訊息的確請我檢查網路，我不知道這中間發生了什麼改變。

Thanks,
Makoto

Nicky Chen ***@***.***>於 2021年5月21日 週五，上午11:15寫道：

**Comment by Mark-Fenng** [comment]
這種不好複現的網絡問題，我們也沒有什麼好辦法去解决😔

**Comment by MakotoChang** [comment]
Hi, Nicky,
這個問題突然又恢復正常了，我看了一下版本號為2.2.0
特此回報
感謝你們開發這個工具

Thanks,
Makoto

Lucky Feng ***@***.***> 於 2021年5月21日 週五 下午5:02寫道：
