### ISSUE TITLE
朗读原始文本失败

### ISSUE THREAD

**Issue by eriri88888** [EdgeTranslate/EdgeTranslate#172]
**describe the bug描述问题**
侧边翻译
朗读失败，请检查网络连接或更换翻译源

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
侧边翻译
朗读失败，请检查网络连接或更换翻译源
**testable address 出现问题的网址**
全部

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_
全部

**steps to reproduce复现步骤**
划词-点击朗读原始文本
_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**
windows10的EDGE版本 90.0.818.62
_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_
windows10的EDGE版本 90.0.818.62
_browser name 浏览器类型 [e.g. chrome, firefox]_
windows10的EDGE版本 90.0.818.62
_browser version 浏览器版本 [e.g. 22]_
windows10的EDGE版本 90.0.818.62
_extension version 插件版本 [e.g. 2.0.0]_
侧边翻译
2.1.3
**other information 其他信息**
已尝试更换翻译源，还是朗读失败
_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
所有翻译源都无法朗读是吗？
