### ISSUE TITLE
与Dark Reader夜间模式不兼容

### ISSUE THREAD

**Issue by aug7** [EdgeTranslate/EdgeTranslate#18]
**描述问题**

启动夜间模式阅读文章，选中单词翻译，出现的翻页界面背景为白色，翻译界面的内容为淡黄色，且无法看清除。

**出现问题的网址**

所有

**复现步骤**

启动夜间模式阅读文章，选中单词翻译，出现的翻页界面背景为白色，翻译界面的内容为淡黄色，且无法看清除。

**问题截图**

**使用环境**

_浏览器类型
Chromium 
_浏览器版本 [e.g. 22]_
Chromium 72.0.3626.121
_插件版本 [e.g. 1.2.0]_
1.6.1
**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
收到，我们后续会抽时间优化的。

**Comment by RemRemRemRe** [comment]
请问可以把音标也显示一下吗

**Comment by nickyc975** [comment]
抱歉，最近忙考试，所以暂时没时间做。

**Comment by nickyc975** [comment]
等考试完了我们会一一处理的。
