### ISSUE TITLE
語音問題

### ISSUE THREAD

**Issue by D0542562** [EdgeTranslate/EdgeTranslate#184]
**describe the bug描述问题**
目前時常遇到
''側邊翻譯
朗讀失敗，請檢查網絡連接或更換翻譯源。''
_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
無法知道字詞的發音
**testable address 出现问题的网址**
不一定 目前是pdf最常出現
_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**
按下側邊翻譯的icon
按下朗讀原始文本的小喇叭
彈出警告框
_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_
![image](https://user-images.githubusercontent.com/32399757/119686976-67662600-be79-11eb-81fc-ceefc6696fb6.png)

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_
windows
_browser name 浏览器类型 [e.g. chrome, firefox]_
edge
_browser version 浏览器版本 [e.g. 22]_
版本 90.0.818.66 (官方組建) (64 位元)
_extension version 插件版本 [e.g. 2.0.0]_
2.2.0
**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
@D0542562 麻煩再確認一下側邊翻譯的版本號是2.1.3还是2.2.0，因為2.2.0在Edge瀏覽器上還沒有發布
