### ISSUE TITLE
seem the new version can't translate the phrase

### ISSUE THREAD

**Issue by kev26** [EdgeTranslate/EdgeTranslate#185]
I use Google Translate to translate Vietnamese from English  but it only works with words, but doesn't with the phrase!

**Comment by Mark-Fenng** [comment]
Could you please provide the phrase that the extension can't translate?

**Comment by kev26** [comment]
Try translate your comment and it appears like this
![image](https://user-images.githubusercontent.com/25315610/119762478-ff92f800-bed7-11eb-9588-e56d88b7fbf3.png)

**Comment by Mark-Fenng** [comment]
Thank you, this looks like a bug. And I need some information to reproduce this problem. 
What's your browser name and browser version? And I'd appreciate that if you could provide logs in your console.

**Comment by kev26** [comment]
Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by Mark-Fenng** [comment]
Are there any errors in your console of chrome's dev tools?

**Comment by kev26** [comment]
"Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist." Is this an error?

**Comment by Mark-Fenng** [comment]
Yes, a sreenshot of your console would be helpful!

**Comment by kev26** [comment]
![image](https://user-images.githubusercontent.com/25315610/119765535-a928b800-bedd-11eb-82fc-057a6dff20ba.png)

**Comment by Mark-Fenng** [comment]
Great, and could you please translate a phrase first and then capture your console

**Comment by nickyc975** [comment]
Problem comfirmed. We will fix this in next version. Thanks for your feedback!

**Comment by kev26** [comment]
By the way, can you add a feature to save and check vocabulary? I think it is very useful!

**Comment by nickyc975** [comment]
> By the way, can you add a feature to save and check vocabulary? I think it is very useful!

We are working on it!
