### ISSUE TITLE
not working after update to 2.2.0(duplicate with issue#185 & need a fallback for the google translate api)

### ISSUE THREAD

**Issue by vardipoorm** [EdgeTranslate/EdgeTranslate#186]
**describe the bug描述问题**

- some times not showing anything 
- some times error 429

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
i reinstall it but not different
i still have V2.1.3 on edge and have no problem and work like yoghurt ;)
**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/84905074/119802012-6c67bb80-bef3-11eb-98d9-11721597c87c.png)
![image](https://user-images.githubusercontent.com/84905074/119802185-96b97900-bef3-11eb-916c-3070af2adcdf.png)
_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_
chrome-firefox
_browser version 浏览器版本 [e.g. 22]_
latest
_extension version 插件版本 [e.g. 2.0.0]_
2.2.0
**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
Sorry for the bad experience!
We will fix this issue soon.

**Comment by vardipoorm** [comment]
Thanks <3 Sent from Mail for Windows 10 From: Lucky FengSent: Thursday, May 27, 2021 3:02 PMTo: EdgeTranslate/EdgeTranslateCc: vardipoorm; AuthorSubject: Re: [EdgeTranslate/EdgeTranslate] not working after update to 2.2.0 (#186) Sorry for the bad experience!We will fix this issue soon.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
