### ISSUE TITLE
请求参数错误，请更换其他翻译源或过段时间再翻译，如还是无法使用，请联系开发者

### ISSUE THREAD

**Issue by digger-yu** [EdgeTranslate/EdgeTranslate#187]
请求参数错误，请更换其他翻译源或过段时间再翻译，如还是无法使用，请联系开发者。

错误代码: 400

错误信息: "Request failed."

错误操作: 

![图片](https://user-images.githubusercontent.com/55081697/119820715-5de5c800-bf24-11eb-9d22-09a35d381ecd.png)

**Comment by nickyc975** [comment]
这个bug已知，将在下个版本修复，谢谢你的反馈！

**Comment by niaiwomattt** [comment]
666 修复很快，昨天我刚发现！今天就修复了！
