### ISSUE TITLE
请为Edge商店中的EdgeTranslate更新

### ISSUE THREAD

**Issue by PurBlu** [EdgeTranslate/EdgeTranslate#189]
https://microsoftedge.microsoft.com/addons/detail/%E4%BE%A7%E8%BE%B9%E7%BF%BB%E8%AF%91/bfdogplmndidlpjfhoijckpakkdjkkil?hl=zh-CN
版本仍旧是2.1.3 烦请为其更新 感谢！

**Comment by Mark-Fenng** [comment]
一周前就已经上传更新了，只是不知为何，这次的审核异常漫长，到现在也没有通过😂

**Comment by PurBlu** [comment]
> 一周前就已经上传更新了，只是不知为何，这次的审核异常漫长，到现在也没有通过😂

感谢回复，EdgeTranslate是真的很好用！
我工作原因Chrome和Edge会混用，Chrome这边自动更新后两边体验差别每次都有些不适应。
看来只有嗯等巨硬审核啦哈哈😉

**Comment by Mark-Fenng** [comment]
@PurBlu Edge上v2.2.1的也上传了，v2.2.0还是没有更新， 巨硬不知道在搞什么事情
