### ISSUE TITLE
按键功能设置

### ISSUE THREAD

**Issue by SnDream** [EdgeTranslate/EdgeTranslate#19]
**功能描述**

希望能提供插件按键功能的设置，如开关划词、直接启动谷歌翻译等功能，而不是单纯的翻译窗口（或者，翻译窗口中添加这些快速功能的开关）

**使用场景**

翻译窗口使用偏少，而网页翻译菜单又收缩起来，不方便选。
另外，我在手机yandex上使用时，浏览器没有右键菜单，无法调用网页翻译功能。

**你的解决方案**

同上

**替代方案**

无

**其他信息**

无

**Comment by nickyc975** [comment]
"按键功能"是指快捷键吗？

**Comment by SnDream** [comment]
指的就是扩展栏的那个功能图标。
我注意到ff对图标右键可以选择有道翻译或者谷歌翻译，但是毕竟是右键点击，而且chrome上还没有，我想问的是，能否在设置中提供修改左键点击图标调用的功能，而不是弹出那个简单的单词翻译窗口。

**Comment by nickyc975** [comment]
你的意思是在左键点击右上角图标弹出的悬浮框里添加网页翻译的功能对吗？

**Comment by nickyc975** [comment]
这个功能确实可以考虑，这样的话就可以在手机上使用网页翻译功能了对吧？

**Comment by SnDream** [comment]
悬浮框里加或者直接能更换图标功能都行吧，个人感觉用悬浮窗输入单词翻译还是使用频率偏低的功能，大部分情况下，除了划词，还是直接调用网页翻译比较多，能把图标用上会更好些。
当然，这些只是我个人的体验，也许不太符合一般人的用法。

**Comment by nickyc975** [comment]
这个插件主要是面向桌面端的，并没有适配手机。而在桌面端，直接在页面上任意位置右键调用网页翻译功能显然更方便。手机端我们暂时不打算做适配，不过你的这个建议我们倒是可以采纳，谢谢反馈！

**Comment by miss-fang** [comment]
> 
> 
> 这个插件主要是面向桌面端的，并没有适配手机。而在桌面端，直接在页面上任意位置右键调用网页翻译功能显然更方便。手机端我们暂时不打算做适配，不过你的这个建议我们倒是可以采纳，谢谢反馈！

能不能加个**开关**功能，有时候我希望它是关闭的，这样我选中文字不会和其他软件等功能冲突

**Comment by nickyc975** [comment]
> > 这个插件主要是面向桌面端的，并没有适配手机。而在桌面端，直接在页面上任意位置右键调用网页翻译功能显然更方便。手机端我们暂时不打算做适配，不过你的这个建议我们倒是可以采纳，谢谢反馈！
> 
> 能不能加个**开关**功能，有时候我希望它是关闭的，这样我选中文字不会和其他软件等功能冲突

你可以使用插件的网页黑名单功能，把网页暂时加入到黑名单中来禁用翻译功能。
