### ISSUE TITLE
插件简介出现了错别字

### ISSUE THREAD

**Issue by MidCheck** [EdgeTranslate/EdgeTranslate#194]
此处的“我么”应该为“我们”

网址为：
https://addons.mozilla.org/zh-CN/firefox/addon/edge_translate/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

![插件错别字](https://user-images.githubusercontent.com/45385025/120575515-cae0ec80-c453-11eb-9fed-a22e0da6e772.png)

**Comment by Mark-Fenng** [comment]
感谢指正，我这就去修改

**Comment by Mark-Fenng** [comment]
已经修改，清除一下浏览器缓存就可以看到变化了
