### ISSUE TITLE
在清空浏览器缓存后会出现 Network error 的问题

### ISSUE THREAD

**Issue by MaoKwen** [EdgeTranslate/EdgeTranslate#20]
**描述问题**

选中某些文本，右键翻译，侧面板出现，显示

> Network error! Please check your network connection.
> 
> Error code: 403

重新安装插件没能解决

**复现步骤**

在 Chrome 下（Firefox下没能复现），尝试翻译以下文本：

- Let‘
- &
- 中文english
- ？

**使用环境**

Chrome 75.0.3770.100
Plugin Version 1.6.1

**Comment by nickyc975** [comment]
这应该是你的网络有问题，跟翻译的内容无关。出现报错的时候你试试直接访问[https://translate.google.cn](translate.google.cn)了不能正常访问？

**Comment by MaoKwen** [comment]
我找到复现方法了，我发现这问题常常出现在清理浏览器缓存之后。

症状为只能翻译英文，翻译其他文本都会报错403。

解决方法是手动访问 translate.google.cn 。

**Comment by nickyc975** [comment]
确认了，是插件的问题，我们将尽快解决，感谢反馈！

**Comment by nickyc975** [comment]
@MaoKwen 你安装这个包看看还有没有问题，下载之后把后缀改为crx，安装方法在[这里](https://github.com/EdgeTranslate/EdgeTranslate/blob/master/docs/README_CN.md#chrome)：
[chrome.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/3391393/chrome.zip)

**Comment by MaoKwen** [comment]
@nickyc975 在这个包中问题没有再次出现

**Comment by nickyc975** [comment]
@MaoKwen 好的，感谢反馈！
