### ISSUE TITLE
在点击翻译键的时候翻译框会在左侧闪一下

### ISSUE THREAD

**Issue by Legend-Master** [EdgeTranslate/EdgeTranslate#201]
在点击翻译键的时候翻译框会在左侧闪一下，[视频片段](https://streamable.com/xll3gt)
（顺带有个小建议，把翻译键从按下触发改成点击触发会不会更好一点？

浏览器：Chrome,  91.0.4472.77
插件：2.2.1

**Comment by Mark-Fenng** [comment]
感谢反馈，闪一下的问题确实有时会出现，需要再排查一下原因。改成点击后触发有什么优势吗

**Comment by Legend-Master** [comment]
个人倾向啦，觉得体验上舒服一点，鼠标点上去还没抬起来按键就消失了感觉怪怪的2333

**Comment by Mark-Fenng** [comment]
好的，我会尽快改进一下

**Comment by Legend-Master** [comment]
感谢超快的回复，加油 XD
