### ISSUE TITLE
网络错误！请检查您的网络连接。  错误代码: 429

### ISSUE THREAD

**Issue by V1R1UL** [EdgeTranslate/EdgeTranslate#21]
拉住原文侧边翻译出现错误代码429，作者大大看下

**Comment by nickyc975** [comment]
这是由于翻译太频繁导致谷歌封IP了，只能等解封，我们也没办法。

**Comment by zhanxiage233** [comment]
一样的问题，出现错误的同时访问国内谷歌翻译地址是正常的

**Comment by Mark-Fenng** [comment]
我们再想想办法, 尽可能能解决这个问题

**Comment by gupeng1208** [comment]
不断出现429，我多次不断测试，发现如果不使用任何代理，直连就不会出现这个问题；如果使用了代理，很快就会出现429。是不是可以做一个判断；我这边使用的代理是clash

**Comment by nickyc975** [comment]
> 不断出现429，我多次不断测试，发现如果不使用任何代理，直连就不会出现这个问题；如果使用了代理，很快就会出现429。是不是可以做一个判断；我这边使用的代理是clash

收到，感谢测试。

**Comment by gupeng1208** [comment]
感谢你们的努力，能帮助到你们很开心。

________________________________
gupeng1208@outlook.com

发件人： Nicky Chen<mailto:notifications@github.com>
发送时间： 2019-07-18 19:16
收件人： EdgeTranslate/EdgeTranslate<mailto:EdgeTranslate@noreply.github.com>
抄送： gupeng1208<mailto:gupeng1208@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [EdgeTranslate/EdgeTranslate] 网络错误！请检查您的网络连接。 错误代码: 429 (#21)

不断出现429，我多次不断测试，发现如果不使用任何代理，直连就不会出现这个问题；如果使用了代理，很快就会出现429。是不是可以做一个判断；我这边使用的代理是clash

收到，感谢测试。

**Comment by zhanxiage233** [comment]
今天又出现429 429的同时扩展的整页翻译却是可用的
我这里还出现了一个403错误，好像是划词翻译特定的内容时就会出现   例如：“F5、Ctrl+R、command+R、地址栏刷新按钮”
不知道这个403错误是不是我这里的问题

**Comment by nickyc975** [comment]
> 今天又出现429 429的同时扩展的整页翻译却是可用的
> 我这里还出现了一个403错误，好像是划词翻译特定的内容时就会出现 例如：“F5、Ctrl+R、command+R、地址栏刷新按钮”
> 不知道这个403错误是不是我这里的问题

你用的是1.6.2还是1.6.1？

**Comment by gupeng1208** [comment]
> 今天又出现429 429的同时扩展的整页翻译却是可用的
> 我这里还出现了一个403错误，好像是划词翻译特定的内容时就会出现 例如：“F5、Ctrl+R、command+R、地址栏刷新按钮”
> 不知道这个403错误是不是我这里的问题

429是因为调用google翻译的API太频繁的问题，可是基本上翻墙的人很多都是买的SS，所以服务器的IP是一个，这样访问太频繁了，我想如果自己搭建SS服务，这个问题就可以避免。

**Comment by zhanxiage233** [comment]
> > 今天又出现429 429的同时扩展的整页翻译却是可用的
> > 我这里还出现了一个403错误，好像是划词翻译特定的内容时就会出现 例如：“F5、Ctrl+R、command+R、地址栏刷新按钮”
> > 不知道这个403错误是不是我这里的问题
> 
> 你用的是1.6.2还是1.6.1？

1.6.2

**Comment by zhanxiage233** [comment]
> > 今天又出现429 429的同时扩展的整页翻译却是可用的
> > 我这里还出现了一个403错误，好像是划词翻译特定的内容时就会出现 例如：“F5、Ctrl+R、command+R、地址栏刷新按钮”
> > 不知道这个403错误是不是我这里的问题
> 
> 429是因为调用google翻译的API太频繁的问题，可是基本上翻墙的人很多都是买的SS，所以服务器的IP是一个，这样访问太频繁了，我想如果自己搭建SS服务，这个问题就可以避免。

这个扩展用的国内谷歌翻译，按照我的代理设置，根本不走代理啊
而且我试了几个其他的翻译扩展或者脚本都没出现过类似的情况

**Comment by nickyc975** [comment]
429这个问题还有可能是因为我们的翻译接口调用没有设置cookie，导致谷歌把我们识别成机器人了。

**Comment by nickyc975** [comment]
我们正在排查

**Comment by nickyc975** [comment]
403的问题就很迷了，按道理应该修复了啊，我们自己测试也没再出现这个问题了。你试试手动访问一下translate.google.cn然后再用。

**Comment by zhanxiage233** [comment]
> 403的问题就很迷了，按道理应该修复了啊，我们自己测试也没再出现这个问题了。你试试手动访问一下translate.google.cn然后再用。

不好意思，现在没法测试，我这里现在已经全部429了  之前403错误的同时划词翻译其他内容是正常的

**Comment by nickyc975** [comment]
我们尽快修复！
