### ISSUE TITLE
内置pdf浏览器，浏览searchable的俄文pdf时，复制出来的句子都没有空格，单词全都连一起的

### ISSUE THREAD

**Issue by Mario-Hero** [EdgeTranslate/EdgeTranslate#216]
**describe the bug描述问题**

内置pdf浏览器，浏览searchable的俄文pdf时，复制出来的句子都没有空格，单词全都连一起的。用edge自带的pdf浏览器看就没问题。

**environment 使用环境**

Windows 10 专业工作站版 21H1

_browser name 浏览器类型 EDGE

_browser version 浏览器版本  91.0.864.59

_extension version 插件版本 2.2.1

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
能否提供一下出问题的pdf，以方便我们解决问题

**Comment by Mario-Hero** [comment]
ok, pdf 在附件里。













在 2021-06-29 16:24:00，"Lucky Feng" ***@***.***> 写道：

能否提供一下出问题的pdf，以方便我们解决问题

**Comment by Mark-Fenng** [comment]
@Mario-Hero 你回复的内容没有带上附件😂

**Comment by Mario-Hero** [comment]
那就百度云吧。。这个文件夹下的pdf都是用ABBYY ocr导出的searchable pdf，应该复制出来的句子都是不带空格的。


链接: https://pan.baidu.com/s/1Yvr7jV1ja1tG4ZbkloYshQ 提取码: fsv4 复制这段内容后打开百度网盘手机App，操作更方便哦













在 2021-06-29 16:42:55，"Lucky Feng" ***@***.***> 写道：

@Mario-Hero 你回复的内容没有带上附件

**Comment by Mark-Fenng** [comment]
确实是个问题，我们看一下pdf.js最新版本有没有修复这个问题

**Comment by nickyc975** [comment]
问题已在最新的pdf.js中被修复了，我们更新了侧边翻译中使用的pdf.js的版本，下个版本生效，感谢反馈！
