### ISSUE TITLE
增加微软的翻译引擎

### ISSUE THREAD

**Issue by luyajun** [EdgeTranslate/EdgeTranslate#22]
**功能描述**

能够使用微软提供的bing翻译作为翻译引擎翻译页面信息

**使用场景**

在google翻译无法使用的情况下作为一个替代，有道的翻译质量还是堪忧

**Comment by nickyc975** [comment]
后续有时间的话我们会尝试加上的。

**Comment by zsynacl** [comment]
求问功能开发如何了 😭 公司已经发生了无法使用google transelate的情况，急需更改翻译引擎

**Comment by Mark-Fenng** [comment]
> 求问功能开发如何了  公司已经发生了无法使用google transelate的情况，急需更改翻译引擎

如果急需的话，还是先用别的翻译插件吧，例如沙拉dict，划词翻译，翻译侠等

**Comment by nickyc975** [comment]
多翻译源已实现。
