### ISSUE TITLE
Network error! with Hybrid and Bing Translate sources

### ISSUE THREAD

**Issue by duianto** [EdgeTranslate/EdgeTranslate#220]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

Two of the translation sources return: Network error!
- Hybrid and Bing
```
Network error! Please check your network connection.

Error code: undefined

Error message: undefined

Error action: {"api":"bing","action":"translate","text":"recommends","from":"auto","to":"en"}
```

There was a similar issue the first time Baidu Translate was chosen as the source:
```
Network error! Please check your network connection.

Error code: 0

Error message: "timeout of 5000ms exceeded"
```

But it might only have happened the first time.
Because it shows translation results now.

Google Translate and Tencent Translate
works every time.

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_
It happens on all pages.

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

- I searched for the word: test
on bing.com
- Double clicked on a word
- Clicked on the EdgeTranslate icon
- Chose Hybrid Translate or Bing Translate
from the top left button in the EdgeTranslate panel.

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

![msedge_ps2aPSAVe7](https://user-images.githubusercontent.com/13420573/124272405-f3d1cb80-db3e-11eb-9758-b63e9c113984.png)

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_
Edge

_browser version 浏览器版本 [e.g. 22]_
Version 91.0.864.64 (Official build) (64-bit)

_extension version 插件版本 [e.g. 2.0.0]_
2.2.1

**other information 其他信息**
Windows 10 21H1

**Comment by nickyc975** [comment]
This problem has been fixed. We will publish an update asap.
