### ISSUE TITLE
google翻译此页，选项框空白

### ISSUE THREAD

**Issue by gupeng1208** [EdgeTranslate/EdgeTranslate#23]
1.6.3版本出现使用鼠标右键选择google翻译此页的时候，可以翻译，但是页面顶部的选项框不能出来，出现空白；
浏览器版本chrome 75.0.3770.142

**Comment by nickyc975** [comment]
什么页面，方便发一下链接吗？

**Comment by gupeng1208** [comment]
查看了几个英文站，页面的google翻译会出现这种空白；有道翻译不会出现。另外firefox上面使用google翻译此页的时候完全正常，只有在chrome上出现

**Comment by gupeng1208** [comment]
查看了几个英文站，页面的google翻译会出现这种空白；有道翻译不会出现。另外firefox上面使用google翻译此页的时候完全正常，只有在chrome上出现，你可以用www.bbc.com复现这个问题

**Comment by gupeng1208** [comment]
使用chrome beta版本这个问题消失，beta版本为76.0.3809.71
