### ISSUE TITLE
更新后，弹出NOTICE页面

### ISSUE THREAD

**Issue by firerflystar** [EdgeTranslate/EdgeTranslate#231]
**describe the bug描述问题**

下午更新后除了少数网址：GITHUB GOOGLE 不会弹出提示页面，其他页面均被弹出
_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
划词翻译后，直接被带到NOTICE.HTML

提示如图

**testable address 出现问题的网址**

wiki 以及其他

**steps to reproduce复现步骤**
划词翻译， 跳转到提示页面 ， 刷新 ，重装插件或浏览器，COOKIES清除， 重启，无果。。。

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/62865237/125592843-8e96cae2-504a-4f2d-a430-3d22b398379f.png)

**environment 使用环境**
WINDOWS 专业版 20H2 + CHROME 91.0.4472.124 or Sidekick 90

**Comment by firerflystar** [comment]
在另部电脑上测试 Windows10 企业版 LTSC 正常 ，怀疑是不是因为我早上卸载了IE11, 重新装回， 还是没解决。

**Comment by firerflystar** [comment]
在另部电脑上测试 Windows10 企业版 LTSC 正常 ，怀疑是不是因为我早上卸载了IE11, 重新装回， 还是没解决。

**Comment by Mark-Fenng** [comment]
@firerflystar 感谢反馈，我马上去修复

**Comment by firerflystar** [comment]
> @firerflystar 感谢反馈，我马上去修复

感谢好作品，用了两天，没它不习惯了。

**Comment by Mark-Fenng** [comment]
在这个[commit](https://github.com/EdgeTranslate/EdgeTranslate/commit/5ce01cc25688e6594ccf6a3ca253861c59761912)中修复了
