### ISSUE TITLE
Chrome 2.2.2版本在www.sciencedirect.com上进行翻译会自动跳提示页面

### ISSUE THREAD

**Issue by Claire1982** [EdgeTranslate/EdgeTranslate#232]
2.2.1 版本正常，今天更新了下2.2.2版本再点翻译的时候就成了弹出新窗口了

**Comment by sshsu** [comment]
同，应该不是单单这个网站，我的91版本的chrome在很多网站都会跳转：
https://www.rfc-editor.org/rfc/rfc5109.html#page-7

https://www.baidu.com/s?wd=github&rsv_spt=1&rsv_iqid=0xbebd515000008eef&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=&tn=baiduhome_pg&ch=&rsv_dl=ib&rsv_enter=1&rsv_btype=i&inputT=1276

**Comment by Mark-Fenng** [comment]
非常抱歉，webpack更新了一下版本就build出问题了，2.2.3版本修复了，已经提交审核了
