### ISSUE TITLE
display.js:2 Uncaught Error: Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by kmvan** [EdgeTranslate/EdgeTranslate#233]
**describe the bug描述问题**
F12 console shows:
```
display.js:2 Uncaught Error: Automatic publicPath is not supported in this browser
    at display.js:2
    at display.js:2
    at display.js:696
```
_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
Script error.

**testable address 出现问题的网址**
https://cn.bing.com

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_
https://cn.bing.com

**steps to reproduce复现步骤**
Access any page, F12 switch `console` and get the error.

_describe steps to reproduce 请在此给出问题的复现步骤_
Access any page, F12 switch `console` and get the error.

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/3839554/125720040-f6687983-924d-47a7-831b-cdfb5888fe95.png)

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_
![image](https://user-images.githubusercontent.com/3839554/125720040-f6687983-924d-47a7-831b-cdfb5888fe95.png)

**environment 使用环境**
Wndows 10 20h2

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_
Chrome Version 91.0.4472.124 (Official Build) (64-bit)

_browser name 浏览器类型 [e.g. chrome, firefox]_
chrome

_browser version 浏览器版本 [e.g. 22]_
91.0.4472.124

_extension version 插件版本 [e.g. 2.0.0]_
2.2.2

**other information 其他信息**
none

_other information(optional) 如果还有其他相关信息，请补充到这里_
none

**Comment by Mark-Fenng** [comment]
We're so sorry. We've fixed this problem and submitted a new patch version. It will be published in a short time.

**Comment by kmvan** [comment]
Thanks
