### ISSUE TITLE
pdf划句子时会增加额外的换行符干扰翻译，希望能够提供过滤换行符的功能

### ISSUE THREAD

**Issue by Illyrix** [EdgeTranslate/EdgeTranslate#236]
**describe feature功能描述**
增加选项：翻译时移除换行符和制表符

**scene used使用场景**
pdf划词

**your solution 你的解决方案**
在发送翻译请求之前replace换行符和制表符为空格

**more information 其他信息**

**Comment by Vang3lis** [comment]
+1 
原本 2.2.1 还没出现这个问题， 2.2.3 出现了该问题，从更新来看是处理空格出现了问题
问题：在选择多行的时候，会把每一行结尾的东西识别成回车

**Comment by Mark-Fenng** [comment]
收到，看起来是pdf.js最新的版本造成的

**Comment by daojixing** [comment]
换行影响翻译。
