### ISSUE TITLE
互译模式无法开启

### ISSUE THREAD

**Issue by GoodStudyDay** [EdgeTranslate/EdgeTranslate#237]
插件版本：2.2.3版本
谷歌浏览器：92.0.4515.107
描述: 互译模式无法开启
图片：https://user-images.githubusercontent.com/45306276/127257406-daf34daf-d442-4063-8641-d7be459d852f.png

**Comment by nickyc975** [comment]
源语言设为自动检测时时无法开启互译模式的，请将源语言改为需要翻译的语言。

**Comment by GoodStudyDay** [comment]
> 源语言设为自动检测时是无法开启互译模式的，请将源语言改为需要翻译的语言。

谢谢
