### ISSUE TITLE
firefox浏览器翻译切分不准确

### ISSUE THREAD

**Issue by gupeng1208** [EdgeTranslate/EdgeTranslate#24]
![图片](https://user-images.githubusercontent.com/33377548/61614001-48067c80-ac95-11e9-8e56-83b60b046026.png)

firefox在翻译的时候，遇到这类不能翻译的专有名词，会出现需要横向的拉的情况，chrome则不会出现；firefox版本是68.0.1

**Comment by nickyc975** [comment]
这个跟浏览器的换行策略有关，我们以后会抽时间优化一下的。
