### ISSUE TITLE
Page Translate not working

### ISSUE THREAD

**Issue by guru-of-sound** [EdgeTranslate/EdgeTranslate#25]
Using FireFox70.0a1 (2019-07-23) (64-bit)
The Google Page Translate Link Does not work. 

**描述问题*

_请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**出现问题的网址**

_如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**复现步骤**

_请在此给出问题的复现步骤_

**问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

_在这里给出你的使用环境，例如：_

_浏览器类型 [e.g. chrome, firefox]_

_浏览器版本 [e.g. 22]_

_插件版本 [e.g. 1.2.0]_

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
On which website?
Google page translate is not working on Github because of the content policy of Github.
