### ISSUE TITLE
firefox 选中后无法正常使用，弹出空白窗口，设置失踪了

### ISSUE THREAD

**Issue by Claire1982** [EdgeTranslate/EdgeTranslate#256]
**describe the bug描述问题**

选中后点击翻译弹出窗口，无内容，点设置按钮之后发现所有开关均关闭

**environment 使用环境**

Firefox 91.0 edge translate 2.2.3

**Comment by Mark-Fenng** [comment]
使用的操作系统，出现问题的网址和更多的浮现步骤也麻烦提供一下，因为根据目前的信息我还没能复现这个问题

**Comment by Claire1982** [comment]
> 
> 
> 使用的操作系统，出现问题的网址和更多的复现步骤也麻烦提供一下，因为根据目前的信息我还没能复现这个问题

win10 企业版 19043.1165，试了一下基本上每个网址都有这个问题……
https://www.sciencedirect.com/science/article/abs/pii/S8756328221001988?via%3Dihub
选中后点翻译就这样了[https://imgtu.com/i/fWi8US](url)
打开设置界面是这样[https://imgtu.com/i/fWiduq](url)

**Comment by Mark-Fenng** [comment]
非常奇怪的问题，请问在安装插件后有修改过设置吗，或者做过其他操作吗，如果能够看看设置界面的控制台信息将会更有帮助

**Comment by Claire1982** [comment]
没有，之前一直正常使用，最近更新过Firefox和Windows系统，问题出现的挺突然的

**Comment by Claire1982** [comment]
[https://imgtu.com/i/fhrv0e](url)
是这样嘛

**Comment by Mark-Fenng** [comment]
@Claire1982 截图中有挺重要的报错信息，我再详细看一下

**Comment by Claire1982** [comment]
今天试了一下可以正常使用了……问题有点魔怔

**Comment by Claire1982** [comment]
查了下，之前报错的时候Firefox 版本是91.0，现在是91.0.1，应该跟这次更新有关系
