### ISSUE TITLE
pdf文件阅读功能

### ISSUE THREAD

**Issue by yuuwenhao** [EdgeTranslate/EdgeTranslate#258]
**describe the bug描述问题**
打开非影印的pdf文件只显示标点、数字和页眉页脚
_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
从cnki知网下载的pdf文件，以前能够用侧边翻译打开浏览，无论是否影印。某次更新后无法显示非影印pdf文件的正文文字，退出侧边翻译后可以用edge自带的浏览器打开浏览。
**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
能否提供一下不能打开的非影印pdf文件，帮助我们尽快找到问题的原因

**Comment by yuuwenhao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EdgeTranslate/EdgeTranslate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 晚上11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EdgeTranslate/EdgeTranslate] pdf文件阅读功能 (#258)





 
能否提供一下不能打开的非影印pdf文件，帮助我们尽快找到问题的原因
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mark-Fenng** [comment]
@yuuwenhao 你的最新回复没有任何内容，可否重新编辑一下
