### ISSUE TITLE
有些网页无法翻译

### ISSUE THREAD

**Issue by YuI2333** [EdgeTranslate/EdgeTranslate#259]
例如：
https://winaero.com/category/windows-11/

浏览器：Edge 92

有道可以，谷歌不可以，麻烦帮忙看看，万分感谢！！

另外，当选中几十或更多文字时，右键菜单会变的很宽，有时选中文字目的不是翻译，但突然菜单很宽就很突兀，希望选中文字后的右键菜单修改为“翻译所选内容”几字。

还有个问题，双击单词翻译时页面左上角会有个窗口一闪而过，希望能去掉。

**Comment by Mark-Fenng** [comment]
感谢反馈！
1. 不能网页翻译的网站我们需要排查一下原因
2.  选中更多文字时菜单栏确实会变的很宽，但是我们扩展可能不是主要原因，在不打开扩展的情况下，菜单栏也很宽
![image](https://user-images.githubusercontent.com/27533910/129926329-48a1cf8e-0015-4d61-a085-b24642fdf82a.png)
3. 这个确实体验很不好，我们会尽快消除掉

**Comment by nickyc975** [comment]
问题一目前无解，只能先用有道代替了。

**Comment by Mark-Fenng** [comment]
问题三与issue #201 重复
