### ISSUE TITLE
侧边栏直接适配网页，而非浮窗

### ISSUE THREAD

**Issue by yuhw2001** [EdgeTranslate/EdgeTranslate#26]
**功能描述**
侧边栏不影响浏览时该插件最主要特色。
但是遇到全宽页面或者pdf文件时，浮动侧边栏遮挡文字对体验影响很大。

**使用场景**

_网页浏览

**你的解决方案**

frame直接插入网页？
或者参考有无类似插件？
https://www.ghacks.net/2010/07/22/enable-side-tabs-in-google-chrome/

**替代方案**

如果不能解决，让浮窗有一个左侧/右侧开关。这样阅读右侧的时候，我可以把浮窗放到左侧，阅读左侧的话，可以把浮窗放到右侧。

**其他信息**

无

**Comment by nickyc975** [comment]
你可以在插件的布局设置中勾选上“收缩页面”这个选项，这样翻译框就会将页面推开，而不是遮挡。
![image](https://user-images.githubusercontent.com/25877145/63206110-0eccfb00-c0e1-11e9-89ae-5395c049f729.png)

**Comment by yuhw2001** [comment]
原来如此！非常舒服！无出其右！
