### ISSUE TITLE
启用插件时 打开pdf会报错

### ISSUE THREAD

**Issue by Vstural** [EdgeTranslate/EdgeTranslate#261]
启用插件时 打开pdf会报错
似乎和一个叫pdf.js的东西有关 在使用语雀文档跳转至内嵌pdf时可以稳定复现

**Comment by Mark-Fenng** [comment]
可能帮忙提供一下出问题的pdf文件呢

**Comment by Vstural** [comment]
> 能否帮忙提供一下出问题的pdf文件呢

https://www.yuque.com/poxer/wk16us/qcudkk
可以尝试查阅该页的pdf，鼠标移至链接后点击弹出来的小眼睛（preview/预览）

**Comment by nickyc975** [comment]
感谢反馈，问题已修复，下个版本生效。
