### ISSUE TITLE
希望向侧栏界面的可点击元素添加辅助功能标记

### ISSUE THREAD

**Issue by gdh1995** [EdgeTranslate/EdgeTranslate#267]
**describe feature功能描述**

向侧栏里可点击的按钮添加特定 HTML 属性 `role=button`，使其可以被 Vimium、Vimium C 等键盘快捷键类扩展程序识别到。

**scene used使用场景**

使用 Vimium C 快速点击页面元素。但发现默认状态下侧栏里的元素不产生提示标志。

**your solution 你的解决方案**

对相应的 `span`, `svg` 和 `div` 等添加 `role=button`，比如 `<div>` 变成 `<div role="button">`。Vimium、Vimium C 支持不少种类的 role 属性，包括 `["button" , "tab" , "link", "checkbox", "menuitem", "menuitemcheckbox", "menuitemradio"]`。

**more information 其他信息**

我简单找了几个可以点击但 Vimium C 没提示的地方，比如：

![20210913_180215](https://user-images.githubusercontent.com/5547703/133066731-8c5dd59e-f1d3-45b7-9a3d-a827ffdf02c6.png)

**Comment by nickyc975** [comment]
添加属性后，在新打开的页面中，如果先进行翻译，再使用vimium c进行选择，确实可以给出提示；
但是如果是先使用vimium c进行过选择，那么之后的翻译结果就会挡住vimium c给出的提示，不知道这个是vimium c的问题还是我们的问题。

**Comment by nickyc975** [comment]
我推测是不是Vimium C没有监测页面元素的变化，只会根据初始状态计算一次z-index？

**Comment by gdh1995** [comment]
嗯，z-index用的是固定的INT32_MAX，遮挡是元素先后关系造成的。这个问题我昨天也发现了（ https://github.com/crimx/ext-saladict/issues/1481#issue-994412926 第二点），已经加了逻辑来移动 Vimium C 的根元素 （ https://github.com/gdh1995/vimium-c/commit/b1b2835cd0917b9ba8252fb82e91383a251a64e8 ），等下一版本应该好很多吧。

**Comment by nickyc975** [comment]
好的
