### ISSUE TITLE
建议翻译的目标语言也自动检测

### ISSUE THREAD

**Issue by yurenziyou** [EdgeTranslate/EdgeTranslate#27]
**功能描述**

_自动检测目标语言_

**使用场景**

_我想吧中文翻译为英文时，还需要去点击切换，而切换功能隐藏太深，需要多次点击鼠标_

**你的解决方案**

_建议翻译的目标语言也自动检测，例如选择的是英文，默认翻译为中文，选择的文本时中文，默认自动翻译为英文。不许要人为的选择目标语言。_

**Comment by Mark-Fenng** [comment]
感谢你的建议, 确实这样会更加方便些, 我们再想想办法, 看看有什么办法能做成这样
