### ISSUE TITLE
已允许侧边翻译读取和更改所有网站上留存的所有数据，但仍然显示“网络错误！请检查您的网络连接。  错误代码: 0  错误信息: "Network Error"”

### ISSUE THREAD

**Issue by 1haoyue** [EdgeTranslate/EdgeTranslate#274]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by 1haoyue** [comment]
已允许侧边翻译读取和更改所有网站上留存的所有数据，Google浏览器随便打开一篇文章翻译，仍显示“网络错误！请检查您的网络连接。错误代码: 0  错误信息: "Network Error"”
![image](https://user-images.githubusercontent.com/90747792/133378126-0dba1cce-7857-47d7-ac5f-6f0c95cec30c.png)
![image](https://user-images.githubusercontent.com/90747792/133378217-c3ee4872-07a1-4170-9deb-b75850063104.png)

**Comment by nickyc975** [comment]
更换其他翻译源试试呢？

**Comment by 1haoyue** [comment]
> 更换其他翻译源试试呢？

感谢解答，换成百度翻译果然可以了，不知道谷歌翻译是怎么了呢

**Comment by nickyc975** [comment]
不客气，可能是你的网络无法访问谷歌翻译。
