### ISSUE TITLE
网络错误！请检查您的网络连接。  错误代码: 0  错误信息: "Network Error"

### ISSUE THREAD

**Issue by zhouhaohao95** [EdgeTranslate/EdgeTranslate#276]
框选好英文段落后，右边显示网络错误。
![批注 2021-09-20 090640](https://user-images.githubusercontent.com/91037913/133949128-f3d66a9a-8b3b-42b0-8281-a464aef8ac1e.png)

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_edge浏览器

_browser version 浏览器版本 [e.g. 22]_版本 93.0.961.52 (官方内部版本) (64 位)

_extension version 插件版本 [e.g. 2.0.0]_2.2.3

**Comment by nickyc975** [comment]
谷歌翻译貌似无法直接访问了，请改用其他翻译源试试
