### ISSUE TITLE
谷歌翻译用不了

### ISSUE THREAD

**Issue by believer911** [EdgeTranslate/EdgeTranslate#278]
**describe the bug描述问题**

在不翻墙的情况下
划词翻译时谷歌翻译和必应翻译用不了

_browser name 浏览器类型 [e.g. Edge]_

_extension version 插件版本 [e.g. 2.2.3]_

**Comment by nickyc975** [comment]
收到，已确认问题，我们尽快修复。

**Comment by nickyc975** [comment]
与 #275 #276 是同一个问题
