### ISSUE TITLE
最近都无法使用谷歌翻译和腾讯翻译

### ISSUE THREAD

**Issue by zelin97** [EdgeTranslate/EdgeTranslate#279]
**describe the bug描述问题**

直接在网页中使用侧边翻译，鼠标左键选择文本，右键选择侧边翻译，只有百度翻译有结果，其它没有，腾讯翻译只有句号

**Comment by Mark-Fenng** [comment]
可以提供一下你选中的文本是什么内容吗

**Comment by nickyc975** [comment]
谷歌翻译的问题我们已经修复了，下个版本更新。腾讯翻译的话好像腾讯加强了爬虫检测，如果遇到无法使用的情况就先用着其他的翻译源吧，过一段时间应该会好，除此之外也没什么好办法。
