### ISSUE TITLE
翻译漏洞

### ISSUE THREAD

**Issue by Disciple7** [EdgeTranslate/EdgeTranslate#28]
**描述问题**

对以下句子进行侧边翻译（谷歌引擎）时，字体颜色会变绿：
If it shows <font color='#33cc33'>Correct</font> result, you're ready to move on!
在谷歌翻译官方网站上不会出现这个问题。是否没有将html语言视为字符串？

**出现问题的网址**

_如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**复现步骤**

在kaggle.com/learn中，使用notebook模式打开Data Visualization课程第一课“Hello，Seaborn”时，选中对应语句，右键“翻译'if...'”得到。

**问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

Chrome

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
字体颜色变绿是什么鬼？？？
是页面的字体颜色还是翻译结果的字体颜色？
