### ISSUE TITLE
翻译指定内容时, 没有推开网页的bug

### ISSUE THREAD

**Issue by sysescool** [EdgeTranslate/EdgeTranslate#281]
**describe the bug描述问题**

打开该[网站](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/)时,  
翻译指定内容时, 网页没有推过来.  

确认: 布局设置 - 收缩页面 (已打开)  

**testable address 出现问题的网址**  

https://www.khronos.org/registry/OpenGL-Refpages/es2.0/  
https://www.khronos.org/registry/OpenGL-Refpages/es3.0/  
https://www.khronos.org/registry/OpenGL-Refpages/es3.1/  

**steps to reproduce复现步骤**  

点击网页左侧链接, 如[glActiveTexture], 右侧网页内容刷新.  
选中部分内容, 右键菜单, 点击"翻译xxx..."  

**issue screenshot 问题截图**  

![image](https://user-images.githubusercontent.com/26477016/135199663-efb96c35-e4e4-4895-aa95-bd5b058bd20e.png)  

**environment 使用环境**  

_browser name 浏览器类型 **edge**  

_browser version 浏览器版本 **94.0.992.31**  

_extension version 插件版本 **2.2.3**  

**other information 其他信息**  

使用了网页侧边栏.

**Comment by nickyc975** [comment]
与 #280 是同一个问题，都是由于在该网页上无法通过 element.style   @@设置元素样式导致的，你有空可以研究一下 @Mark-Fenng 。

**Comment by Mark-Fenng** [comment]
@sysescool 这个页面的结构太特殊了，没有好办法去推开这个网页
