### ISSUE TITLE
使用div标签出现问题

### ISSUE THREAD

**Issue by strong-Tom** [EdgeTranslate/EdgeTranslate#299]
当使用chrome给div标签设置长宽和颜色后，会出现显示问题，使用ie无问题。

**Comment by Mark-Fenng** [comment]
可否再详细描述一下情景，最好能告诉我如何复现（在什么网页给div设置什么样式）

**Comment by Mark-Fenng** [comment]
fixed by the commit acc8f876dc1ebcddb049f9b29b6a1130a6d69c03
