### ISSUE TITLE
感觉最近侧边翻译返回的结果不是很正确

### ISSUE THREAD

**Issue by chihiro2014** [EdgeTranslate/EdgeTranslate#30]
通常如果翻译一句完整的句子会给出好几条差不多的翻译，现在好像默认只有一条了？

单词翻译还正常

**Comment by Mark-Fenng** [comment]
我去看一下，如果是google翻译返回的内容少了，那我们也没办法了
如果是api返回格式变了，我们会尽快修复的

**Comment by Mark-Fenng** [comment]
问题已经修复，请及时更新最新版本
