### ISSUE TITLE
添加功能：非内置的PDF阅读时，划词后出现翻译logo或设置快捷键直接翻译

### ISSUE THREAD

**Issue by Dagger-axe** [EdgeTranslate/EdgeTranslate#302]
**功能描述**

非内置的PDF阅读时，划词后出现翻译logo或设置快捷键直接翻译；
或
内置的PDF阅读器划词不要错位，且提高精度避免连带划取后续内容，如下：
![image](https://user-images.githubusercontent.com/44394720/140312588-b6537c27-f912-439e-a997-ea8609955bd8.png)

**使用场景**

阅读PDF文献时，如果使用内置的阅读器，划词不够准确，有偏移；如果不使用内置阅读器，每次都要右键后点击翻译，操作不便。

**你的解决方案**

增加图标或增强内置PDF阅读器。

**Comment by Mark-Fenng** [comment]
你提出的问题我们也做了很多尝试，但目前也没有想到办法改进
