### ISSUE TITLE
用Microsoft Edge打开一些中文pdf会出现编排错误，产生很大的空格

### ISSUE THREAD

**Issue by StWooow** [EdgeTranslate/EdgeTranslate#303]
**describe the bug描述问题**
用Microsoft Edge打开一些中文pdf会出现编排错误，产生很大的空格

**testable address 出现问题的网址**
https://changkun.de/modern-cpp/

**steps to reproduce复现步骤**
首页打开之后点击下载CN版本的 pdf 

**issue screenshot 问题截图**

![2](https://user-images.githubusercontent.com/9404211/140319435-a046e07e-0644-485c-ad37-ac83bfbf4b01.png)

下面是用正常情况(chrome或firefox正常)
![3](https://user-images.githubusercontent.com/9404211/140319521-6ce41d47-6fa3-4e14-b915-16e1a1506dc9.png)

**environment 使用环境**
windows 10 64位 

_browser name 浏览器类型
Microsoft Edge 版本95.0.1020.40 (官方内部版本) (64 位)

_extension version 插件版本
2.2.4

**other information 其他信息**
chrome firefox都正常，只有edge出现异常

**Comment by Mark-Fenng** [comment]
感谢反馈

**Comment by nickyc975** [comment]
pdf.js的问题，暂时无解。
