### ISSUE TITLE
Right click option problem

### ISSUE THREAD

**Issue by bakinazik** [EdgeTranslate/EdgeTranslate#307]
When I right click on firefox, page translate option are not visible. This does not happen only on one site, all sites have the same problem.

![screenshot](https://user-images.githubusercontent.com/61169988/143071224-3e77c60e-cb5b-4ca5-b5c2-7101d5191a44.png)
![version](https://user-images.githubusercontent.com/61169988/143071626-ab215e88-d3a2-4d57-8094-60c71f988e50.png)

**Comment by Mark-Fenng** [comment]
Because you are using a version without page translation. Please read this [log](https://github.com/EdgeTranslate/EdgeTranslate/blob/master/docs/wiki/en/ToFirefoxUsers.md) to install a fully functional version.
