### ISSUE TITLE
划词翻译图标位置自定义

### ISSUE THREAD

**Issue by Unkingh** [EdgeTranslate/EdgeTranslate#309]
**describe feature功能描述**

_自定义划词翻译图标的位置_

**scene used使用场景**

_Microsoft Edge 浏览器新增了迷你菜单，其位置与划词翻译图标位置重叠_
![image](https://user-images.githubusercontent.com/36095707/143392903-2732e176-53d6-4b3c-97db-cf679c38e21d.png)

**your solution 你的解决方案**
方案1. _停用 Microsoft Edge 迷你菜单：设置→外观→上下文菜单→关闭选择文本时显示迷你菜单_
方案2. _停用划词翻译，启用双击单词立即翻译_

**Comment by Mark-Fenng** [comment]
感谢反馈，是个解决办法，可以考虑加上
