### ISSUE TITLE
翻译文本添加英文

### ISSUE THREAD

**Issue by itangk** [EdgeTranslate/EdgeTranslate#31]
**功能描述**
希望侧边栏在翻译一段话的时候显示原文本，还有朗读希望能添加暂停功能（再次点击取消朗读之类的）。
_你想要什么样的功能 /改进？_

**使用场景**

_你是在什么场景下需要用到这个功能 /改进？_

**你的解决方案**

_你有没有想到什么解决方案？_

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
1. 将鼠标悬浮在翻译结果上方即可查看原文；

2. 暂停功能后续会考虑的，这段时间比较忙，暂时做不了。

**Comment by itangk** [comment]
啊啊啊啊啊，有回复！好激动！好炫酷！！好棒！




------------------ 原始邮件 ------------------
发件人: "Nicky Chen"<notifications@github.com>; 
发送时间: 2019年10月3日(星期四) 晚上8:02
收件人: "EdgeTranslate/EdgeTranslate"<EdgeTranslate@noreply.github.com>; 
抄送: "光"<1274605040@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译文本添加英文 (#31)



 
 
将鼠标悬浮在翻译结果上方即可查看原文；
 
 
 
暂停功能后续会考虑的，这段时间比较忙，暂时做不了。

**Comment by nickyc975** [comment]
当然有回复啦 /笑哭
还有问题吗？没有的话我关 issue 了。

**Comment by itangk** [comment]
没有了没有了hhhh，加油！



------------------ 原始邮件 ------------------
发件人: "Nicky Chen"<notifications@github.com>; 
发送时间: 2019年10月3日(星期四) 晚上8:54
收件人: "EdgeTranslate/EdgeTranslate"<EdgeTranslate@noreply.github.com>; 
抄送: "光"<1274605040@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [EdgeTranslate/EdgeTranslate] 翻译文本添加英文 (#31)




当然有回复啦 /笑哭
 还有问题吗？没有的话我关 issue 了。
