### ISSUE TITLE
翻译内置PDF浏览器什么时候能支持标注功能

### ISSUE THREAD

**Issue by fgqile** [EdgeTranslate/EdgeTranslate#310]
**describe feature功能描述**
翻译内置PDF浏览器支持标注功能

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**
在edge浏览器下使用
_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_
在linux系统下面，可用的词典软件很少，而且也没有edge translate使用方便。感谢感谢

**Comment by Mark-Fenng** [comment]
感谢反馈，与 #204 的建议差不多
