### ISSUE TITLE
侧边翻译无法使用

### ISSUE THREAD

**Issue by zhengweijia16** [EdgeTranslate/EdgeTranslate#311]
**describe the bug描述问题**侧边翻译插件无法在猎豹浏览器上使用，原因是网络错误，错误代码为0

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_在任何网页上都无法使用侧边翻译插件，显示结果均为“网络错误！请检查您的网络连接。错误代码：0”但我的网络没有任何问题.

**testable address 出现问题的网址**所有网页

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**选中需要翻译的句子，点击出现的侧边翻译图标，弹出侧边栏，加载一段时间后显示错误

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/95837846/145330416-3dcbc6de-d7c5-4e75-aeac-05260fa8b8aa.png)

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_windows 7

_browser name 浏览器类型 [e.g. chrome, firefox]_猎豹浏览器

_browser version 浏览器版本 [e.g. 22]_8.0.021806

_extension version 插件版本 [e.g. 2.0.0]_1.9.3

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
谷歌接口前几个月更新了，所以1.9.3版本的插件可能不能用了，需要更新到最新版本的

**Comment by zhengweijia16** [comment]
如何更新呢 最新版本是多少呢？



在 2021-12-09 11:52:07，"Lucky Feng" ***@***.***> 写道：

谷歌接口前几个月更新了，所以1.9.3版本的插件可能不能用了，需要更新到最新版本的

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mark-Fenng** [comment]
https://github.com/EdgeTranslate/EdgeTranslate/releases/tag/2.2.4
从这里可以下载到最新版

如果速度比较慢的话，也可以从这里下载
https://gitee.com/EdgeTranslate/EdgeTranslate/releases/2.2.4
