### ISSUE TITLE
Make the default viewer available

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [EdgeTranslate/EdgeTranslate#312]
# Proposal

When opening a PDF, if "Use built-in PDF" is enabled, the viewer provided by this extension will start.
I like this viewer, but sometimes I want to use browser default viewer.

Is it possible to provide a way to launch the default viewer?

This extension, which can be easily translated even from PDF, is very useful. Thank you:smile:

**Comment by Mark-Fenng** [comment]
yes, we have designed a button to do this. You can click a left arrow button on the top left of the viewer (i.e. the top tool bar) and then browser will navigate to the default viewer.

**Comment by Yarakashi-Kikohshi** [comment]
Oh, I didn't know there was this button.



I was able to launch the browser's default viewer as expected from this button on the top left.
Thank you!!:relaxed:
