### ISSUE TITLE
请问可以加一个自定义api吗？还有就是腾讯翻译总是不能正常使用，错误代码为200

### ISSUE THREAD

**Issue by female20** [EdgeTranslate/EdgeTranslate#313]
**describe feature功能描述**

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

**your solution 你的解决方案**

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
1. 自定义api是指允许自己添加翻译api吗？
2. 腾讯翻译无法使用是因为腾讯加强了爬虫检测，这个暂时没什么好办法，遇到问题就先用其他的翻译源顶替一段时间吧；
