### ISSUE TITLE
您好，我在使用你们的内置pdf阅读器时，会出现有些文字无法被选中，一段中会有一部分不能连续选中，导致翻译结果有误

### ISSUE THREAD

**Issue by lulununuhuhu** [EdgeTranslate/EdgeTranslate#314]
![issue](https://user-images.githubusercontent.com/51259289/146349081-94562170-cf1e-47d4-bc4a-719493e85c04.gif)

**Comment by Mark-Fenng** [comment]
非常抱歉，这个问题属于[pdf.js](https://github.com/mozilla/pdf.js)一直以来的缺陷，我们暂时也没有能力去改进这一点

**Comment by lulununuhuhu** [comment]
好的，有些pdf还是可以的，是不是不同的论文排版格式造成的呢？

**Comment by Mark-Fenng** [comment]
对的，pdf.js对某些排版的处理可能有些问题
