### ISSUE TITLE
support dark model for the panel

### ISSUE THREAD

**Issue by gglin001** [EdgeTranslate/EdgeTranslate#315]
**describe feature功能描述**

翻译面板支持 黑暗主题

**scene used使用场景**

电脑在使用黑暗主题时使用 EdgeTranslate 亮度对比很强烈, 如果支持黑暗主题设置会很棒!

**your solution 你的解决方案**

No

**more information 其他信息**

No

**Comment by Mark-Fenng** [comment]
感谢反馈, 与 #230 是相同的建议
