### ISSUE TITLE
必应翻译和腾讯翻译有些问题，必应选中英文没有翻译，只显示英文；而腾讯翻译弹出一个新标签（腾讯翻译），选中翻译的英文，点击翻译后无反应

### ISSUE THREAD

**Issue by Thinking123456** [EdgeTranslate/EdgeTranslate#316]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_
![Snipaste_2021-12-17_22-36-40](https://user-images.githubusercontent.com/90300990/146560616-a9aba186-38d6-4fcd-b22e-92d9ee7d207d.png)

**Comment by Mark-Fenng** [comment]
是否是翻译语言的设置的问题呢，腾讯翻译时弹出一个标签是正常现象，等待标签关闭后就可以展示翻译内容了

**Comment by Thinking123456** [comment]
感谢回复,确实是这样的
