### ISSUE TITLE
打开pdf文件后字符混乱

### ISSUE THREAD

**Issue by iTelock** [EdgeTranslate/EdgeTranslate#317]
**describe the bug描述问题**
已经授权可以读取文件URL，然而当我打开一些pdf文件的时候，出现了字符无法显示，位置错乱的现象，导致无法阅读。

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
我尝试打开多个PDF文件，问题似乎是当我打开英文pdf的时候没问题，但当我打开中文或者日文pdf的时候就会显示错乱。

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/35419800/146799561-6a6c3ce2-560f-4fa1-9188-306d49163d15.png)

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_
chrome
_browser version 浏览器版本 [e.g. 22]_
版本 96.0.4664.110（正式版本） （64 位）

_extension version 插件版本 [e.g. 2.0.0]_
2021/12/21刚刚安装

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by Mark-Fenng** [comment]
这个应该属于[pdf.js](https://github.com/mozilla/pdf.js)的问题，如果遇到这种问题，可以尝试点击页面左上角的返回按钮，跳转回浏览器自带的阅读器观看。
![image](https://user-images.githubusercontent.com/27533910/147422881-83f02a57-e229-490a-9c74-ed8f13ae6553.png)
