### ISSUE TITLE
chrome的pdf查看器，双击选词在换行时错误

### ISSUE THREAD

**Issue by zhanggenex** [EdgeTranslate/EdgeTranslate#32]
双击require选词，不能正确选择
![image](https://user-images.githubusercontent.com/26472848/66878555-f0a24f00-efec-11e9-8e81-acc4750989f8.png)

双击interaction选词，错误地选中了上一行的词
![image](https://user-images.githubusercontent.com/26472848/66878594-28a99200-efed-11e9-9c34-eecfd994d34b.png)

**怀疑是不是行末出现-符号的时候条件判断写错了。。。**

**Comment by nickyc975** [comment]
我们内置的pdf查看器是mozilla的pdf viewer，这是pdf viewer的问题，我们也没办法，只能等mozilla改进。
