### ISSUE TITLE
[Future request] Remove some specific elements

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [EdgeTranslate/EdgeTranslate#322]
# [Future request] Remove some specific elements

If you select a test of main body in PDF, the translation may not be processed correctly because it contains sentences that you do not want to include.

For example:

- margin note
- header and footer (page numbers etc.)
    - When selecting text that spans page breaks

Is it possible to implement a feature to get rid of this?

**Comment by Mark-Fenng** [comment]
Sorry for that, it's a quite common issue with pdf.js. We have made some efforts but still find no solution.
