### ISSUE TITLE
部分pdf打开显示异常，尤其是发票类pdf

### ISSUE THREAD

**Issue by yanpd01** [EdgeTranslate/EdgeTranslate#324]
**describe the bug描述问题**

打开部分pdf的时候，只显示一些轮廓，不显示文字，尤其是发票这一类的pdf，基本全军覆没。

**steps to reproduce复现步骤**

用内置pdf阅读器打开pdf文件即可

**issue screenshot 问题截图**

下面两张图，第一张是用别的阅读器打开，第二张是用内置阅读器打开。
![001](https://user-images.githubusercontent.com/69427931/150461264-0d78eaa5-2fee-4506-9b58-dd734371be41.jpg)

![002](https://user-images.githubusercontent.com/69427931/150461267-58592077-6164-4b46-ab1f-cba2102d36bd.jpg)

**environment 使用环境**

_browser name 浏览器类型 [edge]_

_browser version 浏览器版本 [97.0.1072.62]_

_extension version 插件版本 [2.2.4]_

_system version 系统版本 [win10 19044.1466]_

**other information 其他信息**

附件pdf如下：
[43D279A3-4666-4482-BCA0-CB7B1ACFEFA9.pdf](https://github.com/EdgeTranslate/EdgeTranslate/files/7910186/43D279A3-4666-4482-BCA0-CB7B1ACFEFA9.pdf)

**Comment by Mark-Fenng** [comment]
@nickyc975 更新一下pdf.js可不可以解决这个问题呢

**Comment by nickyc975** [comment]
我抽空看看，不过大概率不行，这个问题已经存在很久了

**Comment by nickyc975** [comment]
暂时无解，我们会尝试向上游开发者反馈。
