### ISSUE TITLE
建议给网页翻译时鼠标悬停句子显示原文功能提供提供关闭选项

### ISSUE THREAD

**Issue by ghost** [EdgeTranslate/EdgeTranslate#328]
**describe feature功能描述** ：
网页翻译时，鼠标悬停在某句话上，会出现原文的文本框，有时会影响观看，建议添加一个关闭功能，因为鼠标有时候不小心放在某句话上，就会弹出原文

**your solution 你的解决方案** 希望能提供关闭选项

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_
![无标题](https://user-images.githubusercontent.com/98328670/150797019-60ddea7f-f139-4247-8ab3-8aae17cbf840.jpg)

**Comment by Mark-Fenng** [comment]
网页翻译集成的是谷歌网页翻译的服务，悬浮功能我们暂时没有办法去定制
