### ISSUE TITLE
建议增加弹出框模式

### ISSUE THREAD

**Issue by Void-zack** [EdgeTranslate/EdgeTranslate#33]
可以参考一下Google官方的翻译插件那样直接将结果显示在单词下面，感觉用起来会更方便一点。
每一次翻译的结果在左边显示出来对小屏幕来说有点占空间了

**Comment by nickyc975** [comment]
这个我们后续会考虑的，感谢反馈！

**Comment by Mark-Fenng** [comment]
已经实现，即将退出v2.0，欢迎体验
