### ISSUE TITLE
How to set a Target language?!

### ISSUE THREAD

**Issue by zambala** [EdgeTranslate/EdgeTranslate#330]
Hello, I need a help!

I downloaded the Firefox extension Edge Translate from Firefox Extensions, I can not find How to set the target language?!

How to set the target language?! I can not find this! I am using a browser in Italian, because I am learning Italian, but I don't know Italian perfectly, I try to translate Italian, it gives me a translation in Italian, Italian is translated in Italian, but I need in English... Please help!

**Comment by Mark-Fenng** [comment]
Click the EdgeTranslate icon on the right top corner and there will be a po up window. Then click the down arrow button and language settings will show up.

**Comment by zambala** [comment]
OK, Thanks, but it was not in general settings.

**Comment by Mark-Fenng** [comment]
Sorry for that, it should be in a more prominent place
