### ISSUE TITLE
内置PDF浏览本地PDF时，能比较方便的获取到当前文件的路径

### ISSUE THREAD

**Issue by xyc0123456789** [EdgeTranslate/EdgeTranslate#331]
**describe feature功能描述**
内置PDF浏览本地PDF时能提供该PDF的保存路径

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

在PDF浏览工具栏上提供一个按钮或者其他方式可以直接复制当前PDF文件路径，或者能直接打开该文件所在文件夹

**scene used使用场景**

使用插件打开本地PDF，并在浏览器上保存为书签。从这个书签找到本地文件，只能先复制下url的file的值，然后url解码调用两次，才能获取到真实路径

**your solution 你的解决方案**

对当前的url的file的值解析为真实路径，然后以某种便捷的方式提供复制，或者能直接打开所在的文件夹就更好了

**Comment by nickyc975** [comment]
不错的建议，我们会加上的。
