### ISSUE TITLE
In the Russian version add-ons

### ISSUE THREAD

**Issue by ViktorOn** [EdgeTranslate/EdgeTranslate#335]
Hello again :)
The name in the Russian version of Firefox add-ons is written in Chinese. It seems to me that it would be better to write the name in Latin, as in the English version of the add-ons.
Today I tried to find your extension for my Firefox (by searching), but I couldn't find it (because I don't know Chinese).
![2022-02-20 115933](https://user-images.githubusercontent.com/63919734/154838203-90969d96-4913-4e7e-8f41-0f3647ea78d9.png)
![2022-02-20 120318](https://user-images.githubusercontent.com/63919734/154838204-0857ec19-2878-4986-be47-1c0a4a69e85d.png)

**Comment by nickyc975** [comment]
Thank you for your feedback! We have changed the default language to English(US). You can find the extension by its English name now.

**Comment by ViktorOn** [comment]
Great! Thank you.
