### ISSUE TITLE
划线定位不准确

### ISSUE THREAD

**Issue by berry-ding** [EdgeTranslate/EdgeTranslate#336]
在划线翻译时有时会出现定位不准确的情况，导致单词缺少前几个或后几个字符（往往是前几个），例如
![image](https://user-images.githubusercontent.com/40165666/155948185-9f979a50-5b1a-4884-900c-02a8d3c4361d.png)

在我双击选中某个单词，可以准确的翻译，但选择框出现了偏移，如下
![image](https://user-images.githubusercontent.com/40165666/155948338-f92e5480-363c-42d9-81dc-d05d602bda62.png)

environment 使用环境
windows 10 64位

_browser name 浏览器类型
Microsoft Edge 版本 98.0.1108.62 (官方内部版本) (64 位)

_extension version 插件版本
2.2.4

other information 其他信息

**Comment by nickyc975** [comment]
这个是我们使用的pdf浏览器的问题，暂时无解，遇到这个问题你可以尝试缩放一下文档看看。
