### ISSUE TITLE
firefox火狐浏览器能否将侧边窗口嵌入到自带的侧栏中

### ISSUE THREAD

**Issue by vate34** [EdgeTranslate/EdgeTranslate#337]
**describe feature功能描述**

插件使用的弹窗效果已经非常优秀了。但实际上火狐浏览器自带有侧边栏，一些扩展使用该功能后效果非常好（如树状标签页和Bitwarden）。鉴于这个插件窗口的样式与自带的非常吻合，请问是否可以将弹窗放到其中，利用自带的api做到风格统一。
![图片](https://user-images.githubusercontent.com/17670639/156188265-caa975dd-d905-4fa3-8f1f-cfbda2e73645.png)
![图片](https://user-images.githubusercontent.com/17670639/156188313-d641f747-0cca-471b-b371-7b057794fca9.png)

**Comment by nickyc975** [comment]
这个功能室只有火狐提供了是吗？如果是的话，考虑到不同浏览器之间体验的一致性，我们无法针对火狐去单独适配。

**Comment by vate34** [comment]
> 

是的
