### ISSUE TITLE
建议将“划词翻译”开关移到更方便的位置

### ISSUE THREAD

**Issue by luozikuan** [EdgeTranslate/EdgeTranslate#340]
**describe feature功能描述**
建议将“划词翻译”开关移到更方便的位置

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_
例如单击插件按钮的时候就显示“划词翻译”开关，也就是移到和“互译模式”一起

**scene used使用场景**
大部分划词的时候只是想复制，但是现在“划词翻译”的开关入口较深，不能方便地切换“划词翻译”开关。建议提高此开关的操作便捷性。

**Comment by Mark-Fenng** [comment]
谢谢，是个很好的建议
