### ISSUE TITLE
无法正常查看后缀名为pdf的网页

### ISSUE THREAD

**Issue by njzjz** [EdgeTranslate/EdgeTranslate#35]
**描述问题**

无法正常查看后缀名为pdf的网页

**出现问题的网址**

https://commons.wikimedia.org/wiki/File:Test.pdf

**复现步骤**

打开网页

**问题截图**

![image](https://user-images.githubusercontent.com/9496702/67629583-1bdb3880-f84e-11e9-9a0c-174a84d6b72b.png)

**使用环境**

浏览器类型 Edge (Chromium)

浏览器版本 80.0.315.0

插件版本 1.6.3

**其他信息**

**Comment by Mark-Fenng** [comment]
感谢反馈，这确实是个问题，这个网页比较特殊，我们想办法解决一下

**Comment by nickyc975** [comment]
遇到这个问题你可以点一下浏览器左上角的回退，就可以正常查看了。
