### ISSUE TITLE
内置pdf reader 无法渲染某些pdf中的中文字体

### ISSUE THREAD

**Issue by Chemelon** [EdgeTranslate/EdgeTranslate#351]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
使用扩展的内置pdf reader 非常方便，可以迅速划词翻译，但是在打开部分中文pdf时其中的字体都无法正常渲染，表现为空白，只有英文字符正常显示，使用edge的默认pdf reader 可以正常阅读，但是无法双击单词翻译。
![image](https://user-images.githubusercontent.com/43750013/162455934-17f7238c-172b-4452-b24a-fb3718cf6320.png)

_browser version 浏览器版本 [e.g. 22]_
mico soft edge 版本 100.0.1185.29 (正式版本) (64 位)
_extension version 插件版本 [e.g. 2.0.0]_
2.2.4

**Comment by nickyc975** [comment]
这个是我们使用的pdf浏览器的bug，我们会尝试向上游开发者反馈，但是能不能修复就不知道了。
