### ISSUE TITLE
使用插件自带PDF浏览器显示出错

### ISSUE THREAD

**Issue by TigerHall** [EdgeTranslate/EdgeTranslate#356]
**describe the bug描述问题**

阅读PDF文件时产生花屏、卡顿等问题

估计是打开符合PDF/A标准的PDF文件会导致浏览器整个界面花屏，卡顿，过会恢复正常。
但继续阅读PDF的过程中，仍旧会有卡顿花屏等问题，十分影响体验。

**steps to reproduce复现步骤**
![image](https://user-images.githubusercontent.com/45758097/163940611-bff6d58b-4c5a-4c30-89f9-8f322182aaaa.png)

**environment 使用环境**
_browser name 浏览器类型 [e.g. chrome, firefox]_ Microsoft Edge
_browser version 浏览器版本 [e.g. 22]_ 版本 100.0.1185.44 (正式版本) (64 位)
_extension version 插件版本 [e.g. 2.0.0]_ 侧边翻译大小: 6.1 MB大小6.1 MB版本: 2 . 2 . 4版本2.2.4。 下载来源：Edge插件商城

**Comment by nickyc975** [comment]
方便提供一下出问题的PDF文件吗？

**Comment by Mark-Fenng** [comment]
在我的电脑上打开就没有任何问题, 这个可能是浏览器在特定电脑硬件上的渲染问题了

**Comment by nickyc975** [comment]
我这里打开也没有任何问题

**Comment by TigerHall** [comment]
确实是我电脑的问题，刚刚在出问题的电脑上，又能正常加载了😂
感谢开发者

**Comment by nickyc975** [comment]
不客气
