### ISSUE TITLE
建议添加暗色模式。

### ISSUE THREAD

**Issue by TPAXcc** [EdgeTranslate/EdgeTranslate#362]

**Comment by canbus** [comment]
同建议.用了EdgeTranslate会导致chrome及edge自身的Dark Mode失效

**Comment by canbus** [comment]
补充一下:是用浏览器阅读pdf时,EdgeTranslate会导致chrome及edge自身的Dark Mode失效

**Comment by TPAXcc** [comment]
> 补充一下:是用浏览器阅读pdf时,EdgeTranslate会导致chrome及edge自身的Dark Mode失效

建议各位换用 [FilipePS/Traduzir-paginas-web](https://github.com/FilipePS/Traduzir-paginas-web)。
