### ISSUE TITLE
在edge浏览器中不能关闭（双击单词立即翻译）这个功能，关闭了还是双击单词就自动翻译。

### ISSUE THREAD

**Issue by huxiaofeng999** [EdgeTranslate/EdgeTranslate#365]
![Inked1_LI](https://user-images.githubusercontent.com/105413488/168011153-6ddd73a6-6c79-4030-ae68-dda98567737c.jpg)
![Inked3_LI](https://user-images.githubusercontent.com/105413488/168011163-32772871-6a39-42a7-a417-3b4311ac9802.jpg)

**Comment by huxiaofeng999** [comment]
不管是打开还是关闭这个选项 （双击单词立即翻译），都是双击单词自动翻译，关闭不了
![3](https://user-images.githubusercontent.com/105413488/168012236-dd6bf5b7-bc85-431a-9582-3b134e5c3bae.PNG)
。

**Comment by Mark-Fenng** [comment]
因为双击后还是会选中这个单词，因为你同时打开了“划词立即翻译功能”，所以还是会进行翻译

**Comment by huxiaofeng999** [comment]
那双击单词立即翻译这个功能怎么关闭？需要怎么设置？

**Comment by Mark-Fenng** [comment]
把“划词立即翻译功能”这个也关闭就可以了

**Comment by huxiaofeng999** [comment]
OK，Thank you.
