### ISSUE TITLE
百度翻译功能失效

### ISSUE THREAD

**Issue by mojo55aa** [EdgeTranslate/EdgeTranslate#379]
https://github.com/EdgeTranslate/EdgeTranslate/blob/20a2361f02e84572513f16d302bdd210ffe21df4/src/background/library/translators/baidu.js#L284

**百度翻译页面更新，window.gtk获取规则由单引号变成双引号，现在抛出异常。**

**修复：**
`this.gtk = response.data.match(/window.gtk = "(.*?)"/)[1]; `

**Comment by nickyc975** [comment]
感谢反馈，已修复
