### ISSUE TITLE
本地pdf文件划线翻译后 空格/上下左右 翻页控制失效

### ISSUE THREAD

**Issue by gglin001** [EdgeTranslate/EdgeTranslate#38]
**描述问题**

本地pdf文件划线翻译后, 空格/上下左右 翻页控制失效, 需要切换到其他的浏览器标签后再切回来这些控制按键才能继续使用.

**出现问题的网址**

本地pdf文件

**复现步骤**

打开本地的pdf文件(可复制文字的那种pdf), 使用鼠标单选文字, 翻译选择的文字, 然后上述的控制按键就不生效了.

**使用环境**

linux, Ubuntu 18.04

Chrome 78

1.6.4

**其他信息**

这个插件对我阅读英文文献起到了极大地帮助, 感谢开发者付出的的辛勤劳动!

**Comment by Mark-Fenng** [comment]
我的环境和你的一模一样，但是在我这里没有办法复现。
这个问题是不是因为你在翻译后，在侧边框进行了点击操作，页面焦点到了侧边框，按键操作控制的是侧边框内，而不是pdf文件页面
试试点击pdf页面后，按键控制还能不能用

**Comment by gglin001** [comment]
我试了以下, 应该是焦点的问题, 只有在选择文字翻译后, 鼠标主动关闭右侧的翻译侧边框, 这时发生了按键不能操作的情况, 但是这个时候鼠标点击一下pdf的界面, 依然不能控制, 不知为何

**Comment by Mark-Fenng** [comment]
> 我试了以下, 应该是焦点的问题, 只有在选择文字翻译后, 鼠标主动关闭右侧的翻译侧边框, 这时发生了按键不能操作的情况, 但是这个时候鼠标点击一下pdf的界面, 依然不能控制, 不知为何

我找到复现的方式了，你用的chrome自带的pdf阅读器，我试了试确实有这种情况。
我们之后会试着修复这个问题，你也可以在设置里打开pdf.js阅读器，在这里没有这个问题。
