### ISSUE TITLE
划词翻译时个别翻译源会出现“网络错误！请检查您的网络连接。”的字样

### ISSUE THREAD

**Issue by hlx31** [EdgeTranslate/EdgeTranslate#381]
**describe the bug描述问题**

当我进行划词翻译时混合翻译和百度翻译以及DeepL会出现"网络错误！请检查您的网络连接。"的字样。

混合翻译以及百度翻译的错误如下：
错误代码: undefined
错误信息: undefined

Deepl翻译的错误如下：
错误代码: 504
错误信息: "Wait result timeout!"
错误操作: {"api":"deepl","action":"translate","text":"bug","from":"auto","to":"zh-CN"}

**environment 使用环境**

_environment info:使用环境：_

_browser name 浏览器类型：Edge_

_browser version 浏览器版本：103.0.1264.62（正式版本）64bit_

_extension version 插件版本：2.3.0_

**Comment by logo306142054** [comment]
遇到同样的错。win10 edge brower，版本 103.0.1264.71 (正式版本) (64 位)，插件版本2.3.0.
另外腾讯翻译会概率报错

**Comment by zerohk** [comment]
一样，win11 Chrome 103.0.5060.134。所有都不行。![](http://pic.buercheng.space/images/20220729094738.png)

**Comment by amitbha** [comment]
确实，所有都失败
我用的是火狐

**Comment by SeeingDragon** [comment]
我也是

**Comment by wqcblog** [comment]
我按照作者提供的百度翻译修复方法，重新编译修复了，对于Deepl翻译将其隐藏不显示，并且按照我的使用习惯把google.com替换为google.cn，在作者还没有发布新的release，可以用我这个凑合一下。
[Edgetranslate.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/9266113/Edgetranslate.zip)

**Comment by nickyc975** [comment]
百度翻译的问题已修复，谷歌翻译的问题我们会尽量改的更灵活一些，感谢大家的反馈

**Comment by sywee** [comment]
我也存在这样的问题。混合翻译、百度翻译会出现。 侧边翻译 2.3.0版， Edge 105.0.1343.33。期待作者能解决一下。
