### ISSUE TITLE
zetero connector chrome 插件无法识别pdf viewer中的pdf文件并添加到zetero库中

### ISSUE THREAD

**Issue by leigao97** [EdgeTranslate/EdgeTranslate#383]
**describe feature功能描述**

需要内置的pdf viewer打开的pdf文件能被zetero connector chrome插件正确识别
当默认关闭内置的pdf viewer后，zetero connector可以正常识别当前的pdf

**scene used使用场景**

需要使用[zetero connector](https://chrome.google.com/webstore/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc) 插件将当前pdf页面添加到zetero库中

**your solution 你的解决方案**

或许修改pdf viewer可以使其格式可被识别，相关论坛讨论：https://forums.zotero.org/discussion/83913/save-to-zotero-on-a-web-page-of-the-pdf-viewer-extension

**more information 其他信息**

无

**Comment by nickyc975** [comment]
是个不错的建议，我们会尝试实现。
