### ISSUE TITLE
EDGE默认pdf阅读器划词翻译不生效

### ISSUE THREAD

**Issue by bzxgcs** [EdgeTranslate/EdgeTranslate#389]
**describe the bug描述问题**

_使用edge打开pdf，划词翻译无效。虽然我知道用插件默认pdf阅读器可以解决，但是edge的pdf批注功能还挺好用的_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_打开任意一篇本地pdf，可以右键菜单翻译，不能划词翻译_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [edge]_

_browser version 浏览器版本 [104.0.1293.70]_

_extension version 插件版本 [2.3.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
这个是已知问题，且暂时无法解决，要在PDF文件中使用划词翻译请使用扩展内置的PDF阅读器。

**Comment by bzxgcs** [comment]
> 这个是已知问题，且暂时无法解决，要在PDF文件中使用划词翻译请使用扩展内置的PDF阅读器。

刚想到了一个替代方案：是否可以监测鼠标抬起事件，抬起时直接复制文字？
