### ISSUE TITLE
此插件导致有些页面打不开, 比如swagger 的api界面, 某些路由器后台界面

### ISSUE THREAD

**Issue by punisher1** [EdgeTranslate/EdgeTranslate#39]
**描述问题**

Firefox71下面, 此插件会导致swagger api界面不能显示, 一片空白

**出现问题的网址**

swagger api界面(已发现的为：https://app.swaggerhub.com/search), 路由器后台界面(华三路由器)

**复现步骤**

起一个swagger api 

**问题截图**

**使用环境**

Firefox71
Windows 10

**其他信息**

**Comment by Mark-Fenng** [comment]
我们没有条件测试你描述的网址
不知你可否给我们截图一下那个页面下的控制台信息或你认为可能有用的调试信息
谢谢

**Comment by Winnieking-Xi** [comment]
我也出现同样问题
出现问题的网址是路由器的管理页面
firefox版本：71.0 (64 位)
Win10 专业版(x64)
已经用排除法排除了其他扩展的可能。

正常页面
![1](https://user-images.githubusercontent.com/58734807/70532455-0ae24e80-1b92-11ea-8e47-64de86f08c5a.jpg)

故障页面
![2](https://user-images.githubusercontent.com/58734807/70532487-1d5c8800-1b92-11ea-9d11-fa930865da1f.jpg)

**Comment by Mark-Fenng** [comment]
> 我也出现同样问题
> 出现问题的网址是路由器的管理页面
> firefox版本：71.0 (64 位)
> Win10 专业版(x64)
> 已经用排除法排除了其他扩展的可能。
> 
> 正常页面
> ![1](https://user-images.githubusercontent.com/58734807/70532455-0ae24e80-1b92-11ea-8e47-64de86f08c5a.jpg)
> 
> 故障页面
> ![2](https://user-images.githubusercontent.com/58734807/70532487-1d5c8800-1b92-11ea-9d11-fa930865da1f.jpg)

我试着解决了一下这个问题，不知道你是否有兴趣提前测试一下，看看问题是否解决了，下面的链接是打包好的项目文件
[edge_translate_firefox.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/3945014/edge_translate_firefox.zip)
安装要使用firefox 的debug模式(如果不熟悉的话，在项目首页的Readme里有操作步骤)

**Comment by Winnieking-Xi** [comment]
> 
> 
> > 我也出现同样问题
> > 出现问题的网址是路由器的管理页面
> > firefox版本：71.0 (64 位)
> > Win10 专业版(x64)
> > 已经用排除法排除了其他扩展的可能。
> > 正常页面
> > ![1](https://user-images.githubusercontent.com/58734807/70532455-0ae24e80-1b92-11ea-8e47-64de86f08c5a.jpg)
> > 故障页面
> > ![2](https://user-images.githubusercontent.com/58734807/70532487-1d5c8800-1b92-11ea-9d11-fa930865da1f.jpg)
> 
> 我试着解决了一下这个问题，不知道你是否有兴趣提前测试一下，看看问题是否解决了，下面的链接是打包好的项目文件
> [edge_translate_firefox.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/3945014/edge_translate_firefox.zip)
> 安装要使用firefox 的debug模式(如果不熟悉的话，在项目首页的Readme里有操作步骤)

你好，已经测试完毕。以下是测试结果截图

正常页面，已经不存在之前问题
![1](https://user-images.githubusercontent.com/58734807/70590620-428edc00-1c0e-11ea-915e-c88a9e009963.jpg)

翻译功能也能正常使用
![2](https://user-images.githubusercontent.com/58734807/70590662-59353300-1c0e-11ea-874e-714299b6b3a7.jpg)

非常感谢修复此问题！
