### ISSUE TITLE
How to use deepl in edge translate

### ISSUE THREAD

**Issue by GhostShadow0316** [EdgeTranslate/EdgeTranslate#398]
I see edge translate can translate with deepl, but I don't know how to use

**Comment by Mark-Fenng** [comment]
You can use it from the translator source list
<img width="262" alt="image" src="https://user-images.githubusercontent.com/27533910/192198937-22c5260d-ec63-49b6-8b0a-5bad188eedf6.png">
After you choose the DeepL, then the translation result will be the result fetched from deepl

**Comment by egoistinr** [comment]
我的選單翻譯源只有3個
![image](https://user-images.githubusercontent.com/27774913/207226802-565d19a9-0e08-4f5c-947a-523b0568271f.png)
設定處也是
![image](https://user-images.githubusercontent.com/27774913/207227453-3dc682a6-95d6-460b-9c14-e590688479d6.png)

嘗試重新安裝依然如此
我是從chrome商店安裝的 版本2.4.0
chrome版本: 108.0.5359.99
