### ISSUE TITLE
页面翻译功能不起作用

### ISSUE THREAD

**Issue by raysworld** [EdgeTranslate/EdgeTranslate#40]
for the google page translator, nothing appears; 
for the youdao page translator, only a toolbar appears and nothing on the page is actually translated.

**Comment by Mark-Fenng** [comment]
When using youdao page translator,  you need to choose "full text translation" button and only this level will work well.
For the google page translator, some websites like github don't work well because of some security policy but most other websites can work perfectly.

**Comment by Mark-Fenng** [comment]
Could you please tell  us more information like browser type, version or website url where problems occured?

**Comment by raysworld** [comment]
> Could you please tell us more information like browser type, version or website url where problems occured?

Thanks for your response. Now I know how to use the youdao page translator, but the google page translator is still not working... (I am using [this page](https://www.bbc.com/news/world-us-canada-50831743) as an example to test. )
Browser Type: Edge Chromiun
Browser Version: 80.0.361.5 (Official build) dev (64-bit)

**Comment by Mark-Fenng** [comment]
> > Could you please tell us more information like browser type, version or website url where problems occured?
> 
> Thanks for your response. Now I know how to use the youdao page translator, but the google page translator is still not working... (I am using [this page](https://www.bbc.com/news/world-us-canada-50831743) as an example to test. )
> Browser Type: Edge Chromiun
> Browser Version: 80.0.361.5 (Official build) dev (64-bit)

Thanks, in my environment(Ubuntu chrome), the page you mentioned worked well. I will try to find the reason using Edge browser later.

**Comment by Mark-Fenng** [comment]
This is truly a bug caused by the difference of extension API between chrome and Edge Chromium.

**Comment by raysworld** [comment]
> This is truly a bug caused by the difference of extension API between chrome and Edge Chromium.
> But I'm sorry that a new version may be published one or more months later. If you really need this function, I will post a zip file here and you can install it manually.

Thanks for your message and reply. At the beginning I thought this plugin is specially written for Edge... So will there be a future fix for this bug for Edge Chromium?

**Comment by Mark-Fenng** [comment]
> > This is truly a bug caused by the difference of extension API between chrome and Edge Chromium.
> > But I'm sorry that a new version may be published one or more months later. If you really need this function, I will post a zip file here and you can install it manually.
> 
> Thanks for your message and reply. At the beginning I thought this plugin is specially written for Edge... So will there be a future fix for this bug for Edge Chromium?

Sure, our extension on all of these browsers will be updated. (the name  "edge" has different meaning )
Your language setting of your Edge Chromium is English, right?
Maybe this bug also related to the language setting.
Did you get this exntension on microsoft store?(just out of curiosity)

**Comment by Mark-Fenng** [comment]
@raysworld 
I tried to fix this bug and posted
 a zip file below.
Would you like to test it and tell us whether the problem has been fixed or not
[edge_translate_fix.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/3979025/edge_translate_fix.zip)

**Comment by raysworld** [comment]
> @raysworld
> I tried to fix this bug and posted
> a zip file below.
> Would you like to test it and tell us whether the problem has been fixed or not
> [edge_translate_fix.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/3979025/edge_translate_fix.zip)

Hi Mark-Fenng,
many thanks for your quick response. I just tested the zip file and it works like a charm :-)
Thanks again👍👍👍
