### ISSUE TITLE
谷歌翻译对中国大陆停止服务，要使用谷歌翻译需要将 `*.googleapis.com` 添加到代理名单！

### ISSUE THREAD

**Issue by Githubbili** [EdgeTranslate/EdgeTranslate#400]
**describe the bug描述问题**

**全部翻译都失效了**

**steps to reproduce复现步骤**

**右键点击【翻译】，侧边栏的翻译显示无网络**

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

**个人电脑**

_browser name 浏览器类型 [e.g. chrome, firefox]_

**edge  105.0.1343.50

侧边翻译 版本2.3.0**

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/21958998/192930981-2ba7eb9f-9e04-4904-9d55-fa088600f035.png)

![image](https://user-images.githubusercontent.com/21958998/192930852-6410bcac-5493-40a4-b970-3c46ebe208a4.png)

**Comment by Dr-Gavin** [comment]
我也是这个问题，但是腾讯翻译可以用。其他引擎都不行。

**Comment by allen19980114** [comment]
这几天我也是这样

**Comment by Yingjie-Deng** [comment]
同样的问题，目前只有必应翻译和腾讯翻译可以用。

**Comment by ruficol** [comment]
+1 我也这样 好烦

**Comment by gonboy** [comment]
最近一直这样子

**Comment by wjzzd** [comment]
只需要在梯子内将 translate.googleapis.com 设为走代理（PROXY）就可以了

**Comment by jianbinlu225** [comment]
我也这样 但是edge就莫名奇妙可以用 很奇怪

**Comment by ruficol** [comment]
> 只需要在梯子内将 translate.googleapis.com 设为走代理（PROXY）就可以了

请教怎么设置呢 谢谢

**Comment by wqcblog** [comment]
国际版谷歌翻译已经无法直接访问了,cn结尾的可以访问，我修改成cn的域名，文件如下
[Edgetranslate.zip](https://github.com/EdgeTranslate/EdgeTranslate/files/9690107/Edgetranslate.zip)

**Comment by bigknife5th** [comment]
Google发言人通过电子邮件告诉TechCrunch，该公司已经停止了Google翻译在中国大陆的服务，原因是"因为使用率低"。

**Comment by hopingpeople** [comment]
> 

之前一直配的google.com，找了半天这个url，感谢感谢

**Comment by hopingpeople** [comment]
> 只需要在梯子内将 translate.googleapis.com 设为走代理（PROXY）就可以了

感谢，一直没找到这个url

**Comment by MWKrystal** [comment]
> 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可；
> 
> @SETLOCAL enabledelayedexpansion @echo off
> 
> set "source_domain=google.cn" set "target_domain=translate.googleapis.com"
> 
> set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> 
> for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a set "old_rule=null" set "new_rule=%ip% %target_domain%"
> 
> for /f "tokens=*" %%i in ('type %hosts_file%') do ( set "line=%%i" :: Retrieve the rule If the target domain has been exists in the line. if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i" )
> 
> if not "%old_rule%"=="null" ( if not "%old_rule%"=="%new_rule%" ( echo Deleting the rule "%old_rule%" echo Adding the rule "%new_rule%" for /f "tokens=_" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do ( set "rule=%%i" set "rule=!rule:_]=!" if "%old_rule%"=="!rule!" set "rule=%new_rule%" >>%hosts_file% echo(!rule! ) ) else ( echo The rule already exists, nothing to do. ) ) else ( echo Adding the rule "%new_rule%" echo.>>%hosts_file% echo.>>%hosts_file% echo # Fix Google Translate CN>>%hosts_file% echo %new_rule%>>%hosts_file% )
> 
> echo Done. pause

Thanks！

**Comment by ice-SY15** [comment]
> 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可；
> 
> ```batchfile
> @setlocal enabledelayedexpansion
> @echo off
> 
> set "source_domain=google.cn"
> set "target_domain=translate.googleapis.com"
> 
> set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> 
> for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a
> set "old_rule=null"
> set "new_rule=%ip% %target_domain%"
> 
> for /f "tokens=*" %%i in ('type %hosts_file%') do (
>     set "line=%%i"
>     :: Retrieve the rule If the target domain has been exists in the line.
>     if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i"
> )
> 
> if not "%old_rule%"=="null" (
>     if not "%old_rule%"=="%new_rule%" (
>         echo Deleting the rule "%old_rule%"
>         echo Adding the rule "%new_rule%"
>         for /f "tokens=*" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do (
>             set "rule=%%i"
>             set "rule=!rule:*]=!"
>             if "%old_rule%"=="!rule!" set "rule=%new_rule%"
>             >>%hosts_file% echo(!rule!
>         )
>     ) else (
>         echo The rule already exists, nothing to do.
>     )
> ) else (
>     echo Adding the rule "%new_rule%"
>     echo.>>%hosts_file%
>     echo.>>%hosts_file%
>     echo # Fix Google Translate CN>>%hosts_file%
>     echo %new_rule%>>%hosts_file%
> )
> 
> echo Done.
> pause
> ```

赞，操作后，谷歌网页翻译可以用了，谢谢

**Comment by Gaia9527** [comment]
> 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可;
> 
> ```batchfile
> @setlocal enabledelayedexpansion
> @echo off
> 
> set "source_domain=google.cn"
> set "target_domain=translate.googleapis.com"
> 
> set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> 
> for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a
> set "old_rule=null"
> set "new_rule=%ip% %target_domain%"
> 
> for /f "tokens=*" %%i in ('type %hosts_file%') do (
>     set "line=%%i"
>     :: Retrieve the rule If the target domain has been exists in the line.
>     if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i"
> )
> 
> if not "%old_rule%"=="null" (
>     if not "%old_rule%"=="%new_rule%" (
>         echo Deleting the rule "%old_rule%"
>         echo Adding the rule "%new_rule%"
>         for /f "tokens=*" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do (
>             set "rule=%%i"
>             set "rule=!rule:*]=!"
>             if "%old_rule%"=="!rule!" set "rule=%new_rule%"
>             >>%hosts_file% echo(!rule!
>         )
>     ) else (
>         echo The rule already exists, nothing to do.
>     )
> ) else (
>     echo Adding the rule "%new_rule%"
>     echo.>>%hosts_file%
>     echo.>>%hosts_file%
>     echo # Fix Google Translate CN>>%hosts_file%
>     echo %new_rule%>>%hosts_file%
> )
> 
> echo Done.
> pause
> ```

谢谢！谷歌翻译终于又可以用了！

**Comment by hzbtbp** [comment]
厉害呀！又可以使用了，大神，牛， 牛。好人一生平安！

**Comment by yunchengwang21** [comment]
> 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可；
> 
> ```batchfile
> @setlocal enabledelayedexpansion
> @echo off
> 
> set "source_domain=google.cn"
> set "target_domain=translate.googleapis.com"
> 
> set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> 
> for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a
> set "old_rule=null"
> set "new_rule=%ip% %target_domain%"
> 
> for /f "tokens=*" %%i in ('type %hosts_file%') do (
>     set "line=%%i"
>     :: Retrieve the rule If the target domain has been exists in the line.
>     if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i"
> )
> 
> if not "%old_rule%"=="null" (
>     if not "%old_rule%"=="%new_rule%" (
>         echo Deleting the rule "%old_rule%"
>         echo Adding the rule "%new_rule%"
>         for /f "tokens=*" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do (
>             set "rule=%%i"
>             set "rule=!rule:*]=!"
>             if "%old_rule%"=="!rule!" set "rule=%new_rule%"
>             >>%hosts_file% echo(!rule!
>         )
>     ) else (
>         echo The rule already exists, nothing to do.
>     )
> ) else (
>     echo Adding the rule "%new_rule%"
>     echo.>>%hosts_file%
>     echo.>>%hosts_file%
>     echo # Fix Google Translate CN>>%hosts_file%
>     echo %new_rule%>>%hosts_file%
> )
> 
> echo Done.
> pause
> ```

thanks!

**Comment by PhoenixZhong** [comment]
> 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可；
> 
> ```batchfile
> @setlocal enabledelayedexpansion
> @echo off
> 
> set "source_domain=google.cn"
> set "target_domain=translate.googleapis.com"
> 
> set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> 
> for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a
> set "old_rule=null"
> set "new_rule=%ip% %target_domain%"
> 
> for /f "tokens=*" %%i in ('type %hosts_file%') do (
>     set "line=%%i"
>     :: Retrieve the rule If the target domain has been exists in the line.
>     if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i"
> )
> 
> if not "%old_rule%"=="null" (
>     if not "%old_rule%"=="%new_rule%" (
>         echo Deleting the rule "%old_rule%"
>         echo Adding the rule "%new_rule%"
>         for /f "tokens=*" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do (
>             set "rule=%%i"
>             set "rule=!rule:*]=!"
>             if "%old_rule%"=="!rule!" set "rule=%new_rule%"
>             >>%hosts_file% echo(!rule!
>         )
>     ) else (
>         echo The rule already exists, nothing to do.
>     )
> ) else (
>     echo Adding the rule "%new_rule%"
>     echo.>>%hosts_file%
>     echo.>>%hosts_file%
>     echo # Fix Google Translate CN>>%hosts_file%
>     echo %new_rule%>>%hosts_file%
> )
> 
> echo Done.
> pause
> ```

管理员权限运行后，提示
Adding the rule "220.181.174.34 translate.googleapis.com"
拒绝访问。
拒绝访问。
拒绝访问。
拒绝访问。
Done.

**Comment by Windrain7** [comment]
> > 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可；
> > ```batchfile
> > @setlocal enabledelayedexpansion
> > @echo off
> > 
> > set "source_domain=google.cn"
> > set "target_domain=translate.googleapis.com"
> > 
> > set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> > 
> > for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a
> > set "old_rule=null"
> > set "new_rule=%ip% %target_domain%"
> > 
> > for /f "tokens=*" %%i in ('type %hosts_file%') do (
> >     set "line=%%i"
> >     :: Retrieve the rule If the target domain has been exists in the line.
> >     if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i"
> > )
> > 
> > if not "%old_rule%"=="null" (
> >     if not "%old_rule%"=="%new_rule%" (
> >         echo Deleting the rule "%old_rule%"
> >         echo Adding the rule "%new_rule%"
> >         for /f "tokens=*" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do (
> >             set "rule=%%i"
> >             set "rule=!rule:*]=!"
> >             if "%old_rule%"=="!rule!" set "rule=%new_rule%"
> >             >>%hosts_file% echo(!rule!
> >         )
> >     ) else (
> >         echo The rule already exists, nothing to do.
> >     )
> > ) else (
> >     echo Adding the rule "%new_rule%"
> >     echo.>>%hosts_file%
> >     echo.>>%hosts_file%
> >     echo # Fix Google Translate CN>>%hosts_file%
> >     echo %new_rule%>>%hosts_file%
> > )
> > 
> > echo Done.
> > pause
> > ```
> 
> 管理员权限运行后，提示 Adding the rule "220.181.174.34 translate.googleapis.com" 拒绝访问。 拒绝访问。 拒绝访问。 拒绝访问。 Done.

同样提示

**Comment by cool-delete** [comment]
> Adding the rule

详情看

**Comment by PandaLinks** [comment]
还是拒绝访问……

**Comment by sipoli007** [comment]
设置代理后还是无法进行翻译。

**Comment by ShitBro369** [comment]
又g了，那位大佬有别的法子

**Comment by puchizpc** [comment]
能否使用镜像网站呢？

**Comment by Drink-medicine** [comment]
> 没那么复杂，谷歌翻译api在大陆还可以正常使用，以下文本复制到txt，改txt为bat，管理员身份运行即可；
> 
> ```batchfile
> @setlocal enabledelayedexpansion
> @echo off
> 
> set "source_domain=google.cn"
> set "target_domain=translate.googleapis.com"
> 
> set "hosts_file=C:\Windows\System32\drivers\etc\hosts"
> 
> for /f "skip=4 tokens=2" %%a in ('"nslookup %source_domain% 2>NUL"') do set ip=%%a
> set "old_rule=null"
> set "new_rule=%ip% %target_domain%"
> 
> for /f "tokens=*" %%i in ('type %hosts_file%') do (
>     set "line=%%i"
>     :: Retrieve the rule If the target domain has been exists in the line.
>     if not "!line:%target_domain%=!"=="%%i" set "old_rule=%%i"
> )
> 
> if not "%old_rule%"=="null" (
>     if not "%old_rule%"=="%new_rule%" (
>         echo Deleting the rule "%old_rule%"
>         echo Adding the rule "%new_rule%"
>         for /f "tokens=*" %%i in ('type "%hosts_file%" ^| find /v /n "" ^& break ^> "%hosts_file%"') do (
>             set "rule=%%i"
>             set "rule=!rule:*]=!"
>             if "%old_rule%"=="!rule!" set "rule=%new_rule%"
>             >>%hosts_file% echo(!rule!
>         )
>     ) else (
>         echo The rule already exists, nothing to do.
>     )
> ) else (
>     echo Adding the rule "%new_rule%"
>     echo.>>%hosts_file%
>     echo.>>%hosts_file%
>     echo # Fix Google Translate CN>>%hosts_file%
>     echo %new_rule%>>%hosts_file%
> )
> 
> echo Done.
> pause
> ```

不行啊,还是只有腾讯翻译能用
