### ISSUE TITLE
chrome上使用出现网络错误，代码：0

### ISSUE THREAD

**Issue by jianbinlu225** [EdgeTranslate/EdgeTranslate#402]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
chrome上的插件无法使用，提示网络错误，包括所有的翻译网站；
edge上可以使用

**issue screenshot 问题截图**

![image](https://user-images.githubusercontent.com/66287345/193106465-e060a2f1-2c70-4a4c-8287-0a54f250261c.png)

**environment 使用环境**

_browser name 浏览器类型 chrome_

_browser version 浏览器版本  105.0.5195.127  _

_extension version 插件版本 2.3.0_

**Comment by ruficol** [comment]
+1

**Comment by three3suns** [comment]
我也遇到了这个问题，使用的是edge浏览器，网络是正常的，尝试过关闭扩展再启用，仍然无用

**Comment by nickyc975** [comment]
谷歌翻译的接口对大陆停止服务了，要使用的话需要将`*.googleapis.com`添加到代理名单。其他的翻译接口的问题我们很快会发布相应的更新修复。
