### ISSUE TITLE
使用有道网页翻译时鼠标点向译文时会显示原文并提示提交翻译意见，希望能取消这个设置，纯净看译文

### ISSUE THREAD

**Issue by authentic-zz** [EdgeTranslate/EdgeTranslate#406]
**describe feature功能描述**

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

**your solution 你的解决方案**

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
这个功能是由有道自己提供的，我们暂时不会去动。
