### ISSUE TITLE
希望 右上角小图标可以设置隐藏

### ISSUE THREAD

**Issue by FrontendStack** [EdgeTranslate/EdgeTranslate#41]
**功能描述**
右上角小图标可以设置隐藏

**使用场景**
![图片](https://user-images.githubusercontent.com/58390198/71553221-3f854f80-2a46-11ea-8aaa-38602ca93b57.png)

**Comment by Mark-Fenng** [comment]
可以设置隐藏，请在浏览器右上角的侧边翻译的图标处，右键后选择选项一栏，其中有相关的设置



---原始邮件---
发件人: "FrontendStack"<notifications@github.com&gt;
发送时间: 2019年12月29日(周日) 下午2:20
收件人: "EdgeTranslate/EdgeTranslate"<EdgeTranslate@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [EdgeTranslate/EdgeTranslate] 希望 右上角小图标可以设置隐藏 (#41)



功能描述
 右上角小图标可以设置隐藏
 
使用场景

**Comment by zigitn** [comment]
版本 1.7.1， 找不到隐藏选项
