### ISSUE TITLE
网页翻译的选项没有了

### ISSUE THREAD

**Issue by arsoooo** [EdgeTranslate/EdgeTranslate#42]
1.7.0版本网页翻译的选项没有了，2019-12-28更新的
目前只有复制粘贴翻译、互译模式，原来的google和网易翻译选项消失了
另外之前使用的时候google翻译不一定能显示，有的时候网易又不能显示

**Comment by nickyc975** [comment]
我们去掉了右上角popup里的网页翻译入口，你可以在页面上右键，然后在侧边翻译那一栏里边找到网页翻译入口。

Google网页翻译在某些页面上确实无法使用，这是那些网页设置的，我们暂时没办法。有道翻译无法使用的话，可以提供具体的网页吗？

**Comment by arsoooo** [comment]
我试了一下，右键没有侧边翻译一栏呀，我截图了您看一下
![图片](https://user-images.githubusercontent.com/41410134/71557579-fa334300-2a82-11ea-84de-453601e3e0d7.png)
![图片](https://user-images.githubusercontent.com/41410134/71557581-fef7f700-2a82-11ea-9018-b5cc63159780.png)
另外，关于网易翻译不能使用的网页，我忘记了，遇到的时候会在这里回复

**Comment by Mark-Fenng** [comment]
我看了下，火狐不知是什么问题，有时候还真没有选项，看来是我们对火狐不够了解，下个版本我们尽快解决这个问题
