### ISSUE TITLE
由于谷歌翻译失效扩展启用时打开部分网页无法加载出来

### ISSUE THREAD

**Issue by Haurchefant-G** [EdgeTranslate/EdgeTranslate#423]
**describe the bug描述问题**

在扩展开启时，打开部分网页直接无法加载出来，禁用插件后就可以加载出来

**testable address 出现问题的网址**

https://www.microsoftedgeinsider.com/zh-cn/

**steps to reproduce复现步骤**

扩展开启状态下直接打开该网站

**issue screenshot 问题截图**

![1](https://user-images.githubusercontent.com/40447255/194569622-f024d683-8edf-4372-bad0-447e792eda4e.png)

**environment 使用环境**

Microsoft Edge
版本 106.0.1370.37

插件版本 2.4.0

**Comment by Mark-Fenng** [comment]
多谢反馈

**Comment by nickyc975** [comment]
我在最新版本的edge上无法复现这个问题，请升级edge后确认一下。
