### ISSUE TITLE
2.4.0版本有道网页翻译卡在0%

### ISSUE THREAD

**Issue by mfjl1212** [EdgeTranslate/EdgeTranslate#425]
2.4.0版本有道网页翻译卡在0%

**Comment by anmutoo** [comment]
我也有这种情况，请问如何解决

**Comment by qingyiay** [comment]
> 2.4.0版本有道网页翻译卡在0%

同问

**Comment by gaotianxiong** [comment]
![image](https://user-images.githubusercontent.com/86526765/195832912-1600a708-e926-4ecd-bff8-d61e7244df56.png)
是的，网页使用有道翻译无效。google翻译可正常使用。

**Comment by Mark-Fenng** [comment]
似乎是有道网页翻译停止服务了

**Comment by prerequisites** [comment]
点击上方有道的图标，跳转的网页无法打开
![image](https://user-images.githubusercontent.com/26115836/200167484-d6755bce-1053-49e3-b001-3b70052e5733.png)

**Comment by a51095** [comment]
有道翻译，能修复一下吗

**Comment by a51095** [comment]
有道的页面翻译可以修复一下吗，很喜欢这个功能❤️
