### ISSUE TITLE
内置pdf问题

### ISSUE THREAD

**Issue by geshichuangdi** [EdgeTranslate/EdgeTranslate#426]
本地edge浏览器, 安装侧边翻译插件, 打开pdf预览时, 使用侧边翻译内置pdf查看器, 网络请求谷歌插件失败(本地未翻墙), 禁用侧边翻译内置pdf查看器, 采用edge内置pdf查看器, 问题解决

**Comment by nickyc975** [comment]
你是说在Edge上使用插件内置的PDF查看器时无法使用谷歌翻译吗？

**Comment by geshichuangdi** [comment]
你理解错了

**Comment by geshichuangdi** [comment]
半年前的版本了,  侧边翻译插件, 在edge浏览器使用, 预览pdf时, 插件会发送网络请求, 访问chrome商店的资源, 由于本地未翻墙, 故请求失败, 预览pdf也就失真了

**Comment by nickyc975** [comment]
很奇怪，扩展的PDF查看器是不需要访问网络的，一定有什么地方搞错了。现在还有这个问题吗？会不会跟你看的PDF文件有关？

**Comment by geshichuangdi** [comment]
我刚试了一下  可以正常显示了  不过有一个新问题  pdf预览时, 主题颜色是跟随edge系统设置联动的  也就是说  我把edge的整体外观设置为深色, 同时我打开pdf也变成深色的了, 这点体验不好, 还是希望pdf预览是原来的颜色
![image](https://user-images.githubusercontent.com/44060829/229035228-0ddb1580-8858-47df-aaea-bec5a1986a80.png)
![image](https://user-images.githubusercontent.com/44060829/229035337-89c5b131-9d66-4fe7-8537-861efbd6c300.png)
![image](https://user-images.githubusercontent.com/44060829/229035418-940e6301-d09f-495a-af84-c5c46714f73d.png)

**Comment by nickyc975** [comment]
点击PDF查看器右上角的"A"按钮可以切换PDF的显示模式。

**Comment by geshichuangdi** [comment]
谢谢, 祝越来越好
