### ISSUE TITLE
侧边翻译

### ISSUE THREAD

**Issue by ice-SY15** [EdgeTranslate/EdgeTranslate#427]
**describe the bug描述问题**
谷歌和有道翻译都无法使用，有道一直显示正在翻译，进度却为0；谷歌按照（https://github.com/EdgeTranslate/EdgeTranslate/issues/400）尝试了，还是不能使用，不知道是不是操作不对，可以出个修改流程吗，谢谢。

**testable address 出现问题的网址**
edge浏览器上的网页翻译情况都相同
例如：
https://www.researchgate.net/
https://theoldreader.com/folders/5d2dc85fc70bc216b8000c7a

**steps to reproduce复现步骤**
1. https://www.researchgate.net/  
2. 点击有道网页翻译或谷歌  
4. 翻译无进展

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/63955608/195474762-72001a04-7407-4219-ad18-2d1616d3cc31.png)

**environment 使用环境** 

校园网

_browser name 浏览器类型 [e.g. chrome, firefox]_ edge

_browser version 浏览器版本 [e.g. 22]_     106.0.1370.42

_extension version 插件版本 [e.g. 2.0.0]_2.4.0

**other information 其他信息**

插件很好用，希望还能接着用，谢谢。

**Comment by Mark-Fenng** [comment]
似乎是有道网页翻译停止服务了
