### ISSUE TITLE
对 html 标签没有进行过滤

### ISSUE THREAD

**Issue by zigitn** [EdgeTranslate/EdgeTranslate#43]
**描述问题**
对html标签没有进行过滤或者处理, 导致翻译结果会被html标签影响

**复现步骤**

- `翻译<strong><i>这段话, 结果会变斜体+粗体`
- `(翻译结果语言非中文时)翻译<input type='button' onclick="console.log(1)" value="显示警告框" />这个标签, 结果中会出现按钮, 点击可以在控制台输出1`

等等

**使用环境**
chrome beta  80.0.3987.16 (64 位)

插件版本 1.7.0

**Comment by nickyc975** [comment]
这个确实是我们没考虑到，感谢反馈！
