### ISSUE TITLE
能不能加一个快捷键对选中的文本进行翻译？

### ISSUE THREAD

**Issue by ztoiax** [EdgeTranslate/EdgeTranslate#44]
我通过vim插件，在浏览器基本都是键盘操作。能不能加一个快捷键对选中的文本进行翻译？

**Comment by nickyc975** [comment]
这个快捷键是支持的，只不过需要用户自己设置。在浏览器的快捷键设置里就可以找到。

**Comment by Mark-Fenng** [comment]
这个快捷键已经有了，可以在快捷键设置处自己制定
具体操作：右键点击浏览器右上角的侧边翻译标志，在弹出选项中点击快捷键设置进入快捷键设置页面，在这里你可以对侧边翻译的所有快捷键进行自定义
