### ISSUE TITLE
谷歌

### ISSUE THREAD

**Issue by yinchen1233** [EdgeTranslate/EdgeTranslate#442]
**describe the bug描述问题**
谷歌翻译无法使用怎么解决
![image](https://user-images.githubusercontent.com/68657762/196579551-d764df34-1cbf-4dca-8f20-f9129f9f5a68.png)

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by FlounderTheLifeguard** [comment]
所有网页都不能使用谷歌翻译，之前按前几个帖子修改过谷歌的源
![image](https://user-images.githubusercontent.com/42027568/197382254-82f35361-0aa7-47d2-9d05-4cee8a7ea90e.png)
使用环境
edge
版本
![image](https://user-images.githubusercontent.com/42027568/197382301-e9830a53-2ab9-4e30-a6e5-bbfd3758541d.png)
插件版本2.4.0

**Comment by Mark-Fenng** [comment]
没有更好的办法了，可以参考https://github.com/EdgeTranslate/EdgeTranslate/issues/400，或者考虑使用VPN

**Comment by Cc-12342234** [comment]
> 没有更好的办法了，可以参考[https://github.com/EdgeTranslate/EdgeTranslate/issues/400，或者考虑使用VPN](https://github.com/EdgeTranslate/EdgeTranslate/issues/400%EF%BC%8C%E6%88%96%E8%80%85%E8%80%83%E8%99%91%E4%BD%BF%E7%94%A8VPN)

您好 请问我用了VPN也用不了edgetranslate   直接进谷歌翻译网站是可以的  请问是哪里没设置对吗

**Comment by Mark-Fenng** [comment]
应该是代理(proxy)的设置有问题，需要将*.googleapis.com加入代理的名单中
