### ISSUE TITLE
希望在设置里增加一个点击侧边翻译图标就直接进行页面翻译的设置。

### ISSUE THREAD

**Issue by ifenge** [EdgeTranslate/EdgeTranslate#45]
**功能描述**

在设置里增加一个点击侧边翻译图标就直接进行页面翻译的设置。可以设置默认翻译引擎。

**使用场景**

浏览外文页面时

**你的解决方案**

右键选择侧边翻译，点击使用谷歌翻译此页。多了几个步骤有点麻烦。

**替代方案**

没有

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
这个我们正在做，之后会有网页翻译快捷键等。
