### ISSUE TITLE
划词翻译弹窗被edge自带功能弹窗覆盖

### ISSUE THREAD

**Issue by wsjwqq** [EdgeTranslate/EdgeTranslate#450]
**describe the bug描述问题**
   划词翻译弹窗与edge浏览器"选择文本时的微型菜单"的弹窗重合

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/57908320/197474119-88c754f6-e254-4952-8f70-04e268f87661.png)

_browser name 浏览器类型 [edge]_
_browser version 浏览器版本 [106.0.1370.52 (正式版本) (64 位)]_
_extension version 插件版本 [2.4.0]_

**Comment by Mark-Fenng** [comment]
可以在设置页面调整划词翻译弹窗的位置
<img width="894" alt="image" src="https://user-images.githubusercontent.com/27533910/197903676-d3578b05-b3ef-413e-ba54-fa77ae203f4b.png">
