### ISSUE TITLE
使用chrome打开本地pdf文件时不能使用快捷键调用翻译

### ISSUE THREAD

**Issue by gglin001** [EdgeTranslate/EdgeTranslate#46]
**描述问题**

如题

**出现问题的网址**

本地pdf文件, 使用chrome自带的pdf阅读器, 未使用这个插件的build-in pdf 阅读器

**复现步骤**

在chrome浏览器 插件管理 -> 快捷键管理 处设置"Translate selected text
"快捷键为某一快捷键, 如(ALT+T), 在网页文件中选择部分文字, 快捷键可以正常使用, 但在本地pdf文件中无法使用, 使用右键菜单翻译正常.

**使用环境**

Ubuntu 18.04.03 64bit chrome78

_插件版本 [e.g. 1.2.0]_

1.7.1, 以往的版本也有此问题.

**Comment by nickyc975** [comment]
在chrome自带的pdf阅读器里没办法是监听快捷键的，这个没办法。
