### ISSUE TITLE
自动发音和翻译

### ISSUE THREAD

**Issue by Jimmy-Ljm** [EdgeTranslate/EdgeTranslate#47]
希望可以在设置中增加自动发音的开关 可以自动播放单词读音

希望单词定义中的翻译可以有中文版本的 便于初学者理解

您开发的这个插件对我帮助很大 以上是一点点小小的建议 谢谢

**Comment by nickyc975** [comment]
1. 自动发音我们会考虑加上的；
2. 单词定义中的翻译是谷歌翻译直接返回的，我们不好改，你可以尝试自己手动选中翻译；
3. 感谢使用插件！

**Comment by nickyc975** [comment]
我们已经对文本朗读功能做了一些优化，应该可以替代你想要的自动发音功能了，详细的请查看这个issue: #74 。谢谢你的建议！
