### ISSUE TITLE
部分网页翻译，图标未正常显示，点击无反应，右键菜单是可以进行翻译的

### ISSUE THREAD

**Issue by OneKenneth** [EdgeTranslate/EdgeTranslate#484]
如图:
![image](https://user-images.githubusercontent.com/75555787/207253489-8bd6c439-e47d-4539-9880-94430eb8c8c8.png)

**Comment by shelllee** [comment]
补充一张Github网页的翻译图标图：

![image](https://user-images.githubusercontent.com/11704124/211146201-c2607b0c-4119-47df-bafd-b8dbcf290ec9.png)

**Comment by nickyc975** [comment]
在 https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.40.0.txt 页面上可以复现此问题，请 @YunFeng0817 检查一下。

**Comment by simear2004** [comment]
> 在 https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.40.0.txt 页面上可以复现此问题，请 @YunFeng0817 检查一下。
同样的问题
