### ISSUE TITLE
当使用划词翻译功能时，出现的小图标出现bug

### ISSUE THREAD

**Issue by liaosishui** [EdgeTranslate/EdgeTranslate#485]
**describe the bug描述问题**

当使用划词翻译时，出现的小图标出现bug，影响使用

**steps to reproduce复现步骤**

当调整翻译结果内容框大小后时而会出现此bug

**issue screenshot 问题截图**

![image](https://user-images.githubusercontent.com/93067563/207762958-054fd3a7-cfaa-4a3c-9799-25072d12c0cc.png)

**environment 使用环境**

Windows 10 专业版

** 浏览器类型 **

Microsoft Edge
版本 108.0.1462.46 (正式版本) (64 位)

**插件版本 **

侧边翻译
大小: 6.3 MB版本2.4.0

**other information 其他信息**

用指定的PDF编辑器打开PDF文件也同样无法使用全页翻译

**Comment by nickyc975** [comment]
与 #504 应该是同一个问题，将在下个版本中被修复。
