### ISSUE TITLE
能否添加点击页面后，或者按 exit 按钮关闭窗口

### ISSUE THREAD

**Issue by sishen654** [EdgeTranslate/EdgeTranslate#486]
**describe feature功能描述**

1-点击一下页面窗口关闭
2-或者点击 exit 按钮关闭窗口（可以自定义快捷键）

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

关闭窗口不需要去点击 ❌ 按钮，因为窗口会遮挡到文字或者其他部分，每次翻译后需要去点击关闭窗口，很麻烦

**Comment by nickyc975** [comment]
点击窗口右上角三个按钮里边中间的那个图钉按钮可以切换翻译框的固定模式。到图钉为倾斜状态时，点击翻译框外部即可关闭翻译框。
