### ISSUE TITLE
网页翻译没有用

### ISSUE THREAD

**Issue by 1592363624** [EdgeTranslate/EdgeTranslate#488]
**describe the bug描述问题**

任何网页都是显示翻译完成，其实并没有翻译

**testable address 出现问题的网址**

https://www.nexusmods.com/

**Comment by maoxiaomeng2021** [comment]
+1

**Comment by gaotianxiong** [comment]
对于google网页翻译，开始时无反应，一段时间后会弹出错误。
![image](https://user-images.githubusercontent.com/86526765/224659488-a44c980a-321c-40d5-ae0c-6fa1e3c67cfe.png)
对于有道网页翻译，会显示翻译已完成，但没有翻译。

**Comment by nickyc975** [comment]
谷歌的页面翻译服务需要科学上网才能使用。
有道的页面翻译服务已经被关闭了，无法再使用，我们将在下个版本中将其移除。
