### ISSUE TITLE
添加开关和固定功能

### ISSUE THREAD

**Issue by Xerrors** [EdgeTranslate/EdgeTranslate#49]
**功能描述**

点击地址栏的图标的时候可以快速开关划词翻译

**使用场景**

有些时候我希望启用划词翻译，有些时候我不希望启用划词翻译。因为我多数情况下还是在浏览中文网站，多数情况下我划词就只是为了去复制，但是每次就会出现一个翻译的小图标，并不是很好看。

**你的解决方案**

比如这样👇
![mark](http://src.xerrors.fun/blog/20200207/dRRyl4TgMoLQ.png)

**替代方案**

替代方案就是到系统的拓展里面去启用和禁用拓展，不过太麻烦了，一般也就是忍一忍。

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
插件是支持添加网页黑名单的，右键点击浏览器右上角的侧边翻译图标就可以看到。

可以选择将当前网页加入黑名单或者将这个域名下的所有网页都加入黑名单。加入黑名单后在该网页上将无法使用翻译功能。
