### ISSUE TITLE
除了百度翻译接口，都出现了问题。

### ISSUE THREAD

**Issue by CynicalHeart** [EdgeTranslate/EdgeTranslate#494]
## 多数接口失效

开发人员您好，近期侧边翻译失效问题严重，特来此反馈问题，对同一段话翻译结果如下所示。

### 混合翻译

![image](https://user-images.githubusercontent.com/27052882/212555769-173e9eae-bde8-40e1-a29c-2a9926cafa80.png)
 
### 百度翻译

![image](https://user-images.githubusercontent.com/27052882/212555880-5836f76d-d837-4023-b5f2-3e5ac0905d78.png)

### 必应翻译

![image](https://user-images.githubusercontent.com/27052882/212555977-ac01f682-444c-42e4-9257-e4a3abbaac52.png)

### DeepL

![image](https://user-images.githubusercontent.com/27052882/212556009-c424d2a0-f565-4528-ade9-0646cd52862c.png)

### google

![image](https://user-images.githubusercontent.com/27052882/212556041-ae6e60ac-6879-4340-be4e-b97aa467dd47.png)

### 腾讯翻译

![image](https://user-images.githubusercontent.com/27052882/212556077-a0513457-bb9d-4d1a-877e-13039475250e.png)

---

- 测试时间截止至2023/1/16日；
- 测试谷歌翻译时已经修改过host文件；
- 必应翻译接口down的莫名其妙，明明国内是可以使用的；
- 腾讯翻译翻译结果**偶发**错误；

> 测试网址：[link](https://wiki.eclipse.org/JFaceSnippets)， 翻译了第一句话。

---

目前只有百度接口可以使用，**急切需要修复**。

**Comment by CynicalHeart** [comment]
补充信息：

- 使用浏览器 Edge （109.0.1518.52）
- 侧边翻译版本 2.4.0

**Comment by acqxi** [comment]
實際測試後，目前僅bing翻譯API失效

**Comment by CynicalHeart** [comment]
> 實際測試後，目前僅bing翻譯API失效

测试的网络环境不一致，在大陆内，Google和DeepL的接口长期失效，需要翻墙使用。

**Comment by NB-wo** [comment]
一样的问题，我用的是浏览器插件版vpn
像deepl，我需要亲自浏览器打开他的网站后，再使用侧边翻译就好了，每次打开浏览器都要这么弄一次。
即使这样大部分时候deepl翻译的速度会很慢，还是老老实实用百度翻译吧

**Comment by nickyc975** [comment]
谷歌翻译和DeepL翻译需要科学上网才能使用，目前无解。必应翻译的问题已修复，即将发布更新。
