### ISSUE TITLE
必应翻译错误

### ISSUE THREAD

**Issue by qpzer** [EdgeTranslate/EdgeTranslate#495]
网络错误！请检查您的网络连接。

错误代码: undefined

错误信息: "object null is not iterable (cannot read property Symbol(Symbol.iterator))"

错误操作: {"api":"bing","action":"detect","text":"one","from":null,"to":null}
![Snipaste_2023-01-16_08-59-32](https://user-images.githubusercontent.com/60294400/212577608-e92b3270-9a9f-4750-b1a8-5147973b4580.png)
![Snipaste_2023-01-16_09-00-19](https://user-images.githubusercontent.com/60294400/212577616-4dcfc159-e327-497e-a593-6de988675f6d.png)
![Snipaste_2023-01-16_09-00-45](https://user-images.githubusercontent.com/60294400/212577633-59f7737d-9707-4ebb-bc64-fa5f1e0aa544.png)

**Comment by yinhaoooo** [comment]
我跟你遇到同样的问题。
