### ISSUE TITLE
典型例句中的样式丢失问题

### ISSUE THREAD

**Issue by LTHPKBTE** [EdgeTranslate/EdgeTranslate#50]
**描述问题**
翻译单个英文单词时，有时会带有典型例句一栏，此栏通常加粗翻译单词，但在此插件中的样式丢失了
例如：翻译write  然后去找典型例句一栏，句子中会出现类似 to <b>write</b> data to a disk 的样式代码
**问题截图**
![TIM图片20200212221346](https://user-images.githubusercontent.com/53574505/74342930-3d543600-4de5-11ea-8f92-e760efd08223.png)

**使用环境**
_FireFox72.0.2(64Bit)_
_插件版本1.7.1_

**Comment by nickyc975** [comment]
已知问题，我们会抽时间修复的，感谢反馈。
