### ISSUE TITLE
在阅读PDF过程中，添加文字后保存文件，文字会变成乱码

### ISSUE THREAD

**Issue by 090010** [EdgeTranslate/EdgeTranslate#501]
**描述bug描述问题**在阅读PDF的过程中，添加文字后保存文件，文字会变得乱七八糟_描述你遇到的问题请在这里详细描述你遇到的问题，如问题的表现形式，对你造成的影响有那些？

**可测试的地址 问题发生的URL**。

_留给我们一个可测试的地址（可选） 如果问题只出现在某些页面上，请在这里给出该页面的链接

**重现的步骤**

_描述重现的步骤 请在这里给出重现问题的步骤

**问题截图 问题截图**

如果可能的话，最好给出一个问题的截图（注意隐藏你的个人信息）_。

**environment 使用环境**

_告诉我们你的环境信息，例如：在这里给出你的环境，例如：。_

浏览器名称 浏览器类型[例如：Chrome, firefox]_

浏览器版本 浏览器版本[例如：22]_

_extension版本 插件版本[如2.0.0]_

**其他信息 其他信息**

_其他信息（可选） 如果有任何其他相关信息，请在此添加_。

**Comment by nickyc975** [comment]
与 #441 重复。
