### ISSUE TITLE
弹出的翻译按钮显示不正确问题

### ISSUE THREAD

**Issue by Olimiya** [EdgeTranslate/EdgeTranslate#504]
**describe the bug描述问题**

在浏览网页时，选中文字会弹出翻译按钮。但在某个时间以后（以前是正常的），弹出的按钮显示很奇怪。似乎多了右侧和底部的滚动条？导致需要翻译时，点击图标必须点击非滚动条区域的按钮（大概占弹出图标的1/4大小）。就导致进行翻译的交互操作困难了许多。

**testable address 出现问题的网址**

所有网页都一样。

**steps to reproduce复现步骤**

在一个网页中选择文字，自动弹出翻译按钮，按钮图标显示不正确。
**issue screenshot 问题截图**

![image](https://user-images.githubusercontent.com/35156329/219530191-d44337f0-71e7-41d7-b4ab-1cd3fec4aa86.png)

**environment 使用环境**

Microsoft Edge
版本 110.0.1587.46 (正式版本) (64 位)
插件版本：版本2.4.0

**other information 其他信息**

插件非常好用！感谢开发和维护！
如果能对我的问题做出反馈，我会非常感激！

**Comment by frlite** [comment]
同样的问题，希望可以修复，感谢开发者的辛苦付出~

**Comment by MuNitCat** [comment]
我也是同样的问题 希望能修复一下，现在不管是哪个网站我都是这样了

**Comment by MuNitCat** [comment]
修复方法
`EdgeTranslate\packages\EdgeTranslate\src\content\select\select.js`
给弹出的iframe的html标签添加  `overflow: "hidden" `属性
```js
const CleanStyle = {
      padding: 0,
      margin: 0,
      border: "none",
      overflow: "hidden",
};
```

**Comment by frlite** [comment]
我找到了，我的路径是
 `C:\Users\<你的用户名>\AppData\Local\Microsoft\Edge\User Data\Profile 1\Extensions\bfdogplmndidlpjfhoijckpakkdjkkil\2.4.0_0\content\select\select.js` 
 供参考
