### ISSUE TITLE
YouTube翻译不正常

### ISSUE THREAD

**Issue by mobzila** [EdgeTranslate/EdgeTranslate#505]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
YouTube展开的评论无法显示
**testable address 出现问题的网址**https://www.youtube.com/watch?v=5sN7B0TincY
https://www.youtube.com/watch?v=-tKVN2mAKRI

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**
打开链接，启用全文翻译

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**
![image](https://user-images.githubusercontent.com/91730585/219687637-8963bf19-b288-4e8d-a8d5-bbeea7091fca.png)
![image](https://user-images.githubusercontent.com/91730585/219688340-fb3d0f80-5afb-42bc-8daa-b2fcd2543d93.png)

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**
_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：win10pro 22h2_

_browser name 浏览器类型 edge  110.0.1587.49

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 9.2.2_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
问题无法复现。
