### ISSUE TITLE
取消翻译和翻译此页,集成进一个快捷键.

### ISSUE THREAD

**Issue by thomasTAT** [EdgeTranslate/EdgeTranslate#506]
**describe feature功能描述**
希望取消翻页和翻页此页,的快捷键可以集成在一起,这样就不用占用两个快捷键了.

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**
先用快捷键翻译网页,找到自己需要看的部分. 找到之后机器翻译不准,的时候用快捷键切换回原文.

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_
看技术东西
**your solution 你的解决方案**
翻译此页和取消翻译,分别设置两个快捷键.

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**
同类产品: https://github.com/FilipePS/Traduzir-paginas-web 但edge上会被莫名强制卸载.
https://chrome.google.com/webstore/detail/%E8%85%BE%E8%AE%AF%E7%BF%BB%E8%AF%91/lkjkfecdnfjopaeaibboihfkmhdjmanm?hl=zh-CN 苏   速度感人.

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

谢谢你开发了这款扩展,好人一生平安.

**Comment by thomasTAT** [comment]
还有来回翻译切换,网页的位置自己会越挪越上.

**Comment by nickyc975** [comment]
翻译选中的文本和翻译整个页面是两个相互独立的功能，不应该被合并到一起。
