### ISSUE TITLE
必应翻译和DeepL全部显示网络错误

### ISSUE THREAD

**Issue by evanliu3594** [EdgeTranslate/EdgeTranslate#508]
**describe the bug描述问题**
不管开没开代理
必应翻译以及DeepL均显示网络错误

**testable address 出现问题的网址**

全部

**steps to reproduce复现步骤**

打开翻译窗口，输入单词，点击翻译，切换翻译引擎

**issue screenshot 问题截图**

![image](https://user-images.githubusercontent.com/55047262/220571859-192b3b14-4156-40d8-831f-27fc36466d95.png)

**environment 使用环境**

Edge 110.0.1587.50
插件版本2.4.0
Win10 22H2
开关代理都一样

**Comment by yuanyuan19** [comment]
我遇到了和你一样的问题
