### ISSUE TITLE
当我一次划太多单词的时候，它就不能使用了，我确定不是网络的问题。内容如下：“网络错误！请检查您的网络连接。  错误代码: undefined  错误信息: undefined”

### ISSUE THREAD

**Issue by yuanyuan19** [EdgeTranslate/EdgeTranslate#515]
**describe the bug描述问题**

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_

**testable address 出现问题的网址**

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by yuanyuan19** [comment]
![QQ截图20230314142242](https://user-images.githubusercontent.com/120552623/224913503-73f2e34e-79a7-4d6b-8ec6-c1f0b47149df.png)
我也不是很明白如何稳定触发。你可以试试看一次划太多的句子，但是这并不是充要条件

**Comment by nickyc975** [comment]
应该是网络问题，谷歌翻译虽然有文本长度限制，但是应该没有这么短。可以检查一下网络或者尝试一下其他翻译接口。
