### ISSUE TITLE
无法翻译此页面

### ISSUE THREAD

**Issue by narulmcto** [EdgeTranslate/EdgeTranslate#525]
https://lrepacks.net/page/2/

**Comment by YunFeng0817** [comment]
感谢反馈，我查看了一下，应该是因为原页面已经内置了一个谷歌网页翻译
<img width="383" alt="image" src="https://github.com/EdgeTranslate/EdgeTranslate/assets/27533910/5bfd68ca-f71d-451e-b4bc-1fdbd95b977e">
所以我们的网页翻译就无法使用了

**Comment by narulmcto** [comment]
邮件已收到，我会尽快查看
