### ISSUE TITLE
Incorrect display of the interface when scaling text in Windows, the problem is observed in the Opera browser.

### ISSUE THREAD

**Issue by skorpions2000** [EdgeTranslate/EdgeTranslate#528]
When selecting text, if global text scaling is configured in Windows in the Opera browser (any version), the pop-up circle - button is displayed incorrectly with an excessive scrollbar.
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/11683786/fc54a19a-73dc-45a0-8b2e-51610b9c8d3a)

**Comment by YunFeng0817** [comment]
Thanks for your report! This will be fixed by the new release v2.4.1.
Duplicated with #504
