### ISSUE TITLE
DeepL selection translate no longer works

### ISSUE THREAD

**Issue by dogheartedly** [EdgeTranslate/EdgeTranslate#529]
**DeepL Translation via text selection no longer works**

Using DeepL translate via text select leads to an error message with error code 504. This does not happen with any other translation source.

**steps to reproduce复现步骤**

1. Select text
2. Click pop up translate button
3. Wait around 7 seconds
4. Error popup in the box instead of translation

**issue screenshot 问题截图**
Gyazo link:
[Reproduce (gif)](https://gyazo.com/2694b69a3d4466a2095efca1f0785f17)
[Error message](https://gyazo.com/3e956d359e7a4e1a226279b21c9b0d83)

**environment 使用环境**
Windows 10 Home 22H2 (probably irrelevant but just in case)
Firefox v113.0.1
EdgeTranslate v2.4.0

**Comment by RomanAverin** [comment]
Same issue

**Comment by RomanAverin** [comment]
Network error! Please check your network connection.
Error code: 504
Error message: "Wait result timeout!"
