### ISSUE TITLE
AutoTranslation of  Dutch

### ISSUE THREAD

**Issue by wimorrison** [EdgeTranslate/EdgeTranslate#53]
I find that this extension doesn't recognise Dutch automatically and I have to tell it to translate the page. It works well for auto-translating German, French and Spanish to English though :)

**Comment by Mark-Fenng** [comment]
I'm sorry that the function(automatically recognising language) is impletemented by Google Translate so we can't help a lot here.
You'd better tell the language setting to the extension so that the translation result would be more acurrate.
