### ISSUE TITLE
在个别网页上，翻译图标显示Bug

### ISSUE THREAD

**Issue by zhaopuyaoshishabi** [EdgeTranslate/EdgeTranslate#538]
**1、describe the bug描述问题**

目前，我在IEEE的网站上阅读文献时候出现图标显示Bug。比如，
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/34957847/558d1d87-3369-4ab1-88b9-cc21197ee2f0)

**2、testable address 出现问题的网址**

https://ieeexplore.ieee.org/abstract/document/9669061

**3、steps to reproduce复现步骤**

1、划出句子

**4、environment 使用环境**

Microsoft Edge 版本 114.0.1823.82 (正式版本) (64 位)

侧边翻译 2.4.0

**Comment by nickyc975** [comment]
此问题已修复，感谢反馈。
