### ISSUE TITLE
在Microso Edge上初次使用或变更设置后，不显示翻译

### ISSUE THREAD

**Issue by kimlym** [EdgeTranslate/EdgeTranslate#54]
**问题**
在Edge上使用第一次或者重选设置后，会出现不显示中文翻译的情况。实测把自动检测语言改成英语后，翻译又正常出现

**复现步骤**
Edge上第一次安装后使用或者更改设置，例如侧边栏弹出位置

**问题截图**
![image](https://user-images.githubusercontent.com/10537724/75620188-9c3edc80-5b53-11ea-99a2-893ca6a7867a.png)

**使用环境**
Microsoft Edge: Version 80.0.361.62 (Official build) (64-bit)
Edge: v1.72

**Comment by nickyc975** [comment]
收到，我们会尽快确认并修复的，感谢反馈！

**Comment by nickyc975** [comment]
我实测并没有遇到你描述的这个问题，会不会是那个Edge版本的Bug？

**Comment by kimlym** [comment]
啊，有可能的，谢谢查看
