### ISSUE TITLE
互譯模式失效

### ISSUE THREAD

**Issue by vaz1306011** [EdgeTranslate/EdgeTranslate#540]
**describe the bug描述问题**

互譯模式沒有用

**steps to reproduce复现步骤**

開啟互譯模式
選擇 英文<->繁體中文
輸入中文或使用劃詞翻譯翻譯中文
使用混合翻譯或谷歌翻譯

**issue screenshot 问题截图**

![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/50329983/7af0b737-c4af-4ee5-b93f-e30c0a03227e)
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/50329983/67c75e4c-40d1-40f1-baa3-a30533a47608)

**environment 使用环境**

edge 115.0.1901.183
插件版本 2.4.0

**Comment by YunFeng0817** [comment]
確實存在這個問題，我會盡快檢查一下

**Comment by QGB** [comment]
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/8005654/3a08002f-7603-4fff-b1ff-af225027af2f)
@YunFeng0817  谷歌页面翻译失效

**Comment by nickyc975** [comment]
已修復，感謝反饋。

**Comment by QGB** [comment]
> 

https://microsoftedge.microsoft.com/addons/detail/%E4%BE%A7%E8%BE%B9%E7%BF%BB%E8%AF%91/bfdogplmndidlpjfhoijckpakkdjkkil?hl=zh-CN       这里还没更新
