### ISSUE TITLE
无法使用google网页翻译

### ISSUE THREAD

**Issue by hh958877** [EdgeTranslate/EdgeTranslate#541]
**describe the bug描述问题**
今天开始无法使用google网页翻译

_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
按照

**testable address 出现问题的网址**
所有英文网页

_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**
点击插件中的“谷歌网页翻译”按钮

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**
![2023-07-26_092057](https://github.com/EdgeTranslate/EdgeTranslate/assets/140569669/c7e14eec-e151-42df-8b95-a4d18cf0feb8)

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**

_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_
edge浏览器

_browser version 浏览器版本 [e.g. 22]_

_extension version 插件版本 [e.g. 2.0.0]_

**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by moriyan0116** [comment]
Same problem in en to ja. But page translation in translate.google.com works.

**Comment by hzkbj** [comment]
一样的问题，所有网页都无法翻译，会提示：错误：服务器无法完成您的请求。请稍后再试。

**Comment by kangdol** [comment]
same in ko too

**Comment by kangdol** [comment]
I think this is api problem

**Comment by allen365apple** [comment]
我也遇到同樣的問題！

**Comment by nickyc975** [comment]
感谢各位的反馈。我们已经定位到了问题的根源，正在修复。请等待下次更新。

Thanks for your feedbacks. We have addressed the cause of the problem and are working on it. Please wait for the next update.
