### ISSUE TITLE
SERVER NOT WORKING

### ISSUE THREAD

**Issue by getgready** [EdgeTranslate/EdgeTranslate#542]
Could you please solve the problem in this picture : https://github.com/EdgeTranslate/EdgeTranslate/assets/140671128/34575393-8f6f-4b2e-a25b-d001234c7fd0

waiting for your reply

**Comment by getgready** [comment]
Could you please solve this issue shown in this link : https://github.com/EdgeTranslate/EdgeTranslate/assets/140671128/8ab258bd-dd36-4252-92da-936f899c4cc7

**Comment by getgready** [comment]
Could you please solve this issue shown in this link : https://github.com/EdgeTranslate/EdgeTranslate/assets/140671128/8ab258bd-dd36-4252-92da-936f899c4cc7

**Comment by andika207** [comment]
@getgready même problème ici depuis quelques jours. je croyais que la cause était mon chrome 86 mais je vois que non.
<html>
<body>


Error: The server could not complete your request. Try again later. | Error: The server could not complete your request. Try again later.
-- | --


</body>
</html>

**Comment by getgready** [comment]
> @getgready même problème ici depuis quelques jours. je croyais que la cause était mon chrome 86 mais je vois que non.
> 
> Error: The server could not complete your request. Try again later.	Error: The server could not complete your request. Try again later.

ET Comment informer le fondateur de EdgeTranslate)?

**Comment by nickyc975** [comment]
感谢各位的反馈。我们已经定位到了问题的根源，正在修复。请等待下次更新。

Thanks for your feedbacks. We have addressed the cause of the problem and are working on it. Please wait for the next update.

**Comment by andika207** [comment]
@nickyc975 
<a href='https://postimg.cc/kR8PL8Mb' target='_blank'><img src='https://i.postimg.cc/nrSVjY60/screenshot-2.png' border='0' alt='screenshot-2'/></a>

**Comment by andika207** [comment]
@nickyc975 
<a href='https://postimg.cc/kR8PL8Mb' target='_blank'><img src='https://i.postimg.cc/kR8PL8Mb/screenshot-2.png' border='0' alt='screenshot-2'/></a>

**Comment by andika207** [comment]
> ET Comment informer le fondateur de EdgeTranslate)?

@getgready question bête. les dévelopeurs sont au courant si vous écrivez ici
