### ISSUE TITLE
Very serious issue , need you help urgently

### ISSUE THREAD

**Issue by getgready** [EdgeTranslate/EdgeTranslate#548]
Could you please solve this issue in this link : https://github.com/EdgeTranslate/EdgeTranslate/assets/140671128/cc6005b1-69d6-4b22-92c3-99b81955f166

because you told it is fixed but it is not fixed as you told.

**Comment by nickyc975** [comment]
This is fixed in the code, but you need to wait for the update to see it work.

**Comment by andika207** [comment]
@nickyc975 hopefully you soon release the update because the embedded google translator on my obsolete 360chrome doesn't work so I **have no translator right now** unlike others that use modern browsers
