### ISSUE TITLE
自从 51eaa6f 后,CSP无法正常工作,部分网页无法加载

### ISSUE THREAD

**Issue by Just-A-Pony** [EdgeTranslate/EdgeTranslate#549]
**describe the bug描述问题**

自从 51eaa6f 后, Firefox 部分网页由于 CSP 异常 无法加载
已分别构建 51eaa6f 和其前一个 commit 的 EdgeTranslate 验证

**issue screenshot 问题截图**

![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/51501756/923391dd-bf29-4104-a2d4-644f225e699f)

**environment 使用环境**

Firefox 115.0.3

**Comment by god464** [comment]
116.0.1也有类似的问题

**Comment by NWater23** [comment]
我在 #532 报告了这个问题

**Comment by nickyc975** [comment]
已修复，感谢反馈。
