### ISSUE TITLE
谷歌网页翻译工作不正常

### ISSUE THREAD

**Issue by Guwalgiyakuan** [EdgeTranslate/EdgeTranslate#55]
**描述问题**

使用网页翻译功能，英文页面谷歌的没有反应，有道的可以翻译页面。 如果网页是中文的会翻译成我的系统语言（日文）

**出现问题的网址**

https://encycolorpedia.cn/
https://teejeetech.in/

Edge Translate 设置为自动检测语言→简体中文
![image](https://user-images.githubusercontent.com/37359970/76146507-e41ab200-60c5-11ea-8ef3-8914450c14eb.png)

原始中文页面
![image](https://user-images.githubusercontent.com/37359970/76146560-660adb00-60c6-11ea-90a7-2f22dd6e4ce5.png)

使用谷歌网页翻译后出现日文
![image](https://user-images.githubusercontent.com/37359970/76146576-7e7af580-60c6-11ea-948d-a596247b6861.png)
英文页面谷歌翻译无效，有道可以正常翻译为中文。
![image](https://user-images.githubusercontent.com/37359970/76146611-b08c5780-60c6-11ea-9ac5-1204a8c3ecb9.png)

**使用环境**

_操作系统 [Ubuntu 19.10 Gnome Desktop 系统语言日文]_

_浏览器类型 [ firefox]_

_浏览器版本 [74.0b9 (64 ビット)日文版]_

_插件版本 [1.7.2]_

**补充**
网络环境可以正常浏览 google translate 网站
划词翻译没问题可以正常翻译

**Comment by nickyc975** [comment]
1. 网页翻译的语言设定与划词翻译的语言设定是相互独立的，两个网页翻译引擎都是默认翻译到系统语言，所以会将中文页面翻译到日文。

2. 你给出的那个英文页面自带了谷歌翻译功能呢，再使用插件的谷歌翻译时会出现冲突，所以会出现无法翻译的情况。除此之外，某些网页的安全设置会导致谷歌网页翻译失效，比如Github，这种我们也没办法。

**Comment by Guwalgiyakuan** [comment]
感谢解答 明白了
