### ISSUE TITLE
chatgpt429 錯誤

### ISSUE THREAD

**Issue by qq1296** [EdgeTranslate/EdgeTranslate#552]
**describe the bug描述问题**
chatgpt429 錯誤
_describe the problem you encountered 请在此详细描述你遇到的问题，例如问题的表现形式，对你造成了那些影响等_
使用gpt進行翻譯 出現Request failed with status code 429
**testable address 出现问题的网址**
pdf
_leave us a testable address(optional) 如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**steps to reproduce复现步骤**

_describe steps to reproduce 请在此给出问题的复现步骤_

**issue screenshot 问题截图**
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/141701094/3cf58186-e186-4ffd-893e-a444e264b76d)

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**environment 使用环境**
win11
_tell us your environment info,e.g.: 在这里给出你的使用环境，例如：_

_browser name 浏览器类型 [e.g. chrome, firefox]_
google
_browser version 浏览器版本 [e.g. 22]_
115.0.5790.171
_extension version 插件版本 [e.g. 2.0.0]_
2.4.0.5
**other information 其他信息**

_other information(optional) 如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
我們并沒有提供CHATGPT支持，此問題請到這裏反饋：[Jakevin](https://github.com/Jakevin/EdgeTranslate)
