### ISSUE TITLE
very urget issue

### ISSUE THREAD

**Issue by getgready** [EdgeTranslate/EdgeTranslate#553]
Why you didn't solve this issue .
It's more than 3 week and I'm still waiting for the app tobe fixed but nothing done from your side.
why?
see in this link : 
https://github.com/EdgeTranslate/EdgeTranslate/assets/140671128/0e72324e-1458-4142-9a45-84980968ccf1

**Comment by Cuongnvhs150257** [comment]
Me too

**Comment by NWater23** [comment]
Try another translate extension: https://github.com/FilipePS/Traduzir-paginas-web

**Comment by nickyc975** [comment]
This has been fixed, please wait for the update.
