### ISSUE TITLE
Firefox 插件挂了

### ISSUE THREAD

**Issue by cathaysia** [EdgeTranslate/EdgeTranslate#57]
**描述问题**

现在firefox商店已经搜不到侧边翻译啦。希望您能尽快上架。Firefox真的是找不到比这个更好的翻译软件了

**Comment by nickyc975** [comment]
火狐上是因为审核员不允许我们使用闭源的第三方库，所以被下架了。我们正在处理，顺利的话明天应该能上架，不过网页翻译功能就必须得删掉了。

**Comment by cathaysia** [comment]
多谢回复。我从github上面安装了这个插件，firefox下架了不少我喜欢的插件。。。

**Comment by nickyc975** [comment]
已经重新上架了，不过网页翻译没了。
