### ISSUE TITLE
我在firefox上使用edge translate插件，我不能理解的是为什么作为一个翻译插件不能选择语言？？？我只能把英文翻译为英文。

### ISSUE THREAD

**Issue by nehc0** [EdgeTranslate/EdgeTranslate#571]
**describe feature功能描述**

_What kind of feature/improvement would you like? 你想要什么样的功能 /改进？_

**scene used使用场景**

_Where would you need this feature/improvement? 你是在什么场景下需要用到这个功能 /改进？_

**your solution 你的解决方案**

_Do you have any solution 你有没有想到什么解决方案？_

**more information 其他信息**

_If you have any more information, please write here 如果你还需要补充什么信息，请写在这里_

**Comment by YunFeng0817** [comment]
请在浏览器的右上角点开侧边翻译按钮的图标，点击一个向下的箭头，就会弹出相应的选项
<img width="380" alt="image" src="https://github.com/EdgeTranslate/EdgeTranslate/assets/27533910/436da1c0-015f-4feb-83ad-8b7aa5001e04">
