### ISSUE TITLE
非常感谢开发Firefox版本的侧边翻译插件,是我用过最好的插件!

### ISSUE THREAD

**Issue by YanYan233** [EdgeTranslate/EdgeTranslate#58]
后续会逐步更换到edge,再次致以崇高感谢!

**Comment by nickyc975** [comment]
不客气！我们的一点业余工作能帮到这么多人，得到这么多人的喜欢，我们自己也很开心！

**Comment by SnDream** [comment]
感谢作者开发的插件，用了也有大半年了，真的非常好用。
Firefox就是这么个奇怪的浏览器，自称自由，连自定义搜索引擎都不知道怎么搞，全局手势插件的效果也很差。
看看Edge的Linux版什么时候上线，或者换回Vivaldi吧。非常感谢作者。

**Comment by mccleaner** [comment]
好不容易找到个还能用的翻译插件，，，不过我应该不会换chrome的，感谢作者。

**Comment by NivoRozer** [comment]
感谢作者，由于字体渲染的问题，我也应该不会换chrome的，我的edge自动更新已经关了:P

**Comment by nickyc975** [comment]
如果需要继续使用火狐的话，可以点[这里](https://github.com/EdgeTranslate/EdgeTranslate/releases/download/1.7.2/EdgeTranslate_firefox_v1.7.2.xpi)手动下载安装1.7.2版本，这个版本是火狐上最后一个带有网页翻译的版本了。

另外我刚才从 #60 得知火狐上可以通过一些办法安装无签名的扩展，所以我们之后应该还会继续提供功能完整的火狐版侧边翻译，只是不会在扩展商店中上架。

**Comment by zyy0831** [comment]
说一声谢谢哈！

**Comment by DandelionFlowers** [comment]
> 
> 
> 感谢作者开发的插件，用了也有大半年了，真的非常好用。
> Firefox就是这么个奇怪的浏览器，自称自由，连自定义搜索引擎都不知道怎么搞，全局手势插件的效果也很差。
> 看看Edge的Linux版什么时候上线，或者换回Vivaldi吧。非常感谢作者。

emmmmm，自定义引擎是可以实现的，需要用搜索框自己添加，不过不会同步，自由主要还是因为可以触碰到浏览器的源码，很多地方你可以自己修改，而且全局手势一大部分是win的原因。可能也是咋也不是很清楚firefox内部，嘿嘿，最后谢谢作者
