### ISSUE TITLE
当捕获单个word时，能不能显示单词的原型，因为每每抓到时态or其它状态改变的词，不知道原型，侧边栏也没显示原型，有点不方便

### ISSUE THREAD

**Issue by tomdog2016** [EdgeTranslate/EdgeTranslate#59]
**功能描述**

_你想要什么样的功能 /改进？_

**使用场景**

_你是在什么场景下需要用到这个功能 /改进？_

**你的解决方案**

_你有没有想到什么解决方案？_

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
这个可能做不到，不知道谷歌有没有提供这种接口，如果没有的话我们也没办法了。

**Comment by tomdog2016** [comment]
收到，多謝，離不開的插件了

Nicky Chen <notifications@github.com> 于 2020年3月20日周五 下午5:20写道：
