### ISSUE TITLE
能不能继续维护功能完整的Firefox插件呢?不必上架,可以让用户sideload.

### ISSUE THREAD

**Issue by RealXuChe** [EdgeTranslate/EdgeTranslate#60]
先向开发者致以感谢,你们的翻译插件是我用过的最好,功能最全的翻译插件!
如果能同时维护一个功能齐全的版本就好了,用户可以sideload,就像[EhTagTranslation/EhSyringe](https://github.com/EhTagTranslation/EhSyringe)一样.

**Comment by nickyc975** [comment]
谢谢，这确实是个解决方案。
不过目前来说，1.7.2版本还拥有签名，可以直接下载安装，之后我们如果要发布新版本的话会考虑采取这种方案的。

**Comment by a937983423** [comment]
放弃chrome吧，也不看看chrome多流氓，为了打压对手都干了啥，开源才是王道

**Comment by nickyc975** [comment]
不喜欢Chrome的话也可以考虑Edge Chromium或者Chromium，Chromium同样是开源的。

**Comment by a937983423** [comment]
> 
> 
> 不喜欢Chrome的话也可以考虑Edge Chromium或者Chromium，Chromium同样是开源的。

Edge还不是chrom的放弃吧骚年，没看google越来越流氓了吗

**Comment by RealXuChe** [comment]
> 
> 
> > 不喜欢Chrome的话也可以考虑Edge Chromium或者Chromium，Chromium同样是开源的。
> 
> Edge还不是chrom的放弃吧骚年，没看google越来越流氓了吗

我相信在这个issue下的讨论已经偏题了.这个issue只是在探讨一种绕过火狐商店审核的方式.我相信 @nickyc975 也绝对没有要卷入政治斗争的意思.

请你还是注意一下.

**Comment by SuperEndermanSM** [comment]
先向开发者致以感谢,你们的翻译插件是我用过的最好,功能最全的翻译插件!
可以在火狐商店上架的版本做一个跳转，跳转到可以网页翻译的版本么？

**Comment by chocolateEgg** [comment]
非常感谢开发者，你们的侧边翻译真的很好用！

**Comment by RealXuChe** [comment]
Release页面上并没有FF插件啊......只有source.
能不能在Release页面上放一下FF插件呢?

**Comment by nickyc975** [comment]
哦哦，忘了，这就放。
