### ISSUE TITLE
侧边翻译确实很不错，但有和其他firefox扩展一样不支持翻译pdf选定text的缺点

### ISSUE THREAD

**Issue by xxltju324** [EdgeTranslate/EdgeTranslate#61]
**功能描述**

_你想要什么样的功能 /改进？_

**使用场景**

_你是在什么场景下需要用到这个功能 /改进？_

**你的解决方案**

_你有没有想到什么解决方案？_

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
这个是火狐的Bug，火狐不允许扩展访问文件网址，所以除非火狐自己修好这个Bug，否则这个问题无解。
