### ISSUE TITLE
使用谷歌翻译进行网页全文翻译的时候功能失效。有道翻译可正常使用

### ISSUE THREAD

**Issue by euphrat1ca** [EdgeTranslate/EdgeTranslate#62]
使用谷歌网页翻译进行网页全文翻译的时候功能失效。有道网页翻译可正常使用

网页不会弹出谷歌翻译的 上边框栏

**Comment by nickyc975** [comment]
一些网页的安全设置会阻止谷歌网页翻译加载必要的组件，在这些网页上谷歌网页翻译是无法使用的，比如Github，这种问题暂时无解。

**Comment by Mark-Fenng** [comment]
PR#152解决了这个问题，更新在版本[v2.1.3](https://github.com/EdgeTranslate/EdgeTranslate/releases/tag/2.1.3)
