### ISSUE TITLE
Supporting "right to left" feature

### ISSUE THREAD

**Issue by hahossein0** [EdgeTranslate/EdgeTranslate#63]
Hi
Your product doesn't support "right to left" feature for Arabic language. This is really obstacle when I translate somethings. Please add this item.
Best regard.

**Comment by nickyc975** [comment]
Sorry, but I don't understand what is "right to left" feature. Could you please provide more details?

**Comment by hahossein0** [comment]
Arabic (like Hebrew) is written from right to left so in all software exist one feature that support this type of writing. For example by set "dir" attribute to "rtl" in Html pages. You can see Arabic text in correct way (or layout_alignParentRight in android layout). You can translate one paragraph from English to Arabic to understand what I say. Thank you very much.
Fault state
سال نو مبارک
Correct state
<div dir="rtl">سال نو مبارک<div>

**Comment by nickyc975** [comment]
Got it. We will fix this in next version.

**Comment by hahossein0** [comment]
Thank you for your effort.
