### ISSUE TITLE
谢谢侧边翻译的开发团队，这个插件做的真的很好

### ISSUE THREAD

**Issue by 15179793794** [EdgeTranslate/EdgeTranslate#64]
**功能描述**

_你想要什么样的功能 /改进？_

**使用场景**

_你是在什么场景下需要用到这个功能 /改进？_

**你的解决方案**

_你有没有想到什么解决方案？_

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
不客气，很高兴能帮到你！
