### ISSUE TITLE
希望翻译结果展示栏中能够显示所划中的词语/句子

### ISSUE THREAD

**Issue by XSHC** [EdgeTranslate/EdgeTranslate#65]
**功能描述**

希望翻译结果展示栏中能够显示所划中的词语/句子

**使用场景**

在pdf中进行划词的时候，划词可能会出现错位，多或者少划了一个字母，导致翻译出现问题。

**你的解决方案**

在展示栏的最上方，用灰色小字号显示所划中的词语/句子
或者在设置增加一个选项，用于选择是要要进行这样的显示

**替代方案**

_在没有这个功能的情况下，你有没有找到什么临时的解决方案？_

**其他信息**

_如果你还需要补充什么信息，请写在这里_

**Comment by nickyc975** [comment]
将鼠标移到翻译结果上就可以看到原始文本了，不知道这个能不能解决你的问题？
