### ISSUE TITLE
多謝,非常棒的edge擴展,但有個問題,能不能增加記憶寬度功能.

### ISSUE THREAD

**Issue by eternalcyan** [EdgeTranslate/EdgeTranslate#66]
用的新版edge,win7 x64 ultimate.
發現該插件居然不能把側邊的寬度固定,比如我覺得現實的內容太窄,拉寬點,結果下次再次打開翻譯的時候又給我縮回去了.我希望能增加記憶寬度功能,記住最後一次側邊欄的寬度,而不是每次都用一個默認的寬度值.
感謝開發,辛苦了.

**Comment by nickyc975** [comment]
收到，这是个不错的建议，我们下个版本应该会加上的，感谢反馈！
