### ISSUE TITLE
侧边弹出的翻译结果中缺少对应英文的音标

### ISSUE THREAD

**Issue by YuyanCloud** [EdgeTranslate/EdgeTranslate#67]
打开"扩展选项"中的"翻译结果设置"的"音标"后,侧边弹出的翻译结果中只有中文的拼音,缺少英文的音标

**Comment by Mark-Fenng** [comment]
我目前看到的都是正常的
![image](https://user-images.githubusercontent.com/27533910/78454222-51bbfd00-76c9-11ea-9cc4-745bf929a156.png)
如果你遇到没有音标的情况，欢迎反馈一下

**Comment by kylewen7** [comment]
我这个v1.7.2的版本更奇怪了，音标直接没有，或者出现就是不知道什么类似希腊文的东西。。。

**Comment by telanxrays** [comment]
看不到音標通常有這樣幾种情況,所選區域不是一個標準單詞,而是單詞的變形形式;所選區域是一個詞組或句子,而這個詞組或句子不在插件索引的詞典庫中.你可以自己測試下是不是這個情況.
