### ISSUE TITLE
能否考虑添加 DeepL 的翻译接口？

### ISSUE THREAD

**Issue by F-TD5X** [EdgeTranslate/EdgeTranslate#68]
**功能描述**

添加DeepL的API。

**使用场景**

在多次体验中DeepL的翻译效果都好于Google以及有道，所以希望能添加其接口

**你的解决方案**

尽管DeepL提供的是收费API选择，但可以给用户提供免费的试用API选项或者由用户自行购买授权。

**替代方案**

https://www.programmableweb.com/api/deepl-translator/sdks

**Comment by Mark-Fenng** [comment]
收到，这个源我们会考虑一下

**Comment by Sanczzg** [comment]
> 收到，这个源我们会考虑一下

这个真的真的强烈建议添加上！！！长句子翻译和网页翻译DeepL是我见过最好用的

**Comment by Light-23** [comment]
附议！！！确实好用。

**Comment by SunskyR** [comment]
如果能加上就太好了！

**Comment by Dagger-axe** [comment]
API接口的验证目前不支持中国用户，需要国外的信用卡注册才能使用。但可以参考PDF Translate这个插件的实现，直接打开web翻译后返回结果：https://github.com/yoshinobc/PDF-Translator
