### ISSUE TITLE
翻译快捷键支持

### ISSUE THREAD

**Issue by fcwys** [EdgeTranslate/EdgeTranslate#69]
**功能描述**
选中文本后快捷键翻译打开侧栏

**使用场景**
虽然自带了划词自动翻译和点击翻译，但有时候选中文本不一定需要翻译，故希望支持快捷键翻译

**Comment by Mark-Fenng** [comment]
你好，快捷键翻译是支持的。你可以右键点击浏览器右上角的侧边翻译标志，在弹出选项中点击快捷键设置进入快捷键设置页面，在这里你可以对侧边翻译的所有快捷键进行自定义。

**Comment by Mark-Fenng** [comment]
你好，快捷键翻译是支持的。你可以右键点击浏览器右上角的侧边翻译标志，在弹出选项中点击快捷键设置进入快捷键设置页面，在这里你可以对侧边翻译的所有快捷键进行自定义。

**Comment by fcwys** [comment]
额，可能我的插件版本没更新，我自己看下，谢谢!

**Comment by cloudinnng** [comment]
> 你好，快捷键翻译是支持的。你可以右键点击浏览器右上角的侧边翻译标志，在弹出选项中点击快捷键设置进入快捷键设置页面，在这里你可以对侧边翻译的所有快捷键进行自定义。

希望增加这两个按钮中英文切换的快捷键，感
![微信截图_20211213112403](https://user-images.githubusercontent.com/7448932/145747663-faadd5cd-3a7d-4f75-ad36-a2dae32930f0.png)
![微信截图_20211213112416](https://user-images.githubusercontent.com/7448932/145747675-ce4bf6e4-bd8a-4442-92d1-55454d842a02.png)
谢
