### ISSUE TITLE
edge上很棒的翻译工具

### ISSUE THREAD

**Issue by NellPoi** [EdgeTranslate/EdgeTranslate#71]
**功能描述**

1. 增加快捷键功能
2. 划词翻译逻辑需要优化

_你想要什么样的功能 /改进？_

1.关于上方第一点，有了快速翻译页面的快捷键功能，希望增加个恢复原文的快捷键
2.既然有划词自动翻译的功能，希望划词自动翻译侧栏打开后点击关闭能同时取消文本选择，不然会因为文本没有取消选择点击关闭右边侧栏又一直反复打开关不掉，关于这点我更希望能在选择文本时出现的那个图标新增一个鼠标靠近图标自动打开侧栏翻译，移开图标自动关闭侧栏

**Comment by Mark-Fenng** [comment]
两点建议都很好，以后会逐步改进。不过第二点中侧栏又一直反复打开关不掉这个问题，我没有发现，可以提供更多信息吗
