### ISSUE TITLE
Please add English Version too( automaticllay_

### ISSUE THREAD

**Issue by fisforfaheem** [EdgeTranslate/EdgeTranslate#72]
i am tired of most of this extens not being in english ...i am fro paksitan...and i also need urdu too!

**Comment by Mark-Fenng** [comment]
I'm sorry about that. We wiil add english and urdu soon.

**Comment by nickyc975** [comment]
We have changed the default language of our extension into English. Both @Mark-Fenng and I do not know anything about Urdu so I am afraid that we cannot add Urdu support temporarily. But we are considering publishing a guide about how to translate Edge Translate into your language. If you are willing to help, please wait for the guide.

**Comment by fisforfaheem** [comment]
Thanks I hope :)
