### ISSUE TITLE
网络正常却提示网络错误

### ISSUE THREAD

**Issue by ghtz08** [EdgeTranslate/EdgeTranslate#73]
**描述问题**

在网络正常的情况下，侧边栏提示**网络错误！请检查您的网络连接。错误代码: 0**。

**出现问题的网址**

目前遇到的来看，无论是在线网址还是本地文件网址都会出现这个问题，导致无法使用侧边翻译。

**复现步骤**

安装侧边翻译后，将部分设置改成如下所示：
![image](https://user-images.githubusercontent.com/28387552/80663522-cb77b880-8ac6-11ea-835c-5c86c0509d14.png)
重启后再使用侧边翻译，会出现如下图所示的情况：
![image](https://user-images.githubusercontent.com/28387552/80663861-bf402b00-8ac7-11ea-9503-97cb359b7bdd.png)

猜测是因为权限不够，这个提示与实际情况不符。

**使用环境**

操作系统：Windows 10 专业版，1909，18363.778
浏览器：基于 Chromium 的 Microsoft Edge，81.0.416.68 (官方内部版本) (64 位)
插件版本：1.7.2

**Comment by Mark-Fenng** [comment]
![image](https://user-images.githubusercontent.com/27533910/80665572-6aeb7a00-8acc-11ea-9638-3724d7f8752d.png)
你的反馈信息很好，图中的设置“单击时”会阻止后台发送翻译请求，所以如果想要正常使用软件，请设置成“在所有网站上”。请你不必担心隐私问题，软件的代码全是开源的，你可以自行查看。

**Comment by ghtz08** [comment]
感谢，将**站点访问权限**设置成**在所有网站上**确实可以解决提示网络错误的问题。

**Comment by Zhang-986** [comment]
还是不行

**Comment by xuyington** [comment]
> 感谢，将**站点访问权限**设置成**在所有网站上**确实可以解决提示网络错误的问题。



> ![image](https://user-images.githubusercontent.com/27533910/80665572-6aeb7a00-8acc-11ea-9638-3724d7f8752d.png) 你的反馈信息很好，图中的设置“单击时”会阻止后台发送翻译请求，所以如果想要正常使用软件，请设置成“在所有网站上”。请你不必担心隐私问题，软件的代码全是开源的，你可以自行查看。

还是显示网络问题，该怎么办呢

**Comment by est56** [comment]
将站点访问权限设置成所有网站为何还是不能解决网络错误的问题
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/165552203/914d7a7f-4496-45d9-b399-1cf9b4e780be)
![image](https://github.com/EdgeTranslate/EdgeTranslate/assets/165552203/fed34217-be92-4ff4-bf61-3e0aa32da603)

**Comment by ghtz08** [comment]
应该是作者停止维护了，之前的翻译api变了
