### ISSUE TITLE
希望可以增加一些更方便朗读内容的方法

### ISSUE THREAD

**Issue by ghtz08** [EdgeTranslate/EdgeTranslate#74]
**功能描述**

非常感谢能提供一个这么好用的翻译扩展。使用过程中在朗读方面遇到一些不方便的地方，希望可以增加下面这两项内容：

1. 鼠标移入朗读图标时开始朗读相应的内容。
2. 使用快捷键朗读内容时即使没有弹出侧边翻译栏也朗读当前选中的原始内容或者翻译内容（目前 1.7.2 朗读的是上一次选中的内容而不是当前选中的内容）。

**使用场景**

1. 单手操作鼠标时，移入朗读图标比移入再点击更轻松。
2. 有时这个单词其实我明白它的意思但我忘了它的读法，这时使用快捷键在不弹出侧边翻译栏的情况下进行朗读无疑是一种体验更好的方式。

**你的解决方案**

1. 鼠标移入侧边栏的朗读图标时开始朗读。
2. 在选择文字的情况下，触发朗读时如果当前缓存的是上一次的文字就更新为当前选中的文字。（这里不知是否可以设置左键翻译小图标弹出侧边翻译栏，右键朗读（具体是朗读原始内容还是翻译内容可以在设置中选择））

**替代方案**

1. 只能通过点击的方式。
2. 设置翻译的快捷键，每次需要读音时的操作流程：按下翻译的快捷键 --> 按下朗读的快捷键 --> 鼠标单击空白处关闭侧边栏，或者设置选中立即翻译来简化步骤，但依然不是最简单的方式，并且还带来了副作用，因为很多时候我不需要立即翻译。

**Comment by Mark-Fenng** [comment]
感谢，这个问题之后会考虑优化

**Comment by nickyc975** [comment]
如果改成阅读选中文本一个快捷键，阅读翻译框中的原始文本一个快捷键，阅读翻译结果一个快捷键，第一个快捷键任何时候都有效，后两个快捷键只在翻译框展开时有效，这样你觉得可以接受吗？ @ghtz08

**Comment by ghtz08** [comment]
@nickyc975 
很开心你们团队能这么快给出具体的开发方案，你的这种解决方案已经足以满足我的个人需求。
在这其中我有一些不理解的地方，`阅读选中文本`与`阅读翻译框中原始文本`这两种行为并没有使用时间段上的冲突，为什么要分开使用不同的快捷键设定呢？是因为技术上存在某些限制导致不能这么实现吗？
最后，五一快乐！

**Comment by nickyc975** [comment]
> @nickyc975
> 很开心你们团队能这么快给出具体的开发方案，你的这种解决方案已经足以满足我的个人需求。
> 在这其中我有一些不理解的地方，`阅读选中文本`与`阅读翻译框中原始文本`这两种行为并没有使用时间段上的冲突，为什么要分开使用不同的快捷键设定呢？是因为技术上存在某些限制导致不能这么实现吗？
> 最后，五一快乐！

这个是考虑到如果用户在展开翻译框的情况下，如果又重新选择了文本，那么选中文本和原始文本将是不同的。

另外我还增加了右键点击按钮朗读功能，并且在浏览器的右键菜单中也加上了朗读选项。

**Comment by ghtz08** [comment]
你们考虑的很周全，这是我所没有考虑到的，谢谢你们！
