### ISSUE TITLE
如何关闭PDF文件支持

### ISSUE THREAD

**Issue by Jimmyzm** [EdgeTranslate/EdgeTranslate#75]
**描述问题**

我想使用浏览器自带pdf阅读器，如何关闭插件的pdf文件支持？

**使用环境**

Chrome/Edge

**Comment by Mark-Fenng** [comment]
1. 右键点击浏览器右上角的侧边翻译图标，点击如下图的“选项”两字。
![image](https://user-images.githubusercontent.com/27533910/80854690-c8b6c800-8c6c-11ea-9244-d77969897f41.png)
2. 在弹出的选项界面中，将“其他设置”中的“使用内置PDF查看器”的选项关闭即可。
![image](https://user-images.githubusercontent.com/27533910/80854719-1df2d980-8c6d-11ea-82a7-aab87b305356.png)

**Comment by lfydegithub** [comment]
侧边翻译自带的pdf阅读器要怎么才能使用呢?直接把pdf拽到网页里吗

**Comment by Mark-Fenng** [comment]
> 侧边翻译自带的pdf阅读器要怎么才能使用呢?直接把pdf拽到网页里吗

如果初次使用，需要在扩展管理页面打开允许访问文件的权限
例如 chrome上的管理页面是 chrome://extensions/?id=bocbaocobfecmglnmeaeppambideimao

**Comment by dumbkitty** [comment]
在默认用edge阅读器打开pdf时，如何使用翻译呢。

**Comment by yaochao05** [comment]
这个矛盾产生的根本原因是，打开这个选项，然后中文pdf无法正常显示，有中文的地方是空白
![image](https://user-images.githubusercontent.com/52551420/149054576-6d00c34c-d982-41ee-a8a5-d00c51af4228.png)
实际图
![image](https://user-images.githubusercontent.com/52551420/149054664-cbfe7b5e-f7f9-48fa-a07f-203960221e7b.png)
