### ISSUE TITLE
侧边翻译1.8版本，PDF划词翻译失效

### ISSUE THREAD

**Issue by qianqianjun** [EdgeTranslate/EdgeTranslate#76]
**描述问题**

侧边翻译1.8版本，PDF划词翻译失效（网页划词翻译可以使用）。

**出现问题的网址**

本地PDF文件在浏览器打开后跳转到的网址。

**复现步骤**

- 使用谷歌浏览器打开本地一篇PDF文档
- 使用侧边翻译插件，选中一句话，点击翻译按钮，右侧边栏出现，但是没有翻译结果。
- 选择一个英文网站进行测试，发现翻译功能没问题。

**问题截图**

本地的PDF文件出现划词翻译故障
[![YCIhK.png](https://cdn.img.wenhairu.com/images/2020/05/06/YCIhK.png)](https://img.wenhairu.com/image/YCIhK)
其它英文网站功能正常
[![YC44g.png](https://cdn.img.wenhairu.com/images/2020/05/06/YC44g.png)](https://img.wenhairu.com/image/YC44g)

**使用环境**
- 操作系统：Ubuntu 18.04.4 LTS
- 浏览器类型:  Google Chrome 
- 浏览器版本: 81.0.4044.129（正式版本） （64 位）
- 插件版本: 1.8.0

**其他信息**

无

**Comment by nickyc975** [comment]
收到，已定位问题所在，我们会尽快修复。
