### ISSUE TITLE
更新插件后翻译空白，用的是有道翻译，不是谷歌翻译

### ISSUE THREAD

**Issue by polar1shu** [EdgeTranslate/EdgeTranslate#77]
**描述问题**

更新插件后翻译空白，用的是有道翻译，不是谷歌翻译，无法获取pdf的翻译内容。

**出现问题的网址**

![image](https://user-images.githubusercontent.com/19658556/81167034-19a92200-8fc7-11ea-89c7-30e23280be97.png)

**复现步骤**

随便找一个英文的pdf打开后，翻译就是这样。

**问题截图**

![image](https://user-images.githubusercontent.com/19658556/81167049-1e6dd600-8fc7-11ea-81c7-af12e5a98e45.png)

Error handling response: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem:".

这个是扩展程序的报错信息

**使用环境**

_在这里给出你的使用环境，例如：_

chrome 81.0.4044.129 macbook pro
插件版本1.80

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
这个问题已经修复了，请等待新版本通过审核后更新即可。
