### ISSUE TITLE
朗读功能在关闭侧边后不停止

### ISSUE THREAD

**Issue by ruiyushen** [EdgeTranslate/EdgeTranslate#79]
**描述问题**
翻译后侧边点击播放声音，之后点击空白部分侧边关闭，但朗读功能却继续，导致无法停止朗读。

**使用环境**
Windows 10
Chrome

**Comment by nickyc975** [comment]
这个。。。不能算是问题吧，你是希望能够手动中止朗读吗？

**Comment by ruiyushen** [comment]
w

> 这个。。。不能算是问题吧，你是希望能够手动中止朗读吗？

我终止不了朗读，有时候选中一大长串，点一下边上就一直读还停不了。我建议关闭侧边后朗读自动停止。

**Comment by nickyc975** [comment]
收到，后续我们会加上停止朗读的功能的。

**Comment by ruiyushen** [comment]
好的，加油！
