### ISSUE TITLE
在github网站无法正常使用插件内的谷歌网页翻译功能

### ISSUE THREAD

**Issue by LiSheng2099** [EdgeTranslate/EdgeTranslate#80]
**描述问题**

无法正常使用谷歌网页翻译。

**出现问题的网址**

_github网站_

**复现步骤**

_直接在任一github网页使用谷歌网页翻译功能即可_

**问题截图**

_我好像不会使用这里的上传截图功能哈哈……_

**使用环境**

_浏览器类型 [新版EDGE]_

_浏览器版本 [版本 81.0.416.72 (官方内部版本) (64 位)]_

_插件版本 [1.8.1]_

**Comment by Mark-Fenng** [comment]
感谢反馈，但是由于github独特的安全策略，在这个网站上实在没有办法使用谷歌网页翻译。你可以试试有道网页翻译，它在github上是可以正常用的，只是体验不如谷歌翻译
