### ISSUE TITLE
在某些网页选中单词后翻译的小图标显示不正常

### ISSUE THREAD

**Issue by ghtz08** [EdgeTranslate/EdgeTranslate#81]
**描述问题**

在网页上选中单词弹出的图标不正常。

**出现问题的网址**

http://www.mikewootc.com/wiki/tool/sw_develop/gtest_usage.html

**复现步骤**

选中、双击触发翻译即可看到。

**问题截图**
![image](https://user-images.githubusercontent.com/28387552/81936416-d54ffe80-9624-11ea-84f7-158e07d22087.png)

**使用环境**

浏览器类型：基于 Chromium 的 Microsoft Edge

浏览器版本：81.0.416.72

插件版本：1.8.1

**Comment by Mark-Fenng** [comment]
感谢反馈，会尽快修复～
