### ISSUE TITLE
弹出的翻译小图标超出界面外

### ISSUE THREAD

**Issue by ghtz08** [EdgeTranslate/EdgeTranslate#82]
**描述问题**

在使用百度搜索时，选择搜索框中的单词之后弹出的翻译小图标会超出界面。

**出现问题的网址**

https://www.baidu.com/s?wd=hello

**复现步骤**

使用百度搜索英语句子，选中单词就可以复现。

**问题截图**

![image](https://user-images.githubusercontent.com/28387552/81938081-04676f80-9627-11ea-978b-c0edc9355177.png)

**使用环境**

浏览器类型：基于 Chromium 的 Microsoft Edge

浏览器版本：81.0.416.72

插件版本：1.8.1

**Comment by Mark-Fenng** [comment]
感谢反馈～
