### ISSUE TITLE
建議增加一個焦點變換後關閉彈窗功能(鼠標點擊頁面後自動關閉)

### ISSUE THREAD

**Issue by telanxrays** [EdgeTranslate/EdgeTranslate#83]
很多時候翻譯後只需要看一眼,然後就可以關閉了,但需要找X圖標或者按Alt-C去關掉彈出窗口,這就很不人性化,應該增加一個功能,只要單詞取消被選擇,也就是說焦點變成網頁而不是單詞本身之時,就自動退出關閉翻譯彈出窗口,可以和現在的保持彈出窗口功能同時存在,增加一個選項即可,讓用戶可以自行選擇關閉模式.

希望增加這樣一個功能,讓插件稍許人性化,謝謝.

**Comment by Mark-Fenng** [comment]
我們已經有一個功能可能滿足你的需要：
將側邊欄取消固定（點擊關閉按鈕左邊的圖釘按鈕）後，只要點擊網頁任何地方，側邊欄會自動關閉，你可以試一試~

**Comment by telanxrays** [comment]
> 我們已經有一個功能可能滿足你的需要：
> 將側邊欄取消固定（點擊關閉按鈕左邊的圖釘按鈕）後，只要點擊網頁任何地方，側邊欄會自動關閉，你可以試一試~

原來是我按了圖釘,自己都沒發覺.哈哈,多謝提醒了.好用~
