### ISSUE TITLE
翻译结果改进

### ISSUE THREAD

**Issue by ulpyuxa** [EdgeTranslate/EdgeTranslate#85]
**功能描述**

翻译结果能否按选择的文字增加换行处理

**使用场景**

如：我选择了多行文本框中的内容（有多行英语语句），但翻译结果就只有一行了，翻译的结果看起来很乱。
如下图
[https://drive.google.com/file/d/1PDczi9T-5LLBiHQvnXb_NSjthOsmKGTi/view?usp=sharing](url)

**Comment by Mark-Fenng** [comment]
建议很好，现在的是不美观，之后想办法优化一下
