### ISSUE TITLE
插件失效

### ISSUE THREAD

**Issue by Sivyer9303** [EdgeTranslate/EdgeTranslate#86]
**描述问题**
安装完成后，刚开始是可以正常使用的，但是第二天不行了，不知道是不是因为我中间更换了一次ssr节点的原因，现在无论使用什么网络连接方式都没办法生效。但直接访问谷歌翻译或者有道翻译都没有问题。
PS:使用有道或者谷歌翻译都不行

**出现问题的网址**
和网址无关，在任意网站都无法使用。

**复现步骤**
猜测可能的步骤是，在安装后更换网络连接。

**问题截图**
![image](https://user-images.githubusercontent.com/33290356/82626408-55c0c180-9c1a-11ea-8bbe-64610bc0c8c0.png)
(为了避免图片裂开，选中词语进行翻译后，会一直处于loading中，然后过一会会出现网络连接错误的信息，错误代码0 )

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

windows-win7

_浏览器类型 Chrome

_浏览器版本 72.0.3626.121

_插件版本 1.8.1

**其他信息**
禁用后重新启用仍然不起作用，卸载插件重新安装仍然不起作用。
PS：十分好用的插件，感谢~

**Comment by Mark-Fenng** [comment]
有没有可能是代理的问题呢，比如ss, SwitchyOmega
你看看能不能直接在网页打开
https://translate.google.cn/
这个网址呢

**Comment by Sivyer9303** [comment]
> 有没有可能是代理的问题呢，比如ss, SwitchyOmega
> 你看看能不能直接在网页打开
> https://translate.google.cn/
> 这个网址呢

应该不是代理的问题，网页可以正常打开

**Comment by Sivyer9303** [comment]
晚上我回去调整一下代码再试试，感谢回复~

**Comment by Mark-Fenng** [comment]
不应该呀，.cn没有墙的问题呀，应该是代理出问题了

**Comment by Sivyer9303** [comment]
> 不应该呀，.cn没有墙的问题呀，应该是代理出问题了

确实是代理问题，打扰了~
