### ISSUE TITLE
读单词的时候第一次往往声音没播出来或者只播了一半

### ISSUE THREAD

**Issue by gottaegbert** [EdgeTranslate/EdgeTranslate#88]
**描述问题**

读单词的时候第一次往往声音没播出来或者只播了一半

**出现问题的网址**

_如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**复现步骤**

_请在此给出问题的复现步骤_

**问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

_在这里给出你的使用环境，例如：_

_浏览器类型 [e.g. chrome, firefox]_

_浏览器版本 [e.g. 22]_

_插件版本 [e.g. 1.2.0]_

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
没太懂你的意思，可以详细描述一下吗？

**Comment by gottaegbert** [comment]
您好，就是点击翻译然后点击播放单词发音，出现上述问题
