### ISSUE TITLE
长句翻译不完整

### ISSUE THREAD

**Issue by shuishishan** [EdgeTranslate/EdgeTranslate#89]
**描述问题**

您好，在德语文献翻译时，对划出的较长句子只会翻译前一两句

**出现问题的网址**

_如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**复现步骤**

_请在此给出问题的复现步骤_

**问题截图**

https://anonfiles.com/v3O6d046of/_2020-06-01_001614_jpg

**使用环境**

_在这里给出你的使用环境，例如：_

chrome

版本 83.0.4103.61（正式版本） （64 位）

_插件版本 1.8.1

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
我在网页上测试了并没有发现这个问题。如果是PDF文件中出现的，那应该是你没有选完，因为插件内置的PDF阅读器在选中文本时显示的高亮可能会与实际选中的文本不一致，这个我们暂时没办法。
