### ISSUE TITLE
一种可能的获得Mozilla签名的办法?

### ISSUE THREAD

**Issue by RealXuChe** [EdgeTranslate/EdgeTranslate#90]
似乎在开发者中心里可以选择自行托管,然后Mozilla就不会审核直接签名.可以把签名后的扩展放到项目的Release里,以供下载.
这样的话,用户就不用安装Firefox beta或ESR也能用了.

**Comment by nickyc975** [comment]
自行托管也是需要经过审核的，并不能绕过审核获得签名。
