### ISSUE TITLE
Android develop文档页无法翻译，弹出的翻译页面全白；

### ISSUE THREAD

**Issue by zeropercenthappy** [EdgeTranslate/EdgeTranslate#91]
**描述问题**

Android develop文档页无法翻译，弹出的翻译页面全白，其它页面正常；

**出现问题的网址**

（无需梯子）
https://developer.android.google.cn/training/constraint-layout/motionlayout/ref/keyframeset?hl=en

**复现步骤**

只要在该页面内呼出翻译组件，无论是右键选择翻译还是主动点开组件再粘贴翻译，均白屏；

**问题截图**

**使用环境**

_浏览器类型 Firefox

_浏览器版本 77.01

_插件版本 1.8.0

**其他信息**

**Comment by Mark-Fenng** [comment]
收到，在火狐上确实有这个问题
