### ISSUE TITLE
内置的PDF阅读器无法显示中文

### ISSUE THREAD

**Issue by ylzf0000** [EdgeTranslate/EdgeTranslate#93]
内置的PDF阅读器查看有中文的PDF时无法显示中文

**问题截图**

![image](https://user-images.githubusercontent.com/17083562/86218967-193a9b00-bbb4-11ea-8075-6cef55ff1f37.png)

**使用环境**

新版Edge：83.0.478.56

**Comment by ylzf0000** [comment]
![image](https://user-images.githubusercontent.com/17083562/86219107-5010b100-bbb4-11ea-8303-136185d1dfdb.png)

**Comment by nickyc975** [comment]
可以提供一下pdf文件吗？

**Comment by ylzf0000** [comment]
> 可以提供一下pdf文件吗？
[基于机器视觉的工矿现场粉尘实时监测_谢鹏程.pdf](https://github.com/EdgeTranslate/EdgeTranslate/files/4856937/_.pdf)

**Comment by nickyc975** [comment]
已修复，请等待下个版本更新。
