### ISSUE TITLE
新版edge上 pdf插件出现bug

### ISSUE THREAD

**Issue by 00LT00** [EdgeTranslate/EdgeTranslate#94]
**描述问题**

打开一个名字中带有 & 符号的pdf文件，翻译自带的那个pdf插件会无法读取，应该是因为&被浏览器进行url的相应操作了，不知道你们有什么解决办法

**使用环境**

_浏览器类型 [e.g. chrome, firefox]_

新版edge

_浏览器版本 [e.g. 22]_

 85.0.552.1

_插件版本 [e.g. 1.2.0]_

1.9.0

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
收到，下个版本修复。
