### ISSUE TITLE
当复制文本时，插件会其实现

### ISSUE THREAD

**Issue by L-Super** [EdgeTranslate/EdgeTranslate#96]
**描述问题**

每次选中文本，只是为了复制，或者其它，并非划词翻译，然而就弹出来，影响文本的选中。现象主要为，未选中的文中一起选中，经测试，由此插件导致，希望后期能够修复这个问题，在复制文本的时候，不会有所影响。

**出现问题的网址**

_如果问题仅在某些特定的网页上出现，请在此给出网页链接_

**复现步骤**

_请在此给出问题的复现步骤_

**问题截图**

_可以的话，最好再给出出现问题时的截图（注意隐藏你的个人信息）_

**使用环境**

_在这里给出你的使用环境，例如：_

_浏览器类型 [e.g. chrome, firefox]_

_浏览器版本 [e.g. 22]_

_插件版本 [e.g. 1.2.0]_

**其他信息**

_如果还有其他相关信息，请补充到这里_

**Comment by nickyc975** [comment]
方便提供具体的网址吗？
我们目前并未遇到过这个问题，无法复现，也就无法修复。

**Comment by L-Super** [comment]
基本所有网页均会出现此问题，当卸载插件选中文字则不会有此问题。建议卸载插件，安装插件后都试一下，可以看出区别。

**Comment by nickyc975** [comment]
我没太懂你的意思，你是想说，启用插件后，选择文本时会出现问题是吗？

**Comment by L-Super** [comment]
对的，启用插件后，选中文本复制会受到影响

**Comment by nickyc975** [comment]
影响就是你所说的会复制未选中部分是吗？

**Comment by L-Super** [comment]
对

**Comment by nickyc975** [comment]
是在pdf阅读器里出现的这个问题吗？
因为在网页上我们从来没有遇到过这个问题。

**Comment by L-Super** [comment]
网页上，我的设备联想小新air 2018，可能设备问题？

**Comment by nickyc975** [comment]
这个不应该啊，在Github上会出问题吗？可不可以录个视频或者动图之类的？

**Comment by L-Super** [comment]
https://ws28.cn/f/3021flzivz1
录制了一个视频，希望能看到这个问题

**Comment by nickyc975** [comment]
我测试了一下，这个应该是你选择文本的时候在文本的空白处松开了鼠标导致的，跟插件应该没有关系，我禁用插件后依然会出现这样的情况。

建议你选择文本的时候在你要选中的最后一个字后面松开鼠标，这样应该就不会出现问题了。
