### ISSUE TITLE
无法自定义划词查询的目标语言。

### ISSUE THREAD

**Issue by Sunnywin666** [EdgeTranslate/EdgeTranslate#97]
源语言：英语，划词显示翻译为英语而不是中文，没找到地方改成中文

![图片](https://user-images.githubusercontent.com/66147219/87728565-daf7cb00-c7b2-11ea-8d0b-7d0a51840d61.png)

Firefox 78.0.2

插件版本1.7.2

**Comment by nickyc975** [comment]
点击浏览器右上角的侧边翻译图标，然后点击弹出框中的那个向下的箭头就可以看到语言设定了。
