### ISSUE TITLE
音标不显示或显示错误

### ISSUE THREAD

**Issue by waipcat** [EdgeTranslate/EdgeTranslate#99]
**描述问题**

单词翻译中普遍不显示音标，有些显示但显示错误

**复现步骤**

错误显示单词：sporting    音标中出现了大写字母，且有非音标字符出现
不显示举例：网页内划词翻译surface，model

**使用环境**

Microsoft Edge 版本 84.0.522.40 (官方内部版本) (64 位)

_插件版本 1.9.0

**其他信息**

1.建议对不同信息做明确的分割，比如，释义，音标，例句之间，可做线分割或色块分割
2.建议取消中文解释的拼音标注

**Comment by nickyc975** [comment]
1. 音标这个问题我们暂时也没有什么好的解决方案，谷歌翻译返回的音标就是这样。
2. 信息展示优化这个是个不错的建议，我们会考虑优化的。
3. 取消中文拼音这个你可以去设置里取消勾选音标那一项。

**Comment by befantasy** [comment]
音标这个太麻烦了，之前是几乎都不会显示。
今天你敢信了一下，好像大多都能显示了，但显示的基本都是错的。。。
比如release，issue，request

**Comment by Mark-Fenng** [comment]
> 音标这个太麻烦了，之前是几乎都不会显示。
> 今天你敢信了一下，好像大多都能显示了，但显示的基本都是错的。。。
> 比如release，issue，request
这个问题没办法，谷歌翻译返回的结果就是这样的，谷歌翻译的音标不是咱从小到大学的那种音标，是它自己的表示方式。如果你想显示你认为正确的音标的话，我们目前在添加其他翻译源，以后可以换别的翻译源使用。
